Repository TencentBlueKing/bk-sops, pull requests merged in 2020-11, with the labels that each got.

#2930 improvement:分支条件显示框样式调整
  dev_log/dev/fannluo_202010301506.yaml
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
Labels: V3.6.X_dev

#2944 improvement: 文档中心跳转链接由后台动态返回(V3.6.14_for_community)
  frontend/desktop/src/assets/html/template.html
  frontend/desktop/src/components/layout/Navigator.vue
Labels: V3.6.X

#2936 improve: 页面footer添加 蓝鲸智云桌面 选项
  dev_log/dev/normal-wls_202011021754.yaml
  gcloud/core/api.py
  gcloud/core/footer/sites/open/footer.py
  locale/en/LC_MESSAGES/django.po
  locale/zh_hans/LC_MESSAGES/django.po
Labels: V3.6.X

#2935 bugfix: 修复 帮助文档 跳转链接不是最新文档版本问题
  dev_log/dev/normal-wls_202011021657.yaml
  gcloud/conf/sites/community/ver_settings.py
  gcloud/conf/sites/enterprise/ver_settings.py
  gcloud/core/context_processors.py
Labels: V3.6.X

#2938 feature: 执行方案支持文本格式的方案编辑和导出
  dev_log/dev/fannluo_202010301534.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/EditScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: V3.6.X_dev

#2941 improve: 定时插件去掉前端格式校验，支持使用变量拼接
  dev_log/dev/normal-wls_202011022038.yaml
  pipeline_plugins/components/static/components/atoms/bk/timer.js
  static/components/atoms/bk/timer.js
Labels: V3.6.X_dev

#2948 minor: separator拼写错误修改
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/HostAllocation/index.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/components/common/RenderForm/SeparatorSelect.vue
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceList.vue
  frontend/desktop/src/components/common/RenderForm/SetAllocation/index.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagHostAllocation.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagSetAllocation.vue
  frontend/desktop/src/utils/atomFilter.js
Labels: V3.6.X

#2931 bugfix: 修复自动排版时分支条件被覆盖的问题
  dev_log/dev/homholueng_202010301711.yaml
  pipeline_web/drawing_new/position.py
Labels: V3.6.X

#2939 improvement:文档中心跳转链接由后台动态返回
  dev_log/dev/fannluo_202011021944.yaml
  frontend/desktop/src/assets/html/index-dev.html
  frontend/desktop/src/assets/html/index.html
  frontend/desktop/src/components/layout/Navigator.vue
Labels: V3.6.X

#2940 bugfix:全局变量编辑点击遮罩关闭时未检测默认值变更修复
  dev_log/3.6.20/dev/fannluo_202011022005.yaml
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: V3.6.X

#2937 optimization: 当某个流程输出引用的节点未执行时，结束节点不报错，允许继续往下执行
  dev_log/dev/homholueng_202011021910.yaml
  pipeline/core/data/context.py
  pipeline/tests/core/data/test_context.py
Labels: V3.6.X

#2955 bugfix:集群分组选择器添加变量 _pipeline_var_str_value
  dev_log/dev/Atropos1999_202011061148.yaml
  pipeline_plugins/variables/collections/sites/open/cmdb/var_set_group_selector.py
Labels: 2.bug, V3.6.X_dev

#2943 improvement:节点配置面板插件或者子流程重新选择后只变更名称、版本
  dev_log/dev/fannluo_202011022123.yaml
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: V3.6.X

#2957 optimization: 优化 pipeline set_{status} 系列接口
  pipeline/models.py
Labels: V3.6.X

#2970 improvement：全局导航右侧快速入口优化
  dev_log/dev/fannluo_202011101741.yaml
  frontend/desktop/src/components/layout/Navigator.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
Labels: V3.6.X

#2967 improvmement:用户无默认项目时无权限页面跳转到权限中心权限申请页面
  dev_log/dev/fannluo_202011101125.yaml
  frontend/desktop/src/components/layout/permissionApply.vue
Labels: V3.6.X_dev

#2966 improve: s3远程插件加载支持配置源目录
  gcloud/external_plugins/admin.py
  gcloud/external_plugins/migrations/0006_s3originalsource_source_dir.py
  gcloud/external_plugins/models/origin.py
  gcloud/tests/external_plugins/models/test_cache.py
  gcloud/tests/external_plugins/models/test_origin.py
  pipeline/contrib/external_plugins/admin.py
  pipeline/contrib/external_plugins/migrations/0002_s3source_source_dir.py
  pipeline/contrib/external_plugins/models/source.py
  pipeline/contrib/external_plugins/utils/importer/s3.py
Labels: V3.6.X_dev

#2965 improvement:任务执行节点增加重试次数和跳过标识；任务节点强制失败和失败后跳过增加二次确认
  dev_log/dev/fannluo_202011092104.yaml
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/admin/manage/AdminSearch/SearchResult.vue
  frontend/desktop/src/pages/admin/statistics/Appmaker.vue
  frontend/desktop/src/pages/admin/statistics/Atom.vue
  frontend/desktop/src/pages/admin/statistics/Instance.vue
  frontend/desktop/src/pages/admin/statistics/Template.vue
  frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
  frontend/desktop/src/routers/index.js
  frontend/desktop/src/store/modules/task.js
Labels: V3.6.X_dev

#2961 feature:下拉框tag搜索支持字符串以英文逗号分隔匹配多个
  dev_log/dev/fannluo_202011081639.yaml
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
Labels: V3.6.X_dev

#2959 feature:renderform 组件内置获取任一表单值的方法
  dev_log/dev/fannluo_202011081511.yaml
  docs/develop/tag_usage_dev.md
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/components/common/RenderForm/formMixins.js
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.6.X_dev

#2933 improve: ip选择器支持动态分组
  dev_log/dev/fannluo_202010161805.yaml
  dev_log/dev/normal-wls_202010150110.yaml
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicGroup.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/MultipleIpSelector.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/SingleIpSelector.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
  frontend/desktop/src/store/index.js
  frontend/desktop/src/utils/atomFilter.js
  gcloud/utils/cmdb.py
  pipeline_plugins/cmdb_ip_picker/query.py
  pipeline_plugins/cmdb_ip_picker/utils.py
  pipeline_plugins/components/query/sites/open/cc.py
  pipeline_plugins/tests/cmdb_ip_picker/utils/test_get_ip_picker_result.py
  pipeline_plugins/variables/static/variables/cmdb/var_cmdb_ip_selector.js
  static/variables/cmdb/var_cmdb_ip_selector.js
Labels: V3.6.X_dev

#2954 feature: 添加 DummyIAM 屏蔽标准运维&权限中心交互
  config/default.py
  gcloud/iam_auth/shortcuts.py
  iam/__init__.py
  iam/dummy_iam.py
Labels: V3.6.X_dev

#2976 minor:弹窗登录小窗关闭icon样式调整
  frontend/desktop/src/config/login.js
Labels: V3.6.X

#2982 improvement:弹窗登录小窗关闭icon样式调整
  frontend/desktop/src/config/login.js
Labels: V3.6.X

#2971 improvement：全局导航右侧快速入口优化 (begin)
  dev_log/dev/fannluo_202011101741.yaml
  dev_log/dev/fannluo_202011101755.yaml
  frontend/desktop/src/assets/html/index-dev.html
  frontend/desktop/src/assets/html/index.html
  frontend/desktop/src/components/layout/Navigator.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
Labels: V3.6.X

#2977 improvement: 标准插件异步请求错误提示默认展示两行
  dev_log/dev/fannluo_202011112154.yaml
  frontend/desktop/src/App.vue
  frontend/desktop/src/config/setting.js
Labels: V3.6.X

#2981 optimization: 优化 component model 和 variable model 的加载逻辑
  config/default.py
  pipeline/component_framework/apps.py
  pipeline/component_framework/base.py
  pipeline/component_framework/context.py
  pipeline/component_framework/management/commands/update_component_models.py
  pipeline/component_framework/migrations/0007_auto_20201112_2244.py
  pipeline/component_framework/models.py
  pipeline/conf/default_settings.py
  pipeline/contrib/external_plugins/apps.py
  pipeline/utils/env.py
  pipeline/variable_framework/apps.py
  pipeline/variable_framework/context.py
  pipeline/variable_framework/management/__init__.py
  pipeline/variable_framework/management/commands/__init__.py
  pipeline/variable_framework/management/commands/update_variable_models.py
  pipeline/variable_framework/signals/handlers.py
Labels: V3.6.X

#2986 improvement:暂停节点执行时继续执行操作增加二次弹窗确认
  dev_log/dev/fannluo_202011131551.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: V3.6.X_dev

#3001 bugfix: 修复任务执行完成和失败后，职能化任务认领状态不正确的问题
  dev_log/dev/homholueng_202011171217.yaml
  gcloud/contrib/function/apps.py
  gcloud/contrib/function/handlers.py
  gcloud/taskflow3/apps.py
  gcloud/taskflow3/models.py
  gcloud/taskflow3/signals/__init__.py
  gcloud/taskflow3/signals/dispatch.py
  gcloud/taskflow3/signals/handlers.py
  scripts/new_dev_log.sh
Labels: 2.bug, V3.6.X

#3012 minor：优化输出参数`执行结果`的说明，改为`执行结果的布尔值，True or False`
  pipeline/core/flow/activity/service_activity.py
Labels: V3.6.X_dev

#3008 improve: 优化ip动态分组接口调用写法
  gcloud/utils/cmdb.py
  pipeline_plugins/cmdb_ip_picker/query.py
Labels: V3.6.X_dev

#2960 feature: 下拉框tag支持配置右侧icon按钮
  dev_log/dev/fannluo_202011081337.yaml
  docs/develop/tag_usage_dev.md
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
Labels: V3.6.X_dev

#3016 bugfix:修复 创建模块 插件服务模版名称中带有下划线导致解析失败问题
  dev_log/dev/normal-wls_202011181605.yaml
  pipeline_plugins/components/collections/sites/open/cc/base.py
Labels: V3.5.X

#3015 bugfix:修复 创建模块 插件服务模版名称中带有下划线导致解析失败问题
  dev_log/dev/normal-wls_202011181605.yaml
  pipeline_plugins/components/collections/sites/open/cc/base.py
Labels: V3.6.X

#3014 bugfix: cmdb_search_host处理agent参数时过滤ip为空的主机
  dev_log/dev/normal-wls_202011181544.yaml
  pipeline_plugins/cmdb_ip_picker/query.py
Labels: V3.6.X

#3013 improve:插件 bk_审核 增加是否阻塞选项
  pipeline_plugins/components/collections/sites/open/bk/approve/v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/bk_test/approve/test_v1_0.py
  static/components/atoms/bk/approve/v1_0.js
Labels: V3.6.X

#3007 feature: 流程模板支持配置备注信息和执行代理人
  dev_log/dev/fannluo_202011171510.yaml
  frontend/desktop/src/components/common/Individualization/MemberSelect.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/store/modules/template.js
Labels: V3.6.X_dev

#2978 minor: job快速分发文件插件 添加超时设置
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/v1_0.py
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/job_fast_push_file.js
  static/components/atoms/job/fast_push_file/v1_0.js
  static/components/atoms/job/job_fast_push_file.js
Labels: V3.6.X_dev

#3010 bugfix:修复节点配置面板点击遮罩关闭时未检测输出参数变化问题
  dev_log/dev/fannluo_202011172005.yaml
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: V3.6.X

#3019 improvement: 节点步骤名称长度限制调整为 50 个字符
  dev_log/dev/fannluo_202011191110.yaml
  frontend/desktop/src/constants/index.js
Labels: V3.6.X

#3024 bugfix:修复远程插件加载失败的问题
  dev_log/dev/fannluo_202011201501.yaml
  frontend/desktop/src/store/modules/atomForm.js
Labels: V3.6.X

#3025 V3.6.23 begin
  app.yml
  config/default.py
  dev_log/3.6.23/fannluo_202011172005.yaml
  dev_log/3.6.23/fannluo_202011191110.yaml
  dev_log/3.6.23/fannluo_202011201501.yaml
  dev_log/3.6.23/homholueng_202011171217.yaml
  dev_log/3.6.23/normal-wls_202011181544.yaml
  dev_log/3.6.23/normal-wls_202011181605.yaml
  docs/release.md
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.6.23_2020-11-20.md
Labels: V3.6.X

#3037 feature:标准插件支持配置输出表单
  docs/develop/tag_usage_dev.md
  frontend/desktop/src/components/common/Individualization/IpLogContent.vue
  frontend/desktop/src/components/common/Individualization/LogDisplay.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/components/common/RenderForm/formMixins.js
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagLogDisplay.vue
  frontend/desktop/src/components/layout/ProjectSelector.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/config/setting.js
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/atomForm.js
  frontend/desktop/src/utils/atomFilter.js
  frontend/desktop/src/utils/formSchema.js
  pipeline_plugins/components/static/components/atoms/job/job_execute_task_output.js
  static/components/atoms/job/job_execute_task_output.js
Labels: V3.6.X_dev

#3026 运营数据优化
  dev_log/dev/rykerli_202011252033.yaml
  gcloud/contrib/analysis/analyse_items/task_flow_instance.py
  gcloud/contrib/analysis/analyse_items/task_template.py
  gcloud/tasktmpl3/mixins.py
  pipeline/contrib/statistics/migrations/0012_auto_20201123_1552.py
  pipeline/contrib/statistics/models.py
  pipeline/migrations/0027_auto_20201123_1552.py
  pipeline/models.py
Labels: V3.6.X_dev

#3039 bugfix:修复子流程模板勾选的变量在父流程中复用漏判的问题
  dev_log/dev/fannluo_202011252050.yaml
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
Labels: V3.6.X

#3042 minor: add monitor API package
  api/__init__.py
  api/client.py
  api/collections/monitor.py
  api/http.py
  env.py
  pipeline_plugins/components/collections/sites/open/monitor/alarm_shield/v1_0.py
  pipeline_plugins/components/collections/sites/open/monitor/alarm_shield_disable/v1_0.py
  pipeline_plugins/components/collections/sites/open/monitor/alarm_shield_strategy/v1_0.py
  pipeline_plugins/components/query/sites/open/monitor.py
  pipeline_plugins/tests/components/collections/sites/open/monitor/__init__.py
  pipeline_plugins/tests/components/collections/sites/open/monitor/test_alarm_shield_disable.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/test_alarm_shield.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/test_alarm_shield_disable.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/test_alarm_shield_strategy.py
Labels: V3.6.X_dev

#3046 improve: 变量候选页面返回全部模版变量，不进行过滤
  dev_log/dev/normal-wls_202011301454.yaml
  gcloud/taskflow3/models.py
  gcloud/tests/taskflow3/test_api.py
Labels: V3.6.X_dev

#3033 bugfix:修复由公共流程创建的任务查看流程模板链接404的问题
  dev_log/dev/fannluo_202011242018.yaml
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
Labels: V3.6.X

#3030 improvement:模板配置通知分组支持项目自定义配置
  dev_log/dev/fannluo_202011241433.yaml
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/index.vue
  frontend/desktop/src/store/index.js
Labels: V3.6.X_dev

#3045 feature: 任务节点增加步骤名称，节点样式调整
  dev_log/dev/fannluo_202010091605.yaml
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/images/left-branchgateway-guide.gif
  frontend/desktop/src/assets/images/left-convergegateway-guide.gif
  frontend/desktop/src/assets/images/left-parallelgateway-guide.gif
  frontend/desktop/src/assets/images/left-subflow-guide.gif
  frontend/desktop/src/assets/images/left-tasknode-guide.gif
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/main.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/scss/iconfont.scss
  frontend/desktop/src/store/modules/template.js
Labels: V3.5.X

#2994 improvement:任务状态查询接口请求失败时，增加自动重试机制
  dev_log/dev/fannluo_202011161501.yaml
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: V3.6.X_dev

#2962 improve: 将引擎中的日志同步一份到pipeline.logging中，可在节点日志中查看
  config/dev.py
  config/prod.py
  config/stag.py
  pipeline/engine/core/handlers/endevent/executable_end_event.py
  pipeline/engine/core/handlers/service_activity.py
  pipeline/engine/core/schedule.py
Labels: V3.6.X_dev

#2990 improve: 各类资源实现 search_instance 接口
  dev_log/dev/normal-wls_202011141506.yaml
  gcloud/iam_auth/conf.py
  gcloud/iam_auth/resource_api/common_flow.py
  gcloud/iam_auth/resource_api/flow.py
  gcloud/iam_auth/resource_api/mini_app.py
  gcloud/iam_auth/resource_api/periodic_task.py
  gcloud/iam_auth/resource_api/project.py
  gcloud/iam_auth/resource_api/task.py
Labels: V3.6.X_dev
