Repository TencentBlueKing/bk-sops, pull requests merged in 2020-12, with the labels that each got.

#3059 bugfix:移动端接口参数适配
  frontend/mobile/src/store/modules/task.js
  frontend/mobile/src/store/modules/template.js
  frontend/mobile/src/views/task/canvas.vue
  frontend/mobile/src/views/task/create.vue
  frontend/mobile/src/views/task/reset.vue
  frontend/mobile/src/views/task/timing.vue
Labels: V3.6.X

#3036 optimization: 优化有向图环检测算法
  gcloud/tasktmpl3/api.py
  pipeline/utils/graph.py
  pipeline_web/drawing_new/rank/longest_path.py
Labels: V3.6.X

#2993 bugfix:标准插件输出参数说明不显示修复
  dev_log/dev/fannluo_202011161435.yaml
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
Labels: V3.6.X_dev

#3017 improvement: TagTree 组件，集群资源筛选变量、主机资源筛选变量拓扑组件性能优化
  dev_log/dev/fannluo_202011182135.yaml
  frontend/desktop/src/components/common/RenderForm/HostAllocation/HostFilter.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicIp.vue
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTree.vue
Labels: V3.6.X_dev

#3038 V3.6.x output form
  dev_log/dev/homholueng_202011251910.yaml
  docs/develop/tag_usage_dev.md
  frontend/desktop/src/components/common/Individualization/IpLogContent.vue
  frontend/desktop/src/components/common/Individualization/LogDisplay.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/components/common/RenderForm/formMixins.js
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagLogDisplay.vue
  frontend/desktop/src/components/layout/ProjectSelector.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/config/setting.js
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/atomForm.js
  frontend/desktop/src/utils/atomFilter.js
  frontend/desktop/src/utils/formSchema.js
  gcloud/core/resources.py
  pipeline/component_framework/base.py
  pipeline_plugins/components/collections/sites/open/job/execute_task/legacy.py
  pipeline_plugins/components/query/sites/open/job.py
  pipeline_plugins/components/static/components/atoms/job/job_execute_task_output.js
  static/components/atoms/job/job_execute_task_output.js
Labels: V3.6.X_dev

#2997 improvement:S3 插件源支持配置子目录
  dev_log/dev/fannluo_202011162001.yaml
  frontend/desktop/src/constants/manage.js
Labels: V3.6.X_dev

#3055 optimization: 为 pipeline.log LogEntry 的 logged_at 字段添加索引
  pipeline/log/migrations/0006_auto_20201201_1638.py
  pipeline/log/models.py
Labels: V3.6.X

#3056 optimization: 为 ComponentInTemplate 中的 component_code 与 instance_id 添加索引
  pipeline/contrib/statistics/migrations/0013_auto_20201201_1506.py
  pipeline/contrib/statistics/models.py
Labels: V3.6.X_dev

#3060 bugfix:修复流程模板编辑时切换业务会导致模板保存到其他业务的问题
  dev_log/dev/fannluo_202012012140.yaml
  frontend/desktop/src/App.vue
  frontend/desktop/src/components/layout/ProjectSelector.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.6.X

#3051 optimization: 修改 权限中心 拉取资源默认链接为 BK_PAAS_INNER_HOST
  config/prod.py
  config/stag.py
  dev_log/dev/normal-wls_202011301926.yaml
Labels: V3.6.X

#3043 minor: 注释和文档去掉企业版字样
  blueapps/patch/settings_open_saas.py
  config/default.py
  docs/features/mobile.md
  docs/install/mobile_deploy.md
  docs/release.md
  gcloud/conf/i18n.py
  locale/en/LC_MESSAGES/django.po
  locale/zh_hans/LC_MESSAGES/django.po
Labels: V3.6.X_dev

#3063 bugfix: 修复版本日志样式问题
  version_log/version_logs_md/V3.6.12_2020-09-16.md
  version_log/version_logs_md/V3.6.19_2020-10-27.md
  version_log/version_logs_md/V3.6.1_2020-06-29.md
  version_log/version_logs_md/V3.6.2_2020-08-11.md
  version_log/version_logs_md/V3.6.4_2020-08-19.md
  version_log/version_logs_md/V3.6.5_2020-08-26.md
  version_log/version_logs_md/V3.6.6_2020-08-27.md
  version_log/version_logs_md/V3.6.7_2020-09-03.md
  version_log/version_logs_md/V3.6.8_2020-09-07.md
  version_log/version_logs_md/V3.6.9_2020-09-08.md
Labels: V3.6.X

#3058 feature: JOB-快速执行脚本 插件添加v1.0，能够自动同步使用最新JOB脚本线上版本。
  dev_log/dev/normal-wls_202012011645.yaml
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
  pipeline_plugins/components/query/sites/open/job.py
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_0.js
  static/components/atoms/job/fast_execute_script/v1_0.js
Labels: V3.6.X_dev

#3064 improvement: renderform组件样式优化
  dev_log/dev/fannluo_202012041040.yaml
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTree.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
Labels: V3.6.X_dev

#3067 improvement:标准插件前端缓存清空逻辑优化
  frontend/desktop/src/App.vue
Labels: V3.6.X

#3068 improvement:标准插件前端缓存清空逻辑优化
  frontend/desktop/src/App.vue
Labels: V3.6.X_dev

#3083 improvement:去掉节点输出参数勾选后节点设为不可选并禁用的逻辑
  dev_log/dev/fannluo_202010211008.yaml
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: V3.5.X_dev

#3085 improve:变量候选页面返回对未引用变量进行过滤
  dev_log/dev/normal-wls_202012091851.yaml
  gcloud/taskflow3/models.py
  gcloud/tests/taskflow3/test_api.py
Labels: V3.6.X

#3092 bugfix: 修复部分中文未进行国际化问题
  dev_log/dev/normal-wls_202012111654.yaml
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/djangojs.mo
  locale/en/LC_MESSAGES/djangojs.po
  locale/zh_hans/LC_MESSAGES/django.mo
  locale/zh_hans/LC_MESSAGES/django.po
  locale/zh_hans/LC_MESSAGES/djangojs.mo
  locale/zh_hans/LC_MESSAGES/djangojs.po
Labels: V3.6.X

#3098 minor: 管理员视图周期任务列表去掉新建任务按钮
  dev_log/dev/fannluo_202012141156.yaml
  frontend/desktop/src/pages/task/PeriodicList/index.vue
Labels: V3.6.X, optimization

#3096 feature:流程模板标签功能
  frontend/desktop/src/components/common/advanceSearchForm/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/project/mandate.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/routers/index.js
  frontend/desktop/src/store/modules/project.js
  frontend/desktop/src/store/modules/template.js
Labels: V3.6.X_dev

#3126 bugfix: 移动端问题处理
  frontend/mobile/index.html
  frontend/mobile/src/main.js
  frontend/mobile/src/store/modules/component.js
  frontend/mobile/src/views/home/index.vue
Labels: V3.6.X, bug

#3129 bugfix:移动端任务列表页接口需要传project__id参数
  frontend/mobile/src/components/VantForm/VantCell.vue
  frontend/mobile/src/store/modules/taskList.js
Labels: V3.6.X

#3130 bugfix:周期任务执行历史查询参数修改
  dev_log/dev/fannluo_202012181753.yaml
  frontend/desktop/src/pages/task/PeriodicList/index.vue
Labels: V3.6.X, bug

#3121 minor: 开发日志文件生成脚本添加日志规范示例
  scripts/new_dev_log.sh
Labels: V3.6.X_dev

#3122 bugfix:修改cc-按规则修改主机自定义属性的问题（次序字典后台拿到后是字符串，获取集群属性方法错误)
  dev_log/dev/Atropos1999_202012171907.yaml
  pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/v1_0.py
Labels: V3.6.X_dev, bug

#3119 improvement:TagInt组件删除表单值时默认设置值为0
  dev_log/dev/fannluo_202012162102.yaml
  frontend/desktop/src/components/common/RenderForm/tags/TagInt.vue
Labels: V3.6.X_dev, optimization

#3109 improvement: 内部上云版oa小窗登录背景底色优化
  dev_log/dev/fannluo_202012151509.yaml
  frontend/desktop/src/config/login.js
  frontend/desktop/src/utils/guide.js
Labels: V3.6.X, optimization

#3080 bugfix: 修复创建收藏可重复提交问题
  dev_log/dev/normal-wls_202012081424.yaml
  gcloud/contrib/collection/resources.py
  pipeline/admin.py
Labels: V3.6.X

#3069 bugfix: 修复 JOB-执行作业 当 JOB 返回执行方案中带有密码时后台报错的问题
  dev_log/dev/homholueng_202012041639.yaml
  pipeline_plugins/components/query/sites/open/job.py
Labels: V3.6.X

#3111 bugfix:集群资源筛选变量tree节点禁用态不正确修复
  frontend/desktop/src/components/common/RenderForm/HostAllocation/HostFilter.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicIp.vue
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
Labels: V3.6.X, bug

#3102 bugfix: 修复在全局变量中引用节点输出时解析结果不正确的问题
  dev_log/dev/homholueng_202012142017.yaml
  pipeline_web/parser/format.py
  pipeline_web/tests/parser/format/test_classify_constants.py
  pipeline_web/tests/parser/format/test_format_web_data_to_pipeline.py
Labels: V3.6.X_dev, bug

#3105 minor:获取项目项所有模板标签api接口url修改
  frontend/desktop/src/store/modules/project.js
Labels: V3.6.X_dev

#3093 V3.6.x exclusive gateway pre resolove output err open
  dev_log/dev/homholueng_202012111711.yaml
  pipeline/engine/core/handlers/exclusive_gateway.py
Labels: V3.6.X, bug

#3120 bugfix: 列表页高级搜索历史记录不兼容已删除表单问题修复
  dev_log/dev/fannluo_202012162204.yaml
  frontend/desktop/src/components/common/advanceSearchForm/index.vue
Labels: V3.6.X_dev, bug

#3125 improve: 修复节点配置中勾选插件输入、输出到全局变量，查看全局变量”内容未自动更新问题
  dev_log/dev/v_xugzhou_202012181130.yaml
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: V3.6.X_dev

#3117 V3.6.x dev： 自动排版去掉多余提示
  dev_log/dev/v_xugzhou_202012161537.yaml
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.6.X_dev

#3108 improve: 变量面板中点击返回后面板保持在当前变量位置
  dev_log/dev/v_xugzhou202012151431.yaml
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
Labels: V3.6.X_dev, optimization

#3135 minor:移动端修改
  frontend/mobile/src/store/modules/component.js
  frontend/mobile/src/store/modules/task.js
  frontend/mobile/src/store/modules/taskList.js
  frontend/mobile/src/views/template/index.vue
Labels: V3.6.X, optimization

#3152 bugfix:job执行作业刷新按钮错位修复
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
Labels: V3.6.X_dev, bug

#3154 improvement:优化多个流程模版导出等待时间
  dev_log/dev/normal-wls_202012242220.yaml
  pipeline_web/wrapper.py
Labels: V3.6.X_dev

#3142 improvement:全局变量类型新增动态类型分组
  dev_log/dev/fannluo_202012221725.yaml
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: V3.6.X, optimization

#3141 bugfix：修复标准插件表单刷新按钮在创建任务填写表单时不显示问题；表格tag支持导入数据分页
  dev_log/dev/fannluo_202012221455.yaml
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
Labels: V3.6.X_dev, bug

#3139 improvement:插件列表分组按照特定属性值排序
  dev_log/dev/fannluo_202012211946.yaml
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.6.X_dev, optimization

#3136 feature:资源筛选变量增加主机加锁过滤选项配置
  dev_log/dev/fannluo_202012211659.yaml
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
Labels: V3.6.X, feature

#3107 bugfix:处理空子流程模版导入导致列表页问题
  dev_log/dev/normal-wls_202012151150.yaml
  gcloud/commons/template/models.py
  pipeline/models.py
Labels: V3.6.X_dev

#3081 bugfix:输出参数勾选的变量无法修改名称修复
  dev_log/dev/fannluo_202012081114.yaml
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: V3.6.X

#3169 improvement:下拉框变量搜索支持大小写模糊匹配
  dev_log/dev/fannluo_202012291136.yaml
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
Labels: V3.6.X_dev, optimization

#3146 feature: 添加 flush_expired_collections 命令，用于清理过期收藏数据
  gcloud/contrib/collection/management/__init__.py
  gcloud/contrib/collection/management/commands/__init__.py
  gcloud/contrib/collection/management/commands/flush_expired_collections.py
Labels: V3.6.X_dev

#3144 improvement: 流程、任务的表头后端支持时间字段排序
  dev_log/dev/normal-wls_202012221932.yaml
  gcloud/commons/template/resources.py
  gcloud/taskflow3/resources.py
  gcloud/tasktmpl3/resources.py
  pipeline/migrations/0028_auto_20201227_1952.py
  pipeline/models.py
Labels: V3.6.X_dev

#3023 feature: 完成插件生成器，使用命令即可生成插件所需的最基本的代码文件及目录
  docs/develop/dev_plugins.md
  gcloud/core/management/__init__.py
  gcloud/core/management/commands/__init__.py
  gcloud/core/management/commands/_template/docs_file.txt
  gcloud/core/management/commands/_template/init.txt
  gcloud/core/management/commands/_template/plugin_py.txt
  gcloud/core/management/commands/_template/static.txt
  gcloud/core/management/commands/_template/test_file.txt
  gcloud/core/management/commands/create_new_plugin.py
Labels: V3.6.X_dev

#3153 bugfix:修复任务执行方案编辑临时方案时对于相同节点名称和步骤名称的节点可选状态匹配不正确的问题
  dev_log/dev/fannluo_202012242158.yaml
  frontend/desktop/src/pages/task/TaskCreate/EditScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
Labels: V3.6.X, bug

#3173 fixbug: 创建集群2.0的bug
  dev_log/dev/spacesun_202012291607.yaml
  pipeline_plugins/components/static/components/atoms/cc/create_set/v2_0.js
Labels: V3.6.X_dev, bug

#3176 improvement:删除执行方案所需申请权限调整为flow_edit
  dev_log/dev/fannluo_202012301010.yaml
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
Labels: V3.6.X_dev, optimization

#3185 minor:顶部子导航zindex调整
  frontend/desktop/src/components/layout/Navigator.vue
Labels: V3.6.X_dev

#3187 V3.6.27 begin
  app.yml
  config/default.py
  dev_log/3.6.27/fannluo_202012081114.yaml
  dev_log/3.6.27/fannluo_202012242158.yaml
  dev_log/3.6.27/fannluo_202012301010.yaml
  dev_log/3.6.27/spacesun_202012291607.yaml
  docs/release.md
  frontend/desktop/src/pages/task/TaskCreate/EditScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  pipeline_plugins/components/static/components/atoms/cc/create_set/v2_0.js
  pipeline_plugins/tests/variables/collections/sites/open/gse_kit/__init__.py
  pipeline_plugins/tests/variables/collections/sites/open/gse_kit/test_var_gse_kit_ip_selector.py
  pipeline_plugins/variables/collections/sites/open/gse_kit/__init__.py
  pipeline_plugins/variables/collections/sites/open/gse_kit/var_gse_kit_ip_selector.py
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.6.27_2020-12-31.md
Labels: V3.6.X

#3150 fixbug:按规则修改主机自定义属性执行失败的问题
  pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/v1_0.py
Labels: V3.6.X_dev, bug

#3175 bugfix: 修复 open 版本插件 inputs_formats 问题
  pipeline_plugins/components/collections/sites/open/cc/batch_update_host/v1_0.py
  pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/v1_0.py
  pipeline_plugins/components/collections/sites/open/nodeman/create_task/v2_0.py
Labels: V3.6.X_dev, bug
