Repository TencentBlueKing/bk-sops, pull requests merged in 2020-10, with the labels that each got.

#2818 improve: 任务管理页面表格字段更改(V3.6.X_dev)
  dev_log/dev/v_xugzhou_202009291702.yaml
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: V3.6.X_dev

#2825 权限中心项目新增search_instance接口(36x)
  dev_log/dev/normal-wls_20200930.yaml
  gcloud/iam_auth/resource_api/project.py
  iam/contrib/django/dispatcher/dispatchers.py
  iam/contrib/django/dispatcher/exceptions.py
Labels: V3.6.X

#2832 minor: 修改 cc_search_object_attribute_all 函数
  dev_log/dev/Atropos1999_202010121041.yaml
  pipeline_plugins/components/query/sites/open/cc.py
Labels: V3.6.X_dev

#2837 improvement:首页收藏模板创建任务时项目选择框支持搜索
  dev_log/dev/fannluo_202010131039.yaml
  frontend/desktop/src/pages/home/SelectCreateTaskDialog.vue
Labels: V3.6.X

#2836 bugfix：公共流程模板导入失败权限判断错误修复
  dev_log/dev/fannluo_202010131034.yaml
  frontend/desktop/src/pages/template/TemplateList/ImportTemplateDialog.vue
  frontend/desktop/src/store/modules/project.js
Labels: V3.6.X

#2834 improve: start_task api 返回内容新增task_url
  dev_log/dev/normal-wls_202010111633.yaml
  docs/apidoc/en/start_task.md
  docs/apidoc/zh_hans/start_task.md
  gcloud/apigw/views/start_task.py
  gcloud/tests/apigw/views/test_start_task.py
Labels: V3.6.X_dev

#2835 bugfix: 修复 项目管理无法展示对应项目数据 和 无权限用户进入标准运维首页报错 问题
  dev_log/dev/normal-wls_202010112143.yaml
  dev_log/dev/normal-wls_202010112147.yaml
  gcloud/core/resources.py
  gcloud/iam_auth/utils.py
Labels: V3.6.X

#2811 feature: 节点步骤名称编辑，样式调整
  dev_log/dev/fannluo_202010091605.yaml
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/assets/images/left-branchgateway-guide.gif
  frontend/desktop/src/assets/images/left-convergegateway-guide.gif
  frontend/desktop/src/assets/images/left-parallelgateway-guide.gif
  frontend/desktop/src/assets/images/left-subflow-guide.gif
  frontend/desktop/src/assets/images/left-tasknode-guide.gif
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/main.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/scss/iconfont.scss
  frontend/desktop/src/store/modules/template.js
Labels: V3.6.X

#2827 feature:任务节点插件、子流程搜索支持搜索分组名称
  dev_log/dev/fannluo_202010091629.yaml
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
Labels: V3.6.X_dev

#2817 feature: 完成插件 监控平台(Monitor)-蓝鲸监控告警屏蔽解除
  dev_log/dev/Atropos1999_202009291444.yaml
  packages/blueking/component/apis/monitor.py
  packages/blueking/component/collections.py
  pipeline_plugins/components/collections/sites/open/docs/monitor/alarm_shield_disable.md
  pipeline_plugins/components/collections/sites/open/docs/monitor/image/monitor_alarm_shield_disable.png
  pipeline_plugins/components/collections/sites/open/monitor/__init__.py
  pipeline_plugins/components/collections/sites/open/monitor/alarm_shield_disable/__init__.py
  pipeline_plugins/components/collections/sites/open/monitor/alarm_shield_disable/v1_0.py
  pipeline_plugins/components/static/components/atoms/monitor/alarm_shield_disable/v1_0.js
  pipeline_plugins/tests/components/collections/sites/open/monitor/__init__.py
  pipeline_plugins/tests/components/collections/sites/open/monitor/test_alarm_shield_disable.py
  static/components/atoms/monitor/alarm_shield_disable/v1_0.js
Labels: V3.6.X_dev

#2840 bugfix: 修复轻应用迁移时生成的前缀链接错误的问题
  gcloud/contrib/admin/migration_api/app_maker.py
Labels: 2.bug, V3.6.X

#2846 bugfix:节点标签下拉框zIndex层级问题修复
  dev_log/dev/fannluo_202010151958.yaml
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
Labels: V3.6.X

#2849 feature: 合并drf分支相关代码
  config/default.py
  dev_log/dev/fannluo_202009121830.yaml
  dev_log/dev/normal-wls_202009092249.yaml
  dev_log/dev/v_xugzhou_202009181447.yaml
  dev_log/dev/v_xugzhou_202009211409.yaml
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/HostAllocation/HostFilter.vue
  frontend/desktop/src/components/common/RenderForm/HostAllocation/index.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagHostAllocation.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/main.js
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/project/mandate.vue
  frontend/desktop/src/store/index.js
  frontend/desktop/src/store/modules/manage.js
  frontend/desktop/src/store/modules/project.js
  frontend/desktop/src/store/modules/task.js
  gcloud/contrib/admin/migration_api/staff_group.py
  gcloud/core/admin.py
  gcloud/core/apis/__init__.py
  gcloud/core/apis/drf/__init__.py
  gcloud/core/apis/drf/exceptions.py
  gcloud/core/apis/drf/serilaziers/__init__.py
  gcloud/core/apis/drf/serilaziers/project_config.py
  gcloud/core/apis/drf/serilaziers/resource_config.py
  gcloud/core/apis/drf/serilaziers/staff_group.py
  gcloud/core/apis/drf/validators.py
  gcloud/core/apis/drf/viewsets/__init__.py
  gcloud/core/apis/drf/viewsets/project_config.py
  gcloud/core/apis/drf/viewsets/resource_config.py
  gcloud/core/apis/drf/viewsets/staff_group.py
  gcloud/core/apis/drf/viewsets/utils.py
  gcloud/core/migrations/0020_auto_20200908_2030.py
  gcloud/core/models.py
  gcloud/resources/urls.py
  pipeline_plugins/cmdb_ip_picker/query.py
  pipeline_plugins/components/query/sites/open/cc.py
  pipeline_plugins/variables/collections/common.py
  pipeline_plugins/variables/query/sites/open/query.py
  pipeline_plugins/variables/static/variables/staff_group_multi_selector.js
  static/variables/staff_group_multi_selector.js
Labels: V3.6.X

#2851 improvement:任务节点样式优化
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/store/modules/template.js
Labels: V3.6.X_dev

#2852 minor: 升级版本号3.6.16
  app.yml
  config/default.py
  dev_log/3.6.16/Atropos1999_202010121041.yaml
  dev_log/3.6.16/fannluo_202009121830.yaml
  dev_log/3.6.16/fannluo_202010091605.yaml
  dev_log/3.6.16/fannluo_202010131034.yaml
  dev_log/3.6.16/fannluo_202010131039.yaml
  dev_log/3.6.16/fannluo_202010151958.yaml
  dev_log/3.6.16/normal-wls_202009092249.yaml
  dev_log/3.6.16/normal-wls_20200930.yaml
  dev_log/3.6.16/normal-wls_202010112143.yaml
  dev_log/3.6.16/normal-wls_202010112147.yaml
  dev_log/3.6.16/normal-wls_202010161700.yaml
  dev_log/3.6.16/normal-wls_202010161812.yaml
  dev_log/3.6.16/v_xugzhou_202009181447.yaml
  dev_log/3.6.16/v_xugzhou_202009211409.yaml
  dev_log/3.6.16/v_xugzhou_202010140917.yaml
  dev_log/3.6.16/v_xugzhou_202010140942.yaml
  dev_log/3.6.16/v_xugzhou_202010141957.yaml
  docs/release.md
  pipeline_plugins/components/collections/sites/open/bk/approve/v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/bk_test/approve/test_v1_0.py
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.6.16_2020-10-16.md
Labels: V3.6.X

#2857 bugfix: 3.6.16测试版本前端问题修复
  dev_log/dev/fannluo_202010191527.yaml
  frontend/desktop/src/App.vue
  frontend/desktop/src/components/layout/permissionApply.vue
  frontend/desktop/src/pages/home/AddCollectionDialog.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.6.X

#2859 bugfix: 修复 返回值为对象类型的变量直接引用结果优化 未生效问题
  dev_log/dev/normal-wls_202010191600.yaml
  pipeline/core/data/expression.py
Labels: V3.6.X

#2856 bugfix:修改CMDB插件-按规则修改主机自定义属性 无法使用问题 主机没有SetID属性的报错
  dev_log/dev/Atropos1999_202010171659.yaml
  pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/v1_0.py
  pipeline_plugins/components/utils/sites/open/utils.py
  pipeline_plugins/tests/components/collections/sites/open/cc_test/host_custom_property_change/test_v1_0.py
Labels: 2.bug, V3.6.X_dev

#2860 bugfix: bk-审核 请求参数格式修改
  dev_log/dev/v_feifzhao_202010191645.yaml
  pipeline_plugins/components/collections/sites/open/bk/approve/v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/bk_test/approve/test_v1_0.py
Labels: V3.6.X

#2861 集群资源筛选变量筛选ip数量不正确修复；分支条件tooltip文案优化
  dev_log/dev/fannluo_202010191527.yaml
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
Labels: V3.6.X

#2871 bugfix: 修复主机加解锁插件sdk接口方法不存在问题
  dev_log/dev/normal-wls_202010211200.yaml
  packages/blueking/component/apis/cc.py
Labels: V3.6.X

#2865 minor:前端表单增加验证，增加插件的详细描述
  pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/v1_0.py
  pipeline_plugins/components/static/components/atoms/cc/host_custom_property_change/v1_0.js
  static/components/atoms/cc/host_custom_property_change/v1_0.js
Labels: V3.6.X_dev

#2882 minor: 修改前端表单为int时，删除默认值跳过校验的问题
  pipeline_plugins/components/static/components/atoms/cc/host_custom_property_change/v1_0.js
  static/components/atoms/cc/host_custom_property_change/v1_0.js
Labels: 2.bug, V3.6.X_dev

#2892 minor: v3.6.18版本日志添加cmdb版本依赖
  docs/release.md
  version_log/version_logs_md/V3.6.18_2020-10-21.md
Labels: V3.6.X

#2887 optimization: 优化 DB 中存在内存中没有的插件时的处理逻辑
  gcloud/core/resources.py
Labels: V3.6.X

#2894 improvement: CC 工具函数传参优化
  gcloud/tests/utils/cmdb/test_business_host_topo.py
  gcloud/tests/utils/cmdb/test_get_business_host.py
  gcloud/utils/cmdb.py
Labels: V3.6.X

#2895 improvement:首页增加全部项目入口
  dev_log/dev/fannluo_202010231429.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/home/CommonlyUsed.vue
Labels: V3.6.X_dev

#2866 improvement:去掉节点输出参数勾选后节点设为不可选并禁用的逻辑
  dev_log/dev/fannluo_202010211008.yaml
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: V3.6.X_dev

#2867 feature: 流程模板、任务列表表格增加创建时间列
  dev_log/dev/fannluo_202010210959.yaml
  frontend/desktop/src/pages/admin/manage/AdminSearch/SearchResult.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
Labels: V3.6.X_dev

#2879 improvment: 节点参数编辑面板和变量编辑面板支持点击遮罩确认是否保存;标准插件说明样式调整
  dev_log/dev/fannluo0504_20201022.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
Labels: V3.6.X_dev

#2890 improvement:资源筛选变量输出支持配置分隔符
  dev_log/dev/fannluo_202010222035.yaml
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/components/common/RenderForm/SeparetorSelect.vue
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceList.vue
  frontend/desktop/src/components/common/RenderForm/SetAllocation/index.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagSetAllocation.vue
  frontend/desktop/src/utils/atomFilter.js
Labels: V3.6.X_dev

#2845 根据模板创建集群插件修改为可创建多个集群
  dev_log/dev/rykerli_202010241233.yaml
  pipeline_plugins/components/collections/sites/open/cc/create_set_by_template/v1_0.py
  pipeline_plugins/components/collections/sites/open/docs/cc/images/cc_create_set_by_template_manual.png
  pipeline_plugins/components/collections/sites/open/docs/cc/images/cc_create_set_by_template_tupo.png
  pipeline_plugins/components/static/components/atoms/cc/create_set_by_template/v1_0.js
  pipeline_plugins/tests/components/collections/sites/open/cc_test/cc_create_set_by_template/test_v1_0.py
  static/components/atoms/cc/create_set_by_template/v1_0.js
Labels: V3.6.X_dev

#2902 bugfix:下拉框tag设置为多选勾选为变量后，表单值不显示变量key修复
  dev_log/dev/fannluo_202010261730.yaml
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
Labels: V3.6.X

#2903 bugfix: 修复 项目管理页面无法进行搜索 问题
  dev_log/dev/normal-wls_202010261725.yaml
  gcloud/core/resources.py
Labels: V3.6.X

#2908 bugfix: 修复 故障机替换 插件 bk_host_innerip KeyError 问题，增加是否复制故障机属性选项
  dev_log/dev/normal-wls_2020102262210.yaml
  pipeline_plugins/components/collections/sites/open/cc/replace_fault_machine/legacy.py
  pipeline_plugins/components/static/components/atoms/cc/cc_replace_fault_machine.js
  static/components/atoms/cc/cc_replace_fault_machine.js
Labels: V3.6.X

#2905 improvement:输入参数勾选为全局变量复用逻辑调整
  dev_log/dev/fannluo_202010262035.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/ReuseVarDialog.vue
Labels: V3.6.X

#2901 bugfix:集群资源筛选变量主机数量手动输入数字不生效问题修复
  dev_log/dev/fannluo_202010261613.yaml
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
  frontend/desktop/src/components/common/RenderForm/SetAllocation/index.vue
Labels: V3.6.X

#2910 minor: 3.6.19 begin
  app.yml
  config/default.py
  dev_log/3.6.19/fannluo_202010261613.yaml
  dev_log/3.6.19/fannluo_202010261730.yaml
  dev_log/3.6.19/fannluo_202010262035.yaml
  dev_log/3.6.19/normal-wls_2020102262210.yaml
  dev_log/3.6.19/normal-wls_202010261725.yaml
  docs/release.md
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.6.19_2020-10-27.md
Labels: V3.6.X

#2914 improve: 优化 get_template_list 接口，可按照名称关键字筛选模版
  dev_log/dev/normal-wls_202010281140.yaml
  docs/apidoc/en/get_template_list.md
  docs/apidoc/zh_hans/get_template_list.md
  gcloud/apigw/views/get_template_list.py
  pipeline/migrations/0026_auto_20201028_1049.py
  pipeline/models.py
Labels: V3.6.X_dev

#2916 improve: 节点异常数据处理增加关键词屏蔽
  dev_log/dev/normal-wls_2020102281452.yaml
  gcloud/utils/handlers.py
Labels: V3.6.X

#2899 feature:完成插件 CMDB-批量修改主机自定义属性
  pipeline_plugins/components/collections/sites/open/cc/batch_update_host/__init__.py
  pipeline_plugins/components/collections/sites/open/cc/batch_update_host/v1_0.py
  pipeline_plugins/components/collections/sites/open/docs/cc/batch_update_host/v1_0.md
  pipeline_plugins/components/collections/sites/open/docs/cc/images/batch_update_host_auto.png
  pipeline_plugins/components/collections/sites/open/docs/cc/images/batch_update_host_manul.png
  pipeline_plugins/components/query/sites/open/cc.py
  pipeline_plugins/components/static/components/atoms/cc/batch_update_host/v1_0.js
  pipeline_plugins/tests/components/collections/sites/open/cc_test/batch_update_host/__init__.py
  pipeline_plugins/tests/components/collections/sites/open/cc_test/batch_update_host/test_v1_0.py
  static/components/atoms/cc/batch_update_host/v1_0.js
Labels: V3.6.X_dev

#2858 optimization: 后台允许用户取消勾选带有输出参数的节点
  .gitignore
  gcloud/taskflow3/models.py
  gcloud/tests/taskflow3/models/test_taskflow_preview_pipeline_tree_exclude_task_nodes.py
  pipeline_web/parser/format.py
  pipeline_web/tests/parser/format/__init__.py
  pipeline_web/tests/parser/format/test_classify_constants.py
Labels: V3.6.X_dev

#2915 feature: 增加企业微信(WechatWork)-发送消息插件
  dev_log/3.6.20/homholueng_202010281504.yaml
  docs/features/plugin_usage.md
  pipeline_plugins/components/collections/sites/open/wechat_work/__init__.py
  pipeline_plugins/components/collections/sites/open/wechat_work/wechat_work_send_message/__init__.py
  pipeline_plugins/components/collections/sites/open/wechat_work/wechat_work_send_message/v1_0.py
  pipeline_plugins/components/static/components/atoms/wechat_work/wechat_work_send_message/v1_0.js
  pipeline_plugins/tests/components/collections/sites/open/wechat_work_test/__init__.py
  pipeline_plugins/tests/components/collections/sites/open/wechat_work_test/wechat_work_send_message/__init__.py
  pipeline_plugins/tests/components/collections/sites/open/wechat_work_test/wechat_work_send_message/test_wechat_work_send_message_v1.py
  static/components/atoms/wechat_work/wechat_work_send_message/v1_0.js
Labels: V3.6.X

#2898 feature: 新增 标准运维插件 execute_pre_process 数据预处理和校验函数钩子
  dev_log/dev/normal-wls_202010232100.yaml
  docs/develop/dev_plugins.md
  pipeline/core/flow/activity/service_activity.py
  pipeline/engine/core/handlers/service_activity.py
  pipeline/tests/mock.py
Labels: V3.6.X_dev

#2875 improve: 集群资源筛选变量支持生成每个主机到对应模块的映射关系
  dev_log/dev/normal-wls_202010211730.yaml
  dev_log/dev/normal-wls_202010212130.yaml
  pipeline_plugins/variables/collections/sites/open/cc.py
Labels: V3.6.X_dev

#2855 feature: iam sdk 新增基于drf的支持
  dev_log/dev/normal-wls_202010091414.yaml
  iam/contrib/drf/__init__.py
  iam/contrib/drf/permission.py
  iam/contrib/drf/resource.py
Labels: V3.6.X_dev

#2924 minor：get_task_list 接口实现更新
  docs/apidoc/sops.yaml
  gcloud/apigw/views/claim_functionalization_task.py
  gcloud/apigw/views/get_task_list.py
  gcloud/iam_auth/view_interceptors/apigw/claim_functionalization_task.py
Labels: V3.6.X_dev

#2911 feature: 添加 get_tasks_manual_intervention_state API
  dev_log/3.6.20/homholueng_202010271732.yaml
  docs/apidoc/en/get_tasks_manual_intervention_state.md
  docs/apidoc/sops.yaml
  docs/apidoc/zh_hans/get_tasks_manual_intervention_state.md
  gcloud/apigw/urls.py
  gcloud/apigw/views/get_tasks_manual_intervention_state.py
  gcloud/taskflow3/models.py
  gcloud/tests/mock_settings.py
  gcloud/tests/taskflow3/models/taskflow/__init__.py
  gcloud/tests/taskflow3/models/taskflow/test_callback.py
  gcloud/tests/taskflow3/models/taskflow/test_is_manual_intervention_required.py
  gcloud/tests/taskflow3/models/taskflow/test_preview_pipeline_tree_exclude_task_nodes.py
Labels: V3.6.X_dev

#2928 minor: 集群资源筛选添加单元测试
  pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_set_allocation.py
  pipeline_plugins/variables/collections/sites/open/cc.py
Labels: V3.6.X_dev

#2929 minor: 修改healthz接口路径/增加豁免登陆
  gcloud/core/api.py
  gcloud/core/urls.py
Labels: V3.6.X
