Repository TencentBlueKing/bk-sops, pull requests merged in 2020-09, with the labels that each got.

#2594 feature: fast_create_task API 支持引用子流程（3.6.x_dev）
  dev_log/dev/normal-wls_202008281132.yaml
  dev_log/dev/normal-wls_202009081938.yaml
  docs/apidoc/en/fast_create_task.md
  docs/apidoc/zh_hans/fast_create_task.md
  gcloud/apigw/validators/fast_create_task.py
  gcloud/apigw/views/fast_create_task.py
  gcloud/iam_auth/view_interceptors/apigw/fast_create_task.py
  iam/contrib/tastypie/shortcuts.py
Labels: 4.pending

#2720 optimization: 优化子流程参数传递逻辑（V3.6.X）
  dev_log/dev/homholueng_202009121734.yaml
  pipeline/parser/pipeline_parser.py
  pipeline_web/parser/format.py
Labels: V3.6.X

#2734 improvement:兼容应用部署到跨域环境下的小窗登录(V3.6.X)
  dev_log/dev/fannluo_202009151034.yaml
  frontend/desktop/src/api/index.js
  frontend/desktop/src/config/login.js
Labels: V3.6.X

#2741 bugfix: 修复子流程传参逻辑优化引入的 Lazy 类型变量传递失败的问题
  pipeline_web/parser/format.py
Labels: V3.6.X

#2743 feature: 支持本地配置用于访问权限中心的 app_code 及 app_secret
  gcloud/iam_auth/shortcuts.py
Labels: V3.6.X

#2744 fixbug: 修复节日详情页日志一直loading问题
  dev_log/dev/v_xugzhou_202009161556.yaml
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: V3.6.X

#2742 bugfix: 修复查看参数按钮查看子流程节点参数时报错的问题(V3.6.X)
  dev_log/dev/v_xugzhou_202009160950.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: V3.6.X

#2749 minor: 版本号升级到 V3.6.12
  app.yml
  config/default.py
  dev_log/3.6.12/fannluo_202009141043.yaml
  dev_log/3.6.12/fannluo_202009141155.yaml
  dev_log/3.6.12/fannluo_202009151034.yaml
  dev_log/3.6.12/fannluo_202009151120.yaml
  dev_log/3.6.12/homholueng_202009121734.yaml
  dev_log/3.6.12/v_xugzhou_202009160950.yaml
  dev_log/3.6.12/v_xugzhou_202009161556.yaml
  docs/release.md
  readme.md
  readme_en.md
  scripts/start_new_version.sh
  version_log/version_logs_md/V3.6.12_2020-09-16.md
Labels: V3.6.X

#2718 feature：主机筛选变量开发（V3.6.X_iterate)
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/HostAllocation/HostFilter.vue
  frontend/desktop/src/components/common/RenderForm/HostAllocation/index.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagHostAllocation.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/main.js
  frontend/desktop/src/store/modules/task.js
Labels: V3.6.X_dev

#2750 improve: 添加celery心跳设置
  config/default.py
Labels: V3.6.X_dev

#2748 feature: taskflow/api/v4/node_action 接口支持进行强制失败操作
  gcloud/iam_auth/view_interceptors/taskflow.py
  gcloud/taskflow3/apis/__init__.py
  gcloud/taskflow3/apis/views/__init__.py
  gcloud/taskflow3/apis/views/v4/__init__.py
  gcloud/taskflow3/apis/views/v4/node_action.py
  gcloud/taskflow3/apis/views/v4/urls.py
  gcloud/taskflow3/models.py
  gcloud/taskflow3/urls.py
  gcloud/taskflow3/validators.py
Labels: V3.6.X_dev

#2758 bugfix:变量引用次数统计正则回溯问题修复(V3.6.X)
  dev_log/dev/fannluo_202009172121.yaml
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
Labels: V3.6.X

#2761 bugfix:下拉框变量无法编辑问题修复
  dev_log/dev/fannluo_202009180007.yaml
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/store/modules/atomForm.js
Labels: V3.6.X

#2733 minor: 权限申请链接获取失败时去申请按钮置灰(V3.6.X)
  dev_log/dev/v_xugzhou_202009141844.yaml
  frontend/desktop/src/components/common/modal/PermissionModal.vue
Labels: V3.6.X_dev

#2732 improve: 导入流程弹框对 创建新流程按钮做权限管理(V3.6.X)
  dev_log/dev/v_xugazhou_202009141500.yaml
  frontend/desktop/src/pages/template/TemplateList/ImportTemplateDialog.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
Labels: V3.6.X_dev

#2730 improve：导入流程按钮文案优化（V3.6.X)
  dev_log/dev/v_xugzhou_202009141130.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/ImportTemplateDialog.vue
Labels: V3.6.X_dev

#2731 improve: 变量key 支持长度增加到50(V3.6.X)
  dev_log/dev/v_xugzhou_202009141525.yaml
  frontend/desktop/src/constants/index.js
Labels: V3.6.X_dev

#2781 improve： 添加公共流程导入权限判断(V3.6.X_dev)
  dev_log/dev/v_xugzhou_202009211554.yaml
  frontend/desktop/src/pages/template/TemplateList/ImportTemplateDialog.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
Labels: V3.6.X_dev

#2780 fixbug: 修复超出画布区域节点未显示问题(V3.6.X_dev)
  dev_log/dev/v_xugzhou_202009221004.yaml
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/utils/domToImage.js
Labels: V3.6.X_dev

#2784 sprintfix: 筛选ip数据为空问题修复
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
Labels: V3.6.X_dev

#2787 sync 3.6.X bugfix to 3.5.X
  dev_log/dev/fannluo_202009172121.yaml
  dev_log/dev/fannluo_202009180007.yaml
  dev_log/dev/fannluo_202009181044.yaml
  dev_log/dev/fannluo_202009221635.yaml
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/main.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/ReuseVarDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
  frontend/desktop/src/store/modules/atomForm.js
Labels: V3.5.X_dev

#2786 bugfix: 任务节点执行失败后重试、跳过操作按钮绑定错误修复
  dev_log/dev/fannluo_202009221635.yaml
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
Labels: V3.6.X

#2765 bugfix: 变量KEY长度扩展及匹配规则修复
  dev_log/dev/fannluo_202009181044.yaml
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/main.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/ReuseVarDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: V3.6.X

#2762 bugfix:流程模板导出全选时权限判断错误修复
  dev_log/dev/fannluo_202009180015.yaml
  frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
Labels: V3.6.X

#2760 3.5.x to merge
  dev_log/dev/fannluo_202009141043.yaml
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
Labels: V3.5.X

#2785 improvement: 画布快捷键说明样式调整，增加复制、粘贴说明
  dev_log/dev/fannluo_202009221636.yaml
  frontend/desktop/src/components/common/TemplateCanvas/HelpInfo/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
Labels: V3.6.X_dev

#2721 feature: 新增项目授权管理页面
  dev_log/dev/fannluo_202009121830.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/project/mandate.vue
  frontend/desktop/src/store/modules/project.js
Labels: V3.6.X_dev

#2710 improve: 后台添加基于用户权限的项目列表拉取接口
  gcloud/core/resources.py
  gcloud/resources/urls.py
Labels: V3.6.X_dev

#2766 feature:集群模块ip选择器
  packages/blueking/component/apis/cc.py
  pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_set_module_ip_selector.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
  pipeline_plugins/variables/collections/sites/open/docs/cmdb/images/set_module_ip_selector_ip.png
  pipeline_plugins/variables/collections/sites/open/docs/cmdb/images/set_module_ip_selector_manual.png
  pipeline_plugins/variables/collections/sites/open/docs/cmdb/images/set_module_ip_selector_select.png
  pipeline_plugins/variables/collections/sites/open/docs/cmdb/var_set_module_ip_selector.md
  pipeline_plugins/variables/query/sites/open/query.py
  pipeline_plugins/variables/static/variables/cmdb/var_set_module_ip_selector.js
  pipeline_plugins/variables/utils.py
  static/variables/cmdb/var_set_module_ip_selector.js
Labels: V3.6.X_dev

#2789 feature:job获取文件内容公共函数
  pipeline_plugins/components/utils/job.py
Labels: V3.6.X_dev

#2796 minor:修改job获取远程服务器文件失败ip错误提示
  pipeline_plugins/components/utils/job.py
Labels: V3.6.X_dev

#2774 improvement: JOB 回调默认链接使用 PAAS_INNER_HOST 拼接
  dev_log/dev/normal-wls_202009211542.yaml
  pipeline_plugins/components/utils/sites/open/utils.py
  pipeline_plugins/tests/utils/sites/open/test_utils.py
Labels: V3.6.X

#2794 minor: TaskResourceProvider page limit增加为1000
  gcloud/iam_auth/resource_api/task.py
Labels: V3.6.X

#2791 feature: 增加查询对象全部属性的接口
  pipeline_plugins/components/query/sites/open/cc.py
Labels: V3.6.X_dev

#2764 feature: 完成全局变量 集群分组选择器（3.6.X）
  packages/blueking/component/apis/cc.py
  pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_set_group_selector.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_set_group_selector.py
  pipeline_plugins/variables/collections/sites/open/docs/cmdb/images/var_set_group_selector.png
  pipeline_plugins/variables/collections/sites/open/docs/cmdb/var_set_group_selector.md
  pipeline_plugins/variables/query/sites/open/query.py
  pipeline_plugins/variables/static/variables/cmdb/var_set_group_selector.js
  static/variables/cmdb/var_set_group_selector.js
Labels: V3.6.X_dev

#2803 feature: 增加查询对象全部属性的接口(3.5.x)
  pipeline_plugins/components/query/sites/open/cc.py
Labels: V3.5.X_dev

#2801 improve：节点日志信息敏感信息屏蔽
  config/default.py
  dev_log/dev/normal-wls_202009151122.yaml
  gcloud/contrib/admin/views/taskflow.py
  gcloud/taskflow3/models.py
  gcloud/utils/handlers.py
Labels: V3.6.X

#2805 bugfix:公共流程创建的任务再创建时单独查询权限
  dev_log/dev/fannluo_202009242025.yaml
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: V3.6.X

#2806 minor: 任务列表页公共流程创建的任务再创建权限由接口返回
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: V3.6.X

#2804 bugfix：公共流程模版创建任务无法再创建问题修复
  dev_log/dev/normal-wls_202009241943.yaml
  gcloud/taskflow3/resources.py
Labels: V3.6.X

#2809 minor: 升级版本号到3.6.13
  app.yml
  config/default.py
  dev_log/3.6.13/fannluo_202009172121.yaml
  dev_log/3.6.13/fannluo_202009180007.yaml
  dev_log/3.6.13/fannluo_202009180015.yaml
  dev_log/3.6.13/fannluo_202009181044.yaml
  dev_log/3.6.13/fannluo_202009221635.yaml
  dev_log/3.6.13/fannluo_202009242025.yaml
  dev_log/3.6.13/fannluo_202009251143.yaml
  dev_log/3.6.13/normal-wls_202009151122.yaml
  dev_log/3.6.13/normal-wls_202009211542.yaml
  dev_log/3.6.13/normal-wls_202009241943.yaml
  docs/release.md
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.6.13_2020-09-25.md
Labels: V3.6.X

#2810 feature: 新建关联支持属性授权，应用于任务新建关联
  dev_log/dev/normal-wls_202009252110.yaml
  gcloud/iam_auth/resource_api/task.py
  gcloud/iam_auth/resource_creator_action/task.py
  gcloud/iam_auth/resource_creator_action/utils.py
  iam/api/client.py
  iam/iam.py
Labels: V3.6.X_dev

#2747 improve: 返回值为对象类型的变量直接引用场景下的结果优化
  dev_log/dev/normal-wls_202009161614.yaml
  pipeline/core/data/expression.py
  pipeline_plugins/variables/collections/datatable.py
  pipeline_plugins/variables/collections/sites/open/cc.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_set_module_selector.py
Labels: V3.6.X_dev

#2792 improve： 导入流程非法时展示提示信息（V3.6.X_dev)
  dev_log/dev/v_xugzhou_202009211632.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/ImportTemplateDialog.vue
Labels: V3.6.X_dev

#2763 improve: 执行方案允许叠加多个执行方案(V3.6.X_dev）
  dev_log/dev/v_xugzhou_202009180910.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: V3.6.X_dev

#2790 improve: 任务执行页面支持展示pipeline_tree(V3.6.X_dev)
  dev_log/dev/v_xugzhou_202009071810.yaml
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  frontend/desktop/src/pages/task/TaskExecute/TemplateData.vue
  frontend/desktop/src/scss/iconfont.scss
Labels: V3.6.X_dev

#2772 improve: 节点操作面板改版，节点添加强制失败操作功能(V3.6.X_dev)
  dev_log/dev/v_xugzhou_202009211219.yaml
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/scss/iconfont.scss
  frontend/desktop/src/store/modules/task.js
Labels: V3.6.X_dev

#2773 bugFix: 查看任务详情时单击并行网关节点展示问题(V3.6.X_dev)
  dev_log/dev/v_xugzhou_202009211503.yaml
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: V3.6.X_dev

#2813 feature: 新增支持格式自定义的当前系统时间变量
  dev_log/dev/normal-wls_202009271643.yaml
  pipeline_plugins/tests/variables/collections/test_format_support_current_time.py
  pipeline_plugins/variables/collections/common.py
  pipeline_plugins/variables/static/variables/format_support_current_time.js
Labels: V3.6.X_dev

#2713 improvement:全量项目列表接口替换为用户有权限列表接口
  frontend/desktop/src/components/common/modal/SelectProjectModal.vue
  frontend/desktop/src/components/layout/Navigator.vue
  frontend/desktop/src/components/layout/ProjectSelector.vue
  frontend/desktop/src/components/layout/permissionApply.vue
  frontend/desktop/src/pages/admin/statistics/index.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/home/AddCollectionDialog.vue
  frontend/desktop/src/pages/home/SelectCreateTaskDialog.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/store/modules/project.js
Labels: V3.6.X_dev

#2754 feature：增加全局变量 任务开始时间
  dev_log/3.6.12/Atropos1999_202009271935.yaml
  gcloud/taskflow3/context.py
Labels: V3.6.X_dev

#2755 minor:新增bk-审核插件（3.6.X_dev）
  dev_log/3.6.12/v_feifzhao_2020091715114.yaml
  packages/blueking/component/apis/itsm.py
  packages/blueking/component/collections.py
  pipeline_plugins/components/collections/sites/open/bk/approve/__init__.py
  pipeline_plugins/components/collections/sites/open/bk/approve/v1_0.py
  pipeline_plugins/components/static/components/atoms/bk/approve/v1_0.js
  pipeline_plugins/tests/components/collections/sites/open/bk_test/approve/__init__.py
  pipeline_plugins/tests/components/collections/sites/open/bk_test/approve/test_v1_0.py
  static/components/atoms/bk/approve/v1_0.js
Labels: V3.6.X_dev

#2739 optimization: 导出模板数据增加模板来源（项目模板、公共模板）数据和版本数据，模板导入时提前检测模板来源
  dev_log/dev/homholueng_202009151626.yaml
  gcloud/commons/template/models.py
  gcloud/commons/template/validators.py
  gcloud/constants.py
  gcloud/tasktmpl3/models.py
  gcloud/tasktmpl3/validators.py
Labels: V3.6.X_dev

#2753 feature：完成插件 CMDB-按规则修改主机属性
  dev_log/3.6.12/Atropos1999_202009271941.yaml
  packages/blueking/component/apis/cc.py
  pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/__init__.py
  pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/v1_0.py
  pipeline_plugins/components/collections/sites/open/docs/cc/host_custom_property_change/v1_0.md
  pipeline_plugins/components/collections/sites/open/docs/cc/images/host_custom_property_v1_0.png
  pipeline_plugins/components/static/components/atoms/cc/host_custom_property_change/v1_0.js
  pipeline_plugins/tests/components/collections/sites/open/cc_test/host_custom_property_change/__init__.py
  pipeline_plugins/tests/components/collections/sites/open/cc_test/host_custom_property_change/test_v1_0.py
  static/components/atoms/cc/host_custom_property_change/v1_0.js
Labels: V3.6.X_dev

#2800 前端打包方式优化
  frontend/desktop/builds/mock/config/index.js
  frontend/desktop/builds/webpack.base.js
  frontend/desktop/builds/webpack.dev.config.js
  frontend/desktop/builds/webpack.prod.config.js
  frontend/desktop/src/assets/html/index-dev.html
  frontend/desktop/src/assets/html/index.html
  frontend/desktop/src/main.js
  frontend/desktop/src/public-path.js
  gcloud/core/context_processors.py
Labels: V3.6.X_dev
