Repository TencentBlueKing/bk-sops, pull requests merged in 2021-02, with the labels that each got.

#3299 minor: SKIP_IAM情况下跳过iam相关migrate过程
  iam/contrib/iam_migration/migrator.py
Labels: V3.6.X

#3300 minor: http 请求插件默认超时时间改为 5s
  pipeline_plugins/components/static/components/atoms/bk/http/v1_0.js
  static/components/atoms/bk/http/v1_0.js
Labels: V3.6.X_dev, optimization

#3303 bugfix:修复IP选择器添加静态ip时搜索结果翻页显示不正确问题
  dev_log/dev/fannluo_20210204.yaml
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
Labels: V3.6.X, bug

#3266 feature: 后台解析流程树时支持读取用户配置的变量预渲染选项
  pipeline_web/parser/format.py
  pipeline_web/tests/parser/format/test_format_web_data_to_pipeline.py
Labels: V3.6.X_dev, feature

#3322 improve: 轻应用创建页面执行方案处增加提示
  dev_log/dev/v_xugzhou_202102191435.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
Labels: V3.6.X_dev

#3297 bugfix:修复IP选择器添加静态ip时搜索结果翻页显示不正确问题
  dev_log/dev/fannluo_20210204.yaml
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
Labels: V3.5.X, bug

#3325 minor: 修复cc_get_host_by_module_id传参中存在字符串报错问题
  pipeline_plugins/base/query/cmdb.py
Labels: V3.6.X_dev, bug

#3292 improvmement: 标签样式采用新设计
  dev_log/dev/v_xugzhou_202102031605.yaml
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
Labels: V3.6.X_dev

#3317 修复用户不从入口 URL 进入页面时没有向 IAM 注册创建者新建关联的问题
  dev_log/dev/homholueng_202102221034.yaml
  gcloud/core/views.py
Labels: V3.6.X_dev, bug

#3331 bugfix:修复导航右上角可选项目条数不正确问题
  dev_log/dev/fannluo_202102241702.yaml
  frontend/desktop/src/pages/admin/statistics/index.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/store/modules/project.js
Labels: V3.6.X, bug

#3337 minor: 节点管理插件操作前端优化
  static/components/atoms/nodeman/plugin_operate/v1_0.js
Labels: optimization

#3341 minor: job文本上传输出描述优化
  pipeline_plugins/components/collections/sites/open/job/base.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v2_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/push_local_files/test_v2_0.py
Labels: optimization
