Repository TencentBlueKing/bk-sops, pull requests merged in 2021-09, with the labels that each got.

#3965 improvement : 【优化】作业平台(JOB)-分发本地文件 2.0 版本添加文件后不要清空目标路径
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
  static/components/atoms/job/job_push_local_files/v2_0.js
Labels: type/optimization

#3981 bugfix: 导入临时方案问题修复
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
Labels: type/bug, version/V3.6.X

#3973 bugfix: 修复v2引擎节点未执行时数据预览出错问题
  dev_log/dev/waylon_202108301734.yaml
  gcloud/taskflow3/apis/django/api.py
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/taskflow3/models.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py
  gcloud/tests/taskflow3/models/taskflow/test_get_node_detail.py
Labels: version/V3.6.X

#3980 Feature: Plugin Service Merge bigsur
  config/default.py
  config/urls_custom.py
  docs/release.md
  frontend/desktop/builds/webpack.dev.config.js
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeItem.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/atomForm.js
  gcloud/core/resources.py
  pipeline_plugins/components/collections/sites/open/job/base.py
  plugin_service/__init__.py
  plugin_service/admin.py
  plugin_service/api.py
  plugin_service/apps.py
  plugin_service/conf.py
  plugin_service/decorators.py
  plugin_service/env.py
  plugin_service/exceptions.py
  plugin_service/plugin.py
  plugin_service/plugin_client.py
  plugin_service/serializers.py
  plugin_service/tests/test_plugin.py
  plugin_service/urls.py
Labels: version/V3.6.X

#3975 improvement: 从ip_str中匹配IP信息在纯IP格式和云区域ID:IP格式下支持host_innerip为多ip情况
  dev_log/dev/waylon_202108311001.yaml
  pipeline_plugins/components/utils/sites/open/utils.py
  pipeline_plugins/tests/components/utils/test_cc_get_ips_info_by_str.py
Labels: version/V3.6.X

#3979 bugfix: bigsur测试问题修复
  dev_log/dev/waylon_202108311927.yaml
  dev_log/dev/waylon_202108311928.yaml
  dev_log/dev/waylon_202108311930.yaml
  gcloud/contrib/appmaker/models.py
  gcloud/core/api_adapter/sites/open/app_maker.py
  gcloud/taskflow3/apis/tastypie/resources.py
Labels: version/V3.6.X

#3978 minor: 审核插件审核结果字段不再进行国际化
  pipeline_plugins/components/collections/sites/open/bk/approve/v1_0.py
Labels: type/optimization

#3987 improvement: 注册所有常用操作到IAM
  bksops_iam_migrations/migrations/0007_bk_sops_202109011700.py
  dev_log/dev/waylon_202109011719.yaml
  support-files/iam/07_add_common_actions.json
Labels: version/V3.6.X

#3989 bugfix: 修复查看详情切换到未执行节点时日志面板未刷新问题
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: type/bug

#4000 minor: preview_node_inputs接口调用调整
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py
  requirements.txt
Labels: version/V3.6.X

#3925 bugfix: 修复ProjectConfig和StaffGroup接口无权限中心校验问题
  dev_log/dev/waylon_202108242143.yaml
  gcloud/core/apis/drf/viewsets/project_config.py
  gcloud/core/apis/drf/viewsets/staff_group.py
  gcloud/core/apis/drf/viewsets/utils.py
Labels: version/V3.6.X

#4002 bugfix: 修复任务创建后立即查询状态接口报错问题
  dev_log/dev/waylon_202109031648.yaml
  gcloud/taskflow3/dispatchers/task.py
Labels: version/V3.6.X

#4003 3.7.1 begin
  dev_log/3.6.53/waylon_202109031648.yaml
  docs/release.md
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/utils/tplSnapshoot.js
  gcloud/taskflow3/domains/dispatchers/task.py
  pipeline_plugins/components/collections/sites/open/bk/notify/v1_0.py
  pipeline_plugins/components/static/components/atoms/bk/notify/v1_0.js
  pipeline_plugins/tests/components/collections/sites/open/bk_test/notify/test_v1_0.py
  static/components/atoms/bk/notify/v1_0.js
  version_log/version_logs_md/V3.6.51_2021-09-01.md
  version_log/version_logs_md/V3.6.52_2021-09-02.md
  version_log/version_logs_md/V3.6.53_2021-09-03.md
Labels: version/V3.6.X

#4020 bugfix: 首页-我的动态加载失败问题修复
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/home/MyDynamic.vue
Labels: type/bug

#4024 bugfix: 修复 RenderCurrentConstantsView 鉴权 500 的问题
  gcloud/taskflow3/apis/drf/viewsets/render_current_constants.py
Labels: type/bug

#4023 minor: 添加state接口查看任务树状态
  dev_log/dev/waylon_202109061748.yaml
  gcloud/apigw/views/get_task_status.py
  gcloud/apigw/views/get_tasks_status.py
  gcloud/iam_auth/view_interceptors/taskflow.py
  gcloud/taskflow3/api.py
  gcloud/taskflow3/apis/views/v4/state.py
  gcloud/taskflow3/apis/views/v4/urls.py
  gcloud/taskflow3/models.py
  gcloud/taskflow3/resources.py
  gcloud/tests/apigw/views/test_get_tasks_status.py
  gcloud/tests/mock.py
Labels: version/V3.6.X

#4025 bugfix: 修复 RenderCurrentConstantsView 500 的问题
  gcloud/taskflow3/apis/drf/viewsets/render_current_constants.py
Labels: type/bug

#4027 bugfix: 轻应用、任务、流程列表管理员用户项目权限检查豁免
  gcloud/contrib/appmaker/resources.py
  gcloud/iam_auth/utils.py
  gcloud/taskflow3/resources.py
  gcloud/tasktmpl3/resources.py
Labels: version/V3.6.X

#4026 minor: 任务列表查询单个任务状态接口替换
  frontend/desktop/src/mixins/task.js
  frontend/desktop/src/pages/admin/manage/AdminSearch/SearchResult.vue
  frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/store/modules/task.js
Labels: version/V3.6.X

#4028 bugfix: 轻应用、任务、流程列表管理员用户项目权限检查豁免
  gcloud/contrib/appmaker/resources.py
  gcloud/iam_auth/utils.py
  gcloud/taskflow3/apis/tastypie/resources.py
  gcloud/tasktmpl3/apis/tastypie/resources.py
Labels: version/V3.6.X

#4029 minor: V3.6.4209 begin
  app.yml
  config/default.py
  dev_log/3.6.4209/waylon_202109061748.yaml
  docs/release.md
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.6.4209_2021-09-07.md
Labels: version/V3.6.X

#4032 bugfix: 导入临时执行方案按钮去掉前端鉴权
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
Labels: type/bug

#4033 bugfix: 修复JOB全业务插件表格没有添加按钮问题
  dev_log/dev/waylon_202109081459.yaml
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_0.js
  static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
  static/components/atoms/job/all_biz_fast_push_file/v1_0.js
Labels: type/bug, version/V3.6.X

#3946 improvemnt: 导出流程面板样式优化
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
  frontend/desktop/src/pages/template/TemplateList/ImportDatTplDialog.vue
  frontend/desktop/src/pages/template/TemplateList/ImportYamlTplDialog.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
  frontend/desktop/src/store/modules/templateList.js
Labels: type/optimization

#4037 improvement: 第三方插件日志支持滚动加载
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/optimization

#4038 minor: 调整 celery 监控事件发送策略
  config/default.py
  env.py
  requirements.txt
Labels: type/optimization

#4039 minor: 兼容日志format关键字是fmt的情况
  config/default.py
Labels: version/V3.6.X

#4005 feature: DAT格式导出流程模板接口支持 is_full 参数
  gcloud/common_template/apis/django/api.py
  gcloud/tasktmpl3/apis/django/api.py
  gcloud/template_base/apis/django/api.py
  gcloud/template_base/apis/django/validators.py
Labels: type/feature

#4054 bugfix: bigsur前端回归问题修复
  frontend/desktop/src/components/common/RenderForm/IpSelector/ManualInput.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/SingleIpSelector.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
Labels: type/bug

#4052 bugfix: 非编辑态点击连线时不展示删除icon
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
Labels: type/bug, version/V3.6.X

#4053 minor: 流程标签创建操作添加权限校验
  gcloud/label/viewsets.py
Labels: type/bug

#4042 bugfix:V2引擎 创建含子流程任务失败
  pipeline_web/parser/format.py
Labels: type/bug

#4041 bugfix: 修复创建项目环境变量使用项目查看而不是项目编辑权限的问题
  gcloud/project_constants/apis/drf/permissions.py
Labels: type/bug

#4036 bugfix: 修复查看没有Data对象的节点时报错的问题
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py
Labels: type/bug

#4057 minor: 快速分发文件插件表格列宽度自适应
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v2_0.js
  static/components/atoms/job/fast_push_file/v1_0.js
  static/components/atoms/job/fast_push_file/v2_0.js
Labels: version/V3.6.X

#4058 bugfix: 修复同时对并行网关中的子流程进行暂停继续操作时流程卡住的问题
  dev_log/dev/homholueng_202109131618.yaml
  requirements.txt
Labels: type/bug

#4063 bugfix: 修复输出参数表单和输出参数表单key相同时勾选判断的问题
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
Labels: test_stage_bug

#4061 bugfix: 模板批量操作权限判断问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
Labels: test_stage_bug

#4069 bugfix: 非编辑态点击连线时不展示删除icon
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
Labels: test_stage_bug

#4017 improvement: 职能化中心支持对认领人进行过滤
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/functor/FunctionList.vue
Labels: type/feature

#4021 feature: crontab组件增加每个时间维度的清空按钮
  frontend/desktop/src/components/common/Individualization/loopRuleSelect.vue
Labels: type/feature

#4081 minor: 3.7.5 begin
  app.yml
  config/default.py
  dev_log/3.7.5/waylon_202109161905.yaml
  docs/release.md
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.7.5_2021-09-16.md
Labels: version/V3.6.X

#4083 bugfix: 修复任务创建参数填写页面相同类型的表单执行渲染出第一个的问题
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
Labels: type/bug, version/V3.6.X

#4085 minor: paas桌面打开其他应用逻辑放到项目内部处理
  static/core/js/paas_api.js
Labels: type/optimization, version/V3.6.X

#4087 minor: 3.7.6 begin
  app.yml
  config/default.py
  dev_log/3.7.6/waylon_202109171554.yaml
  docs/release.md
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.7.6_2021-09-17.md
Labels: version/V3.6.X

#4092 Bugfix create task with common flow auth
  dev_log/dev/homholueng_202109221005.yaml
  gcloud/iam_auth/view_interceptors/apigw/create_task.py
  requirements.txt
Labels: type/bug

#4102 minor: release 3.7.8
  app.yml
  config/default.py
  dev_log/3.7.8/homholueng_202109221947.yaml
  docs/release.md
  gcloud/apigw/views/get_task_node_detail.py
  gcloud/tests/apigw/views/test_get_task_node_detail.py
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.7.8_2021-09-22.md
Labels: type/bug

#4106 bugfix: 修复 operate_node API 不修改参数重试 engine v2 失败节点时节点数据会被清空的问题
  dev_log/dev/homholueng_202109231453.yaml
  gcloud/taskflow3/domains/dispatchers/node.py
Labels: type/bug

#4108 bugfix: 第三方插件问题修复
  frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#4119 improvement: 运营数据维度丰富
  frontend/desktop/package.json
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/pages/admin/statistics/Appmaker.vue
  frontend/desktop/src/pages/admin/statistics/Atom.vue
  frontend/desktop/src/pages/admin/statistics/HorizontalBarChart.vue
  frontend/desktop/src/pages/admin/statistics/Instance.vue
  frontend/desktop/src/pages/admin/statistics/Template.vue
  frontend/desktop/src/pages/admin/statistics/VerticalBarChart.vue
  frontend/desktop/src/store/modules/admin.js
Labels: type/feature

#4137 feature: 计划任务功能开发
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/constants/routes.js
  frontend/desktop/src/pages/task/ClockedList/DeleteClockedDialog.vue
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/ClockedList/index.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
  frontend/desktop/src/routers/index.js
  frontend/desktop/src/scss/iconfont.scss
  frontend/desktop/src/store/modules/clocked.js
  frontend/desktop/src/store/modules/index.js
Labels: type/feature

#4136 Bugfix get old loop history time missing
  dev_log/dev/homholueng_202109261446.yaml
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py
Labels: type/bug

#4131 bugfix: 修复 operate_task 能够操作未启动的任务的问题
  dev_log/dev/homholueng_202109241659.yaml
  gcloud/taskflow3/domains/dispatchers/task.py
Labels: type/bug

#3893 feature:create_task接口支持选择执行节点
  docs/apidoc/en/create_task.md
  docs/apidoc/zh_hans/create_task.md
  gcloud/apigw/schemas.py
  gcloud/apigw/views/create_task.py
  gcloud/tests/apigw/views/test_create_task.py
Labels: type/feature

#4062 improvement: 职能化中心新建任务项目选择过滤已归档业务
  frontend/desktop/src/pages/functor/FunctionList.vue
Labels: type/optimization

#3928 feature: 【功能】快速执行脚本生成任务名支持自定义
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_0.js
  pipeline_plugins/tests/components/collections/sites/open/job_test/fast_execute_task/test_legacy.py
Labels: type/feature

#4147 bugfix: 修复任务节点重试面板第二次点开时表单不显示的问题
  frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
Labels: type/bug

#4150 bugfix: 修复第三方插件plugin_code取值不正确问题
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#4124 feature: 动态适配锚点、支持移动连线锚点等画布优化
  frontend/desktop/src/assets/js/flow.js
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/store/modules/template.js
Labels: type/feature

#4149 feature:新增create_and_start_task接口，支持创建并执行任务
  dev_log/dev/yovafeng_202108251130.yaml
  docs/apidoc/en/create_and_start_task.md
  docs/apidoc/sops.yaml
  docs/apidoc/zh_hans/create_and_start_task.md
  gcloud/apigw/schemas.py
  gcloud/apigw/urls.py
  gcloud/apigw/views/create_and_start_task.py
  gcloud/tests/apigw/views/test_create_and_start_task.py
  gcloud/tests/mock_settings.py
Labels: type/feature

#3943 improvement: 职能化添加模板跳转按钮
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/optimization

#3912 bugfix: 修复ip选择器前端搜索切换状态刷新问题
  frontend/desktop/src/components/common/RenderForm/IpSelector/IpSearchInput.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
Labels: type/bug

#3971 bugfix: 子流程重试功能联调问题修复
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py
Labels: type/bug
