Repository TencentBlueKing/bk-sops, pull requests merged in 2021-04, with the labels that each got.

#3450 minor: 流程标签替换分类独立分支合入
  dev_log/dev/normal-wls_202103191804.yaml
  dev_log/dev/normal-wls_202103191809.yaml
  env.py
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/components/common/advanceSearchForm/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/home/AddCollectionDialog.vue
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
  frontend/desktop/src/pages/template/TemplateEdit/SettingTabs.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
  frontend/desktop/src/scss/common.scss
  frontend/desktop/src/store/modules/project.js
  frontend/desktop/src/store/modules/template.js
  gcloud/commons/tastypie/resources.py
  gcloud/commons/template/migrations/0008_auto_20210319_1756.py
  gcloud/commons/template/models.py
  gcloud/contrib/admin/migration_api/__init__.py
  gcloud/contrib/admin/migration_api/decorators.py
  gcloud/contrib/admin/migration_api/template_category.py
  gcloud/contrib/admin/urls.py
  gcloud/core/constant.py
  gcloud/label/models.py
  gcloud/label/viewsets.py
  gcloud/taskflow3/migrations/0014_auto_20210319_1757.py
  gcloud/taskflow3/models.py
  gcloud/taskflow3/resources.py
  gcloud/tasktmpl3/migrations/0018_auto_20210319_1752.py
  gcloud/tasktmpl3/resources.py
  iam/contrib/drf/shortcuts.py
  packages/blueking/component/shortcuts.py
Labels: V3.6.X_dev

#3288 minor: 转移主机到默认模块优化
  dev_log/dev/v_feifzhao_202103251610.yaml
  pipeline_plugins/components/collections/sites/open/cc/base.py
  pipeline_plugins/components/collections/sites/open/cc/transfer_fault_host/legacy.py
  pipeline_plugins/components/collections/sites/open/cc/transfer_host_module/legacy.py
  pipeline_plugins/components/collections/sites/open/cc/transfer_host_module/v1_0.py
  pipeline_plugins/components/collections/sites/open/cc/transfer_host_resource/legacy.py
  pipeline_plugins/components/collections/sites/open/cc/transfer_to_idle/legacy.py
  pipeline_plugins/components/collections/sites/open/cc/transfer_to_recovery/v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/cc_test/transfer_fault_host/test_legacy.py
  pipeline_plugins/tests/components/collections/sites/open/cc_test/transfer_host_resource/test_legacy.py
Labels: optimization

#3452 improvement:将最大请求体限制改为25MB
  config/default.py
  dev_log/dev/normal-wls_202104021555.yaml
Labels: V3.5.X

#3453 minor: 模版标签替换分类相关功能合入
  dev_log/dev/normal-wls_202103191804.yaml
  dev_log/dev/normal-wls_202103191809.yaml
  env.py
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/components/common/advanceSearchForm/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/home/AddCollectionDialog.vue
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
  frontend/desktop/src/pages/template/TemplateEdit/SettingTabs.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
  frontend/desktop/src/scss/common.scss
  frontend/desktop/src/store/modules/project.js
  frontend/desktop/src/store/modules/template.js
  gcloud/commons/tastypie/resources.py
  gcloud/commons/template/migrations/0008_auto_20210319_1756.py
  gcloud/commons/template/models.py
  gcloud/contrib/admin/migration_api/__init__.py
  gcloud/contrib/admin/migration_api/decorators.py
  gcloud/contrib/admin/migration_api/template_category.py
  gcloud/contrib/admin/urls.py
  gcloud/core/constant.py
  gcloud/label/models.py
  gcloud/label/viewsets.py
  gcloud/taskflow3/migrations/0014_auto_20210319_1757.py
  gcloud/taskflow3/models.py
  gcloud/taskflow3/resources.py
  gcloud/tasktmpl3/migrations/0018_auto_20210319_1752.py
  gcloud/tasktmpl3/resources.py
  iam/contrib/drf/shortcuts.py
Labels: V3.6.X_dev

#3446 bugfix: 修复网关节点点击报错问题&&修复点击节点树报错问题
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: V3.5.X

#3458 bugfix: 任务执行完毕后未执行节点状态不存在报错问题修复
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: V3.5.X

#3451 bugfix: 处理从3.5.X之前版本升级时Task字段修改带来的问题
  data_migration/management/commands/task_model_migrate.py
  dev_log/dev/normal-wls_202104012244.yaml
Labels: V3.6.X

#3475 3.5.35 begin
  app.yml
  config/default.py
  dev_log/3.5.35/normal-wls_202103161628.yaml
  docs/release.md
  pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_ip_selector.py
  pipeline_plugins/variables/collections/sites/open/cc.py
  pipeline_plugins/variables/static/variables/cmdb/var_cmdb_ip_selector.js
  readme.md
  readme_en.md
  static/variables/cmdb/var_cmdb_ip_selector.js
  version_log/version_logs_md/V3.5.35_2021-04-12.md
Labels: V3.5.X

#3477 improvmement: IP 选择器筛选条件支持自定义分隔符
  frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue
  frontend/desktop/src/components/common/RenderForm/SeparatorSelect.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
Labels: V3.5.X

#3476 improvement: 故障机替换插件添加关于复制故障机属性的使用提示
  dev_log/dev/normal-wls_202104081115.yaml
  dev_log/dev/normal-wls_202104121654.yaml
  pipeline_plugins/components/collections/sites/open/cc/replace_fault_machine/legacy.py
  pipeline_plugins/components/collections/sites/open/job/base.py
Labels: V3.6.X_dev

#3461 minor: 批量更新主机所属业务模块失败信息补充
  pipeline_plugins/components/collections/sites/open/cc/batch_transfer_host_module/v1_0.py
Labels: V3.6.X_dev

#3465 improvement:批量更新模块/集群属性插件自动转换参数类型并添加失败信息
  dev_log/dev/normal-wls_202104071201.yaml
  pipeline_plugins/components/collections/sites/open/cc/batch_module_update/v1_0.py
  pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/cc_test/batch_module_update/test_v1_0.py
Labels: V3.6.X_dev

#3273 improvmement: 模版导入业务id支持 bk_biz_id
  dev_log/dev/v_feifzhao_202103081435.yaml
  gcloud/tasktmpl3/api.py
Labels: optimization

#3496 OpenAPI接入及相关新增接口应用
  config/default.py
  config/urls_custom.py
  dev_log/dev/normal-wls_202104182115.yaml
  env.py
  gcloud/core/api.py
  gcloud/core/urls.py
  gcloud/iam_auth/view_interceptors/template.py
  gcloud/label/migrations/0002_auto_20210415_1205.py
  gcloud/label/models.py
  gcloud/label/viewsets.py
  gcloud/openapi/schema.py
  gcloud/tasktmpl3/api.py
  gcloud/tasktmpl3/apis/drf/serilaziers/template_scheme.py
  gcloud/tasktmpl3/apis/drf/viewsets/template_scheme.py
  gcloud/tasktmpl3/urls.py
  gcloud/tasktmpl3/validators.py
  requirements.txt
Labels: V3.6.X_dev

#3507 minor: add callback data log
  gcloud/taskflow3/api.py
Labels: V3.6.X, optimization

#3508 minor: 添加前端自动打包脚本 & check_variable_key接口兼容${xxx}情况
  gcloud/core/api.py
  gcloud/openapi/schema.py
  scripts/generate_frontend_files.sh
Labels: V3.6.X_dev

#3506 minor: add callback data log
  gcloud/taskflow3/api.py
  gcloud/taskflow3/apis/views/v4/node_callback.py
Labels: V3.6.X_dev, optimization

#3497 minor: BK_IAM_SKIP读取的环境变量添加BKAPP_IAM_SKIP
  env.py
Labels: V3.6.X

#3505 feature: 请求响应中添加trace_id信息
  dev_log/dev/normal-wls_202104201528.yaml
  gcloud/apigw/views/claim_functionalization_task.py
  gcloud/apigw/views/create_periodic_task.py
  gcloud/apigw/views/create_task.py
  gcloud/apigw/views/fast_create_task.py
  gcloud/apigw/views/get_common_template_info.py
  gcloud/apigw/views/get_common_template_list.py
  gcloud/apigw/views/get_functionalization_task_list.py
  gcloud/apigw/views/get_periodic_task_info.py
  gcloud/apigw/views/get_periodic_task_list.py
  gcloud/apigw/views/get_plugin_detail.py
  gcloud/apigw/views/get_plugin_list.py
  gcloud/apigw/views/get_task_detail.py
  gcloud/apigw/views/get_task_list.py
  gcloud/apigw/views/get_task_node_data.py
  gcloud/apigw/views/get_task_node_detail.py
  gcloud/apigw/views/get_task_status.py
  gcloud/apigw/views/get_tasks_manual_intervention_state.py
  gcloud/apigw/views/get_tasks_status.py
  gcloud/apigw/views/get_template_info.py
  gcloud/apigw/views/get_template_list.py
  gcloud/apigw/views/get_template_schemes.py
  gcloud/apigw/views/get_user_project_detail.py
  gcloud/apigw/views/get_user_project_list.py
  gcloud/apigw/views/import_common_template.py
  gcloud/apigw/views/import_project_template.py
  gcloud/apigw/views/modify_constants_for_periodic_task.py
  gcloud/apigw/views/modify_constants_for_task.py
  gcloud/apigw/views/modify_cron_for_periodic_task.py
  gcloud/apigw/views/node_callback.py
  gcloud/apigw/views/operate_node.py
  gcloud/apigw/views/operate_task.py
  gcloud/apigw/views/plugin_proxy.py
  gcloud/apigw/views/preview_common_task_tree.py
  gcloud/apigw/views/preview_task_tree.py
  gcloud/apigw/views/query_task_count.py
  gcloud/apigw/views/set_periodic_task_enabled.py
  gcloud/apigw/views/start_task.py
  gcloud/core/middlewares.py
  gcloud/tests/apigw/views/test_start_task.py
  packages/bkoauth/decorators.py
Labels: V3.6.X

#3498 improvement: 新增执行方案名称输入框交互优化
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
Labels: optimization

#3501 improvement: 标准插件统计插件多版本全选中问题修复
  dev_log/dev/v_xugzhou_202104191953.yaml
  frontend/desktop/src/pages/admin/statistics/Atom.vue
Labels: optimization

#3494 improvement: 插件版本列表倒序排序
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: optimization

#3481 improve: 模板数据无修改时去编辑执行方案不显示弹框
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: optimization

#3492 improvement: 克隆模板可以引用被克隆的模板
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: optimization

#3413 improvement: 静态IP选择器动态拓扑搜索框优化
  dev_log/dev/v_xugzhou_202103231125.yaml
  frontend/desktop/src/components/common/RenderForm/IpSelector/IpSearchInput.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/SingleIpSelector.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue
Labels: V3.6.X_dev

#3478 improvmement: 新建项目时点击执行方案获取方案详情接口返回字段前端调整
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: optimization

#3459 feature: 新增页面操作埋点
  frontend/desktop/src/main.js
  frontend/desktop/src/pages/home/CommonlyUsed.vue
  frontend/desktop/src/pages/home/MyCollection.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
Labels: V3.6.X_dev, feature

#3460 improvement: 企业微信分组插件增加对应icon
  dev_log/dev/fannluo_202104061654.yaml
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/scss/iconfont.scss
Labels: V3.6.X_dev, optimization

#3469 improvement:导航右侧切换项目下拉框筛选去掉停用项目
  dev_log/dev/fannluo_202104081016.yaml
  frontend/desktop/src/components/layout/NavigatorHeadRight.vue
Labels: V3.6.X_dev, optimization

#3472 improvement: 全局变量编辑保存时增加是否为特殊标志符检查
  dev_log/dev/fannluo_202104121023.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/ReuseVarDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/store/modules/template.js
Labels: V3.6.X_dev, optimization

#3499 improvement: 全局变量文本框类型支持正则校验
  dev_log/dev/v_xugzhou_202104191451.yaml
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: optimization

#3512 improvement: 执行详情侧栏中的"执行次数"在切换节点时未刷新问题修复
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: optimization

#3493 improvement: 全局变量类型添加说明
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: optimization

#3491 improvement：所有侧滑添加二次确认弹框
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/EditScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyTime.vue
  frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: optimization

#3513 improvement: 预渲染配置逻辑问题修复
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: optimization

#3490 optimization: apigw 错误日志增加异常堆栈
  gcloud/apigw/views/get_functionalization_task_list.py
  gcloud/apigw/views/get_task_status.py
  gcloud/apigw/views/get_template_list.py
  gcloud/apigw/views/plugin_proxy.py
  gcloud/apigw/views/utils.py
Labels: V3.6.X, optimization

#3522 feature: apigw添加第三方系统cmdb项目同步注册接口
  dev_log/dev/waylonshi_202104262238.yaml
  docs/apidoc/en/register_project.md
  docs/apidoc/zh_hans/register_project.md
  gcloud/apigw/urls.py
  gcloud/apigw/views/register_project.py
  gcloud/core/migrations/0021_auto_20210427_1455.py
  gcloud/core/models.py
  gcloud/core/project.py
  gcloud/tests/core/models/test_user_default_project.py
  gcloud/tests/core/test_project.py
  gcloud/tests/mock_settings.py
Labels: V3.6.X

#3516 improvement: 子流程更新状态判断逻辑问题修复
  dev_log/dev/v_xugzhou_202104251707.yaml
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: V3.6.X_dev, optimization
