Repository TencentBlueKing/bk-sops, pull requests merged in 2021-08, with the labels that each got.

#3822 improvement: 上传组件增加自定义上传函数配置项
  docs/develop/tag_usage_dev.md
  frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
Labels: V3.6.X_dev, optimization

#3823 feature: 执行方案支持编辑功能开发
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.6.X, feature

#3830 bugfix: 修复画布执行状态ui样式问题
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
Labels: V3.6.X, bug

#3804 minor: 移动端任务列表去掉只加载移动端创建任务的筛选条件
  frontend/mobile/src/store/modules/taskList.js
Labels: V3.6.X

#3834 minor: 去掉index.html引入的remote_api文件
  frontend/desktop/src/assets/html/index.html
Labels: V3.6.X

#3833 feature: 新增对接远程插件服务
  config/default.py
  config/urls_custom.py
  plugin_service/__init__.py
  plugin_service/admin.py
  plugin_service/api.py
  plugin_service/apps.py
  plugin_service/conf.py
  plugin_service/decorators.py
  plugin_service/env.py
  plugin_service/plugin.py
  plugin_service/plugin_client.py
  plugin_service/serializers.py
  plugin_service/tests/test_plugin.py
  plugin_service/urls.py
Labels: V3.6.X

#3841 minor: 插件服务环境变量添加BKAPP开头
  plugin_service/env.py
Labels: V3.6.X

#3844 bugfix: 修复 transfer_host_to_recyclemodule API 不存在的问题
  packages/blueking/component/apis/cc.py
Labels: bug, V3.6.X

#3846 bugfix: 3.6.4204 测试问题修复
  dev_log/dev/homholueng_202108111702.yaml
  pipeline_plugins/components/collections/sites/open/cc/update_module/legacy.py
  pipeline_plugins/components/static/components/atoms/monitor/alarm_shield/v1_1.js
  pipeline_plugins/components/static/components/atoms/monitor/alarm_shield_strategy/v1_1.js
  static/components/atoms/monitor/alarm_shield/v1_1.js
  static/components/atoms/monitor/alarm_shield_strategy/v1_1.js
Labels: bug, V3.6.X

#3855 bugfix: 3.5.45 测试问题修复
  api/collections/gse_kit.py
  config/default.py
  dev_log/dev/homholueng_202108131815.yaml
  gcloud/taskflow3/dispatchers/task.py
  requirements.txt
Labels: V3.6.X

#3852 bugfix: 修复因cc接口数量限制而导致的集群模版拉取不全问题
  dev_log/dev/waylon_202108131150.yaml
  pipeline_plugins/components/query/sites/open/cc.py
Labels: V3.6.X

#3851 bugfix: 修复全业务快速执行脚本新引擎回调失败问题
  dev_log/dev/waylon_202108131013.yaml
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
Labels: V3.6.X

#3854 minor: monaco-editor加载内部资源路径调试
  frontend/desktop/builds/webpack.base.js
Labels: V3.6.X

#3853 bugfix: upload组件绑定httpRequest方法异常修复
  frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
Labels: bug, V3.6.X_dev

#3842 bugfix: 新建轻应用无法选择类别问题修复
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
Labels: bug, V3.6.X_dev

#3838 bugfix: 任务执行状态浏览器tab icon路径去掉多余/
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/index.vue
Labels: bug, V3.6.X

#3817 improvement: 表格tag导出数据表头优化
  dev_log/3.6.40/fannluo_202107282026.yaml
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
Labels: optimization, V3.6.X

#3856 optimization: 日志配置优化,变量关键节点增加日志
  config/default.py
  pipeline_plugins/cmdb_ip_picker/utils.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
Labels: optimization, V3.6.X

#3843 bugfix: 修复 transfer_host_to_recyclemodule API 不存在的问题
  packages/blueking/component/apis/cc.py
Labels: bug, V3.6.X

#3672 feature: 新增蓝鲸服务(BK)-消息展示插件
  dev_log/dev/homholueng_202106211205.yaml
  pipeline_plugins/components/collections/sites/open/bk/display/__init__.py
  pipeline_plugins/components/collections/sites/open/bk/display/v1_0.py
  pipeline_plugins/components/static/components/atoms/bk/display/v1_0.js
Labels: feature, V3.6.X_dev

#3845 bugfix: 公共流程删除报错后弹窗不能再次显示修复
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
Labels: bug, V3.6.X

#3837 improvement: 全局变量为显示状态时默认值校验逻辑优化
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: optimization, V3.6.X

#3825 bugfix: 不存在的插件会导致画布卡死问题修复
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: bug, V3.6.X

#3850 improvement: 集群资源筛选变量存量数据兼容cmdb属性配置变更情况
  frontend/desktop/package.json
  frontend/desktop/postcss.config.js
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceList.vue
  frontend/desktop/src/components/common/RenderForm/SetAllocation/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
Labels: optimization, V3.6.X

#3871 bugfix: 任务结束通知支持人员分组配置
  dev_log/3.6.46/waylon_202108161658.yaml
  gcloud/periodictask/models.py
  gcloud/shortcuts/cmdb.py
  gcloud/taskflow3/models.py
  version_log/version_logs_md/V3.6.46_2021-08-16.md
Labels: V3.6.X

#3873 feature: 轻应用任务列表增加克隆功能
  dev_log/3.6.46/fannluo_202108162026.yaml
  frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  frontend/desktop/src/store/modules/taskList.js
Labels: feature, V3.6.X

#3874 minor: 流程模板编辑页面隐藏节点快捷操作面板增加条件并行网关，并左侧菜单栏隐藏该网关
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/scss/iconfont.scss
Labels: V3.6.X

#3876 bugfix: 任务节点code修改后打开配置面板提示逻辑优化
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: bug, V3.6.X

#3875 feature: 添加JOB获取任务日志插件
  dev_log/dev/waylon_202108162115.yaml
  pipeline_plugins/components/collections/sites/open/job/base.py
  pipeline_plugins/components/collections/sites/open/job/fetch_task_log/__init__.py
  pipeline_plugins/components/collections/sites/open/job/fetch_task_log/v1_0.py
  pipeline_plugins/components/static/components/atoms/job/fetch_task_log/v1_0.js
  pipeline_plugins/tests/components/collections/sites/open/job_test/fetch_task_log/__init__.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/fetch_task_log/test_v1_0.py
  static/components/atoms/job/fetch_task_log/v1_0.js
Labels: V3.6.X

#3888 improvement: 编辑执行方案时添加二次确认弹框
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: bug, V3.6.X

#3887 bugfix：新建轻应用无法选择类别问题修复
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
Labels: bug, V3.6.X

#3889 bugfix: 修复集群模块 ip 选择器服务模板输入不合法时会返回集群所有 ip 的问题
  dev_log/dev/homholueng_202108181145.yaml
  pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_set_module_ip_selector.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
Labels: bug, V3.6.X

#3897 feature：第三方插件执行支持
  frontend/desktop/builds/webpack.dev.config.js
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeItem.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/atomForm.js
Labels: feature, V3.6.X

#3909 bugfix: 修复流程DAT格式新增id导入时导入流程排序错误导致的子节点版本过期问题
  dev_log/dev/waylon_202108222231.yaml
  gcloud/tests/utils/algorithms/__init__.py
  gcloud/tests/utils/algorithms/test_algorithms.py
  gcloud/utils/algorithms.py
  pipeline_web/wrapper.py
Labels: V3.6.X

#3880 improvement: IP 选择器动态分组栏支持手动输入动态分组名
  frontend/desktop/src/components/common/RenderForm/IpSelector/ManualInput.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/MultipleIpSelector.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/SingleIpSelector.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
Labels: optimization, V3.6.X_dev

#3773 bugfix:修复节点管理表单插件名称版本级联问题
  pipeline_plugins/components/static/components/atoms/nodeman/plugin_operate/v1_0.js
  static/components/atoms/nodeman/plugin_operate/v1_0.js
Labels: bug

#3848 feature: IP选择器支持手动输入解析
  dev_log/dev/waylon_202108121549.yaml
  pipeline_plugins/cmdb_ip_picker/utils.py
  pipeline_plugins/tests/cmdb_ip_picker/utils/test_get_ip_picker_result.py
Labels: V3.6.X_dev

#3872 improvement: 轻应用、流程和任务列表接口添加项目权限校验
  dev_log/dev/waylon_202108162016.yaml
  gcloud/contrib/appmaker/resources.py
  gcloud/periodictask/resources.py
  gcloud/taskflow3/apis/tastypie/resources.py
  gcloud/tasktmpl3/apis/tastypie/resources.py
Labels: V3.6.X_dev

#3839 improvement: 流程节点名称放开对逗号等符号的限制
  dev_log/dev/waylon_202108101526.yaml
  gcloud/utils/strings.py
Labels: V3.6.X_dev

#3835 minor: 主机所属业务模块修改提示添加
  generated_yaml_data.yaml
  pipeline_plugins/components/collections/sites/open/cc/batch_transfer_host_module/v1_0.py
Labels: V3.6.X_dev

#3832 improvement： 文本值下拉框支持显示未选择选项信息
  dev_log/dev/waylon_202108061416.yaml
  pipeline_plugins/tests/variables/collections/test_text_value_select.py
  pipeline_plugins/variables/collections/common.py
Labels: V3.6.X_dev

#3738 feature: 增加 /taskflow/api/render_current_constants/{task_id}/ API
  gcloud/core/models.py
  gcloud/taskflow3/apis/drf/viewsets/__init__.py
  gcloud/taskflow3/apis/drf/viewsets/render_current_constants.py
  gcloud/taskflow3/domains/dispatchers/task.py
  gcloud/taskflow3/urls.py
  gcloud/tests/mock_settings.py
  gcloud/tests/taskflow3/dispatchers/task/__init__.py
  gcloud/tests/taskflow3/dispatchers/task/test_render_current_constants_v1.py
  gcloud/tests/taskflow3/dispatchers/task/test_render_current_constants_v2.py
Labels: feature, V3.6.X_dev

#3908 improve: 添加获取插件服务app信息接口
  gcloud/core/resources.py
  plugin_service/api.py
  plugin_service/plugin.py
  plugin_service/plugin_client.py
  plugin_service/serializers.py
  plugin_service/urls.py
Labels: V3.6.X

#3918 improvement: 画布工具栏样式优化
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/TemplateCanvas/ToolPanel/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/scss/iconfont.scss
Labels: optimization, V3.6.X

#3917 improvement: 导航栏任务模块优化
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/constants/routes.js
  frontend/desktop/src/scss/iconfont.scss
Labels: optimization, V3.6.X_dev

#3836 feature: 分级通知功能合入
  dev_log/dev/fannluo_202106251016.yaml
  dev_log/dev/waylonshi_202106211955.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/scss/common.scss
  frontend/desktop/src/store/modules/template.js
  gcloud/common_template/apis/tastypie/resources.py
  gcloud/periodictask/models.py
  gcloud/shortcuts/message/__init__.py
  gcloud/taskflow3/models.py
  gcloud/tasktmpl3/apis/tastypie/resources.py
  pipeline_plugins/components/collections/sites/open/job/base.py
Labels: V3.6.X_dev

#3916 improvement: ip选择器新样式界面问题修复
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
Labels: optimization, V3.6.X_dev

#3924 feature: 子流程任务节点支持查看执行信息和失败重试
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/store/modules/task.js
Labels: feature, V3.6.X_dev

#3921 improvement: 画布工具栏样式优化
  frontend/desktop/src/components/common/TemplateCanvas/ToolPanel/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: optimization, V3.6.X_dev

#3777 optimization: 新引擎通过bamboo engine api获取节点输入信息
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/taskflow3/models.py
  gcloud/tests/mock_settings.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py
Labels: V3.6.X_dev

#3932 bugfix: 导入临时方案问题修复
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
Labels: bug, V3.6.X

#3931 improvement: 第三方插件体验问题修复
  frontend/desktop/builds/webpack.dev.config.js
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeItem.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/scss/iconfont.scss
  frontend/desktop/src/store/modules/atomForm.js
Labels: feature

#3951 bugfix：流程本地快照存储空间超出最大值时保存失败问题修复
  frontend/desktop/src/utils/tplSnapshoot.js
Labels: bug, V3.6.X

#3911 feature: node_action API 支持 retry_subprocess
  gcloud/iam_auth/view_interceptors/taskflow.py
  gcloud/taskflow3/apis/django/api.py
  gcloud/taskflow3/domains/dispatchers/node.py
  requirements.txt
Labels: feature, V3.6.X_dev

#3977 bugfix: 前端测试问题修复
  frontend/desktop/src/components/common/RenderForm/IpSelector/ManualInput.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/home/MyDynamic.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: bug, optimization

#3976 bugfix: 前端测试问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
  frontend/desktop/src/components/skeleton/index.vue
  frontend/desktop/src/pages/task/TaskExecute/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/ImportYamlTplDialog.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
  frontend/desktop/src/scss/common.scss
  frontend/desktop/src/store/modules/templateList.js
Labels: type/bug
