Repository TencentBlueKing/bk-sops, pull requests merged in 2021-11, with the labels that each got.

#4362 前端资源加载入口url配置修改为相对路径
  gcloud/core/context_processors.py
Labels: type/optimization

#4365 运营数据二期开发
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/admin/statistics/HorizontalBarChart.vue
  frontend/desktop/src/pages/admin/statistics/Instance.vue
  frontend/desktop/src/pages/admin/statistics/Percentage.vue
  frontend/desktop/src/pages/admin/statistics/Template.vue
  frontend/desktop/src/pages/admin/statistics/VerticalBarChart.vue
  frontend/desktop/src/pages/admin/statistics/index.vue
Labels: type/feature

#4303 improvement: 项目配置权限问题修复
  frontend/desktop/src/pages/project/index.vue
Labels: type/optimization

#4379 流程执行次数topn支持后台配置
  gcloud/analysis_statistics/admin.py
  gcloud/analysis_statistics/migrations/0001_initial.py
  gcloud/analysis_statistics/models.py
  gcloud/taskflow3/models.py
  gcloud/tasktmpl3/models.py
Labels: ignore-for-release-notes

#4380 修复topn数据库未创建
  gcloud/analysis_statistics/migrations/0002_initial.py
Labels: ignore-for-release-notes

#4381 bugfix:修复数据库topn未创建
  gcloud/analysis_statistics/migrations/0002_initial.py
Labels: ignore-for-release-notes

#4356 定时节点支持任意长的定时时间
  pipeline_plugins/components/collections/controller.py
Labels: type/optimization

#4391 运营数据体验问题优化
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/admin/statistics/Instance.vue
  frontend/desktop/src/pages/admin/statistics/Percentage.vue
  frontend/desktop/src/pages/admin/statistics/Template.vue
Labels: type/optimization

#4385 第三方插件api前端调用方式调整
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/optimization

#4401 前端资源加载入口url配置修改为相对路径
  pipeline_plugins/components/collections/controller.py
Labels: type/optimization

#4079 minor: 表格组件增加配置最小宽度属性
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
Labels: type/optimization

#4403 password 组件支持配置公钥
  docs/develop/tag_usage_dev.md
  frontend/desktop/src/components/common/RenderForm/tags/TagPassword.vue
Labels: type/feature

#4402 open-telemetry trace support
  blueapps/opentelemetry/README.md
  blueapps/opentelemetry/__init__.py
  blueapps/opentelemetry/docs/assets/local_jaeger.png
  blueapps/opentelemetry/instrument_app/__init__.py
  blueapps/opentelemetry/instrument_app/apps.py
  blueapps/opentelemetry/instrument_app/celery.py
  blueapps/opentelemetry/instrumentor.py
  blueapps/opentelemetry/setup.py
  config/default.py
  env.py
  requirements.txt
Labels: type/feature

#4405 minor: release 3.9.15
  app.yml
  config/default.py
  version_log/version_logs_md/V3.9.15_2021-11-03.md
Labels: ignore-for-release-notes

#4407 修复没有BKAPP_OTEL_SAMPLER环境变量打开 trace 时报错的问题
  blueapps/opentelemetry/README.md
  blueapps/opentelemetry/setup.py
Labels: type/bug

#4408 minor: release 3.9.16
  app.yml
  config/default.py
  version_log/version_logs_md/V3.9.16_2021-11-03.md
Labels: type/bug

#4409 修复获取 BKAPP_OTEL_BK_DATA_ID 失败的问题
  blueapps/opentelemetry/setup.py
Labels: type/bug

#4410 修复 setup_trace_config 设置线上环境 Resource 类型错误的问题
  blueapps/opentelemetry/setup.py
Labels: type/bug

#4404 修复没有项目编辑权限的用户能够进入项目配置页面的问题
  frontend/desktop/src/pages/project/index.vue
Labels: type/bug

#4421 将 operate_task api 的 start action 改为异步执行
  gcloud/apigw/views/operate_task.py
  gcloud/tests/apigw/views/test_operate_task.py
  gcloud/tests/mock_settings.py
Labels: type/optimization

#4419 修复添加监控屏蔽插件按节点屏蔽节点ID传递错误的问题
  pipeline_plugins/components/collections/sites/open/monitor/alarm_shield/v1_1.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield/test_v1_1.py
Labels: type/bug

#4415 本地分发文件插件添加文件过期提示
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v1_0_0.py
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v2_0.py
Labels: type/optimization

#4223 查看收藏的模板申请权限 项目提示undefined问题修复
  frontend/desktop/src/pages/home/AddCollectionDialog.vue
Labels: type/bug

#4095 improvement: 全局错误信息提示优化
  frontend/desktop/src/api/index.js
Labels: type/optimization, ignore-for-release-notes

#4153 修复API操作任务节点时未记录流水日志的问题
  gcloud/contrib/operate_record/core.py
Labels: type/bug

#4224 节点名称，步骤名称输入框增加去掉首尾空格
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/optimization

#4274 上传tag组件支持携带cookie信息
  docs/develop/tag_usage_dev.md
  en_docs/develop/tag_usage_dev.md
  frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
Labels: type/feature

#4395 导出流程面板无法保存问题修复
  frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
Labels: type/bug

#4424 任务模块新建按钮不支持二次点击问题修复
  frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
Labels: type/bug

#4425 minor: release 3.9.17
  app.yml
  config/default.py
  version_log/version_logs_md/V3.9.17_2021-11-05.md
Labels: ignore-for-release-notes

#4075 minor: 标准运维添加ui自动化测试属性data-test-id
  frontend/desktop/src/components/common/advanceSearchForm/AdvanceSearch.vue
  frontend/desktop/src/components/common/advanceSearchForm/index.vue
  frontend/desktop/src/components/layout/Navigation.vue
  frontend/desktop/src/components/layout/NavigatorHeadRight.vue
  frontend/desktop/src/pages/admin/manage/AdminPeriodic.vue
  frontend/desktop/src/pages/admin/manage/AdminSearch/SearchResult.vue
  frontend/desktop/src/pages/admin/manage/AdminSearch/index.vue
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
  frontend/desktop/src/pages/appmaker/index.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/home/CommonlyUsed.vue
  frontend/desktop/src/pages/home/MyCollection.vue
  frontend/desktop/src/pages/home/MyDynamic.vue
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/PeriodicList/BootRecordDialog.vue
  frontend/desktop/src/pages/task/PeriodicList/DeletePeriodicDialog.vue
  frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/GatewaySelectDialog.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyTime.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
  frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  frontend/desktop/src/pages/task/TaskExecute/revokeDialog.vue
  frontend/desktop/src/pages/task/TaskList/TaskCloneDialog.vue
  frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/ListPageTipsTitle.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
Labels: ignore-for-release-notes

#4423 修复带有子流程任务保存运营数据失败
  gcloud/analysis_statistics/tasks.py
  gcloud/tests/analysis_statistics/tasks/test_recursive_collect_components_execution.py
  gcloud/tests/test_data.py
Labels: type/bug

#4427 修复job执行作业1.0版本插件部分情况下作业详情加载失败问题
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_0.js
  static/components/atoms/job/job_execute_task/v1_0.js
Labels: type/bug

#4429 minor: release 3.9.18
  app.yml
  config/default.py
  version_log/version_logs_md/V3.9.18_2021-11-05.md
Labels: ignore-for-release-notes

#3996 节点未连线时保存，把非法节点标红
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/feature

#4093 节点快捷面板增加在左边插入新节点的操作
  dev_log/dev/fannluo_202109181520.yaml
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/utils/dom.js
Labels: type/feature

#4055 任务详情页面支持查看所有全局变量的值
  frontend/desktop/src/pages/task/TaskExecute/GlobalVariable.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  frontend/desktop/src/store/modules/task.js
Labels: type/feature, ignore-for-release-notes

#4373 表达式分支标签支持调整
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/template.js
Labels: type/feature

#4436 任务详情页面支持查看所有全局变量的值
  frontend/desktop/src/pages/task/TaskExecute/GlobalVariable.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  frontend/desktop/src/store/modules/task.js
Labels: type/feature

#4430 修复运营数据插件流程引用详情返回id字段错误
  gcloud/tasktmpl3/models.py
Labels: type/bug

#4438 优化部分查询逻辑
  gcloud/analysis_statistics/migrations/0001_initial.py
  gcloud/analysis_statistics/migrations/0002_projectstatisticsdemision_tasktmplexecutetopn.py
  gcloud/analysis_statistics/migrations/0002_tasktmplexecutetopn.py
  gcloud/shortcuts/cmdb.py
  gcloud/taskflow3/models.py
  gcloud/tasktmpl3/models.py
Labels: ignore-for-release-notes

#4432 第三方插件展示输出参数逻辑处理
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: type/bug

#4440 修改拼写错误
  frontend/desktop/src/pages/admin/statistics/Percentage.vue
Labels: ignore-for-release-notes

#4439 修改拼写错误
  gcloud/analysis_statistics/admin.py
  gcloud/analysis_statistics/migrations/0002_projectstatisticsdemision_tasktmplexecutetopn.py
  gcloud/analysis_statistics/models.py
  gcloud/taskflow3/models.py
  gcloud/tasktmpl3/models.py
Labels: ignore-for-release-notes

#4371 无权限用户进入标准运维展示权限申请提示页面
  frontend/desktop/src/assets/images/add-biz.png
  frontend/desktop/src/assets/images/not-permission.png
  frontend/desktop/src/components/layout/Navigation.vue
  frontend/desktop/src/components/layout/NotPermissionComponent.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/routers/index.js
  frontend/desktop/src/store/modules/project.js
Labels: type/optimization

#4417 feature:运营数据维度丰富
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/admin/statistics/HorizontalBarChart.vue
  frontend/desktop/src/pages/admin/statistics/Instance.vue
  frontend/desktop/src/pages/admin/statistics/Percentage.vue
  frontend/desktop/src/pages/admin/statistics/Template.vue
  frontend/desktop/src/pages/admin/statistics/VerticalBarChart.vue
  frontend/desktop/src/pages/admin/statistics/index.vue
  gcloud/analysis_statistics/admin.py
  gcloud/analysis_statistics/data_migrate/tasks.py
  gcloud/analysis_statistics/migrations/0001_initial.py
  gcloud/analysis_statistics/migrations/0002_projectstatisticsdemision_tasktmplexecutetopn.py
  gcloud/analysis_statistics/models.py
  gcloud/constants.py
  gcloud/contrib/analysis/analyse_items/task_flow_instance.py
  gcloud/contrib/analysis/analyse_items/task_template.py
  gcloud/shortcuts/cmdb.py
  gcloud/taskflow3/models.py
  gcloud/tasktmpl3/models.py
Labels: type/feature

#4444 运营数据任务详情统计查询优化
  gcloud/taskflow3/models.py
Labels: type/optimization, ignore-for-release-notes

#4445 minor: release 3.10.0
  app.yml
  config/default.py
  version_log/version_logs_md/V3.10.0_2021-11-08.md
Labels: ignore-for-release-notes

#4446 修复BK_STATIC_URL修改导致静态资源访问不到问题
  gcloud/core/context_processors.py
Labels: ignore-for-release-notes

#4447 插件服务get_plugin_api_data接口返回成功时提取data数据
  plugin_service/api.py
Labels: type/optimization

#4455 V3.9.19 begin
  app.yml
  config/default.py
  version_log/version_logs_md/V3.9.19_2021-11-08.md
Labels: ignore-for-release-notes

#4461 通知接收人相关去重排序逻辑优化
  gcloud/periodictask/models.py
  gcloud/taskflow3/models.py
  pipeline_plugins/components/collections/sites/open/bk/notify/v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/bk_test/notify/test_v1_0.py
Labels: type/optimization

#4462 前端支持发起 otel trace
  frontend/desktop/src/api/index.js
  frontend/desktop/src/config/setting.js
  frontend/desktop/src/utils/uuid.js
Labels: type/feature

#4475 调整 uwsgi 进程启动命令
  support-files/supervisord.conf
Labels: type/optimization, ignore-for-release-notes

#4476 bugfix: 修复 V2 引擎无法兼容某些旧模板数据(isSkipped, can_retry)任务启动的问题
  pipeline_web/parser/format.py
Labels: type/bug

#4477 release 3.9.20
  app.yml
  config/default.py
  version_log/version_logs_md/V3.9.20_2021-11-10.md
Labels: ignore-for-release-notes

#4479 修复 V2 引擎无法兼容某些旧模板数据(isSkipped, can_retry)任务启动的问题
  pipeline_web/parser/format.py
Labels: type/bug

#4478 前端trace id生成规则调整
  frontend/desktop/src/utils/uuid.js
Labels: ignore-for-release-notes

#4480 minor: release 3.9.21
  app.yml
  config/default.py
  version_log/version_logs_md/V3.9.21_2021-11-10.md
Labels: ignore-for-release-notes

#4454 修复职能化任务列表认领人无法筛选的问题
  gcloud/contrib/function/resources.py
Labels: type/bug

#4483 修复全业务执行作业插件表单&传参问题
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_0.py
  pipeline_plugins/components/query/sites/open/job.py
  pipeline_plugins/components/static/components/atoms/job/all_biz_execute_job_plan/all_biz_execute_job_plan.js
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_execute_job_plan/test_v1_0.py
  static/components/atoms/job/all_biz_execute_job_plan/all_biz_execute_job_plan.js
  static/components/atoms/job/all_biz_execute_job_plan/all_biz_execute_job_plan_output.js
Labels: type/bug

#4484 minor: release 3.9.22
  app.yml
  config/default.py
  version_log/version_logs_md/V3.9.22_2021-11-11.md
Labels: ignore-for-release-notes

#4453 render_current_constants 接口异常处理优化
  gcloud/taskflow3/domains/dispatchers/task.py
  gcloud/tests/taskflow3/dispatchers/task/test_render_current_constants_v1.py
  gcloud/tests/taskflow3/dispatchers/task/test_render_current_constants_v2.py
Labels: type/optimization, ignore-for-release-notes

#4485 系统关键位置增加 opentelemetry span 记录
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/taskflow3/domains/dispatchers/task.py
Labels: type/feature

#4459 节点管理创建任务新增TJJ认证方式
  pipeline_plugins/components/collections/sites/open/nodeman/create_task/v2_0.py
  pipeline_plugins/components/query/sites/open/nodeman.py
  pipeline_plugins/components/static/components/atoms/nodeman/create_task/v2_0.js
  pipeline_plugins/tests/components/collections/sites/open/nodeman_test/create_task_test/test_nodeman_v2_create_task.py
Labels: type/feature, ignore-for-release-notes

#4488 修复任务详情分页limit错误
  gcloud/taskflow3/models.py
  gcloud/tests/mock_settings.py
  gcloud/tests/taskflow3/models/taskflow/test_group_by_instance_node.py
Labels: type/test-stage-bug

#4456 任务统计模块字段显示错误
  frontend/desktop/src/pages/admin/statistics/Percentage.vue
Labels: type/test-stage-bug, ignore-for-release-notes

#4466 修复job执行作业插件1.1版本全局变量加载失败
  pipeline_plugins/components/collections/sites/open/job/execute_task/v1_1.py
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_1.js
Labels: type/test-stage-bug

#4470 执行方案默认选中值调整
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
Labels: type/optimization

#4469 修复job执行作业1.0插件输入表单路径错误导致无法渲染
  pipeline_plugins/components/collections/sites/open/job/execute_task/v1_0.py
Labels: type/test-stage-bug

#4489 修复变量的KEY字段不合法时点击保存会一直补全格式的问题
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/bug

#4468 admin角色无法创建公共流程任务问题修复
  frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
Labels: type/bug

#4495 修复job插件执行历史下拉框无法跳转至JOB平台
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_1.js
Labels: type/bug

#4497 查看收藏的模板申请权限项目提示undefined问题修复
  frontend/desktop/src/pages/appmaker/AppCard.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
Labels: type/bug

#4501 修改定时插件的秒数正则,支持无限长时间定时
  pipeline_plugins/components/collections/controller.py
Labels: type/optimization, ignore-for-release-notes

#4496 自带trace模块功能调整
  blueapps/opentelemetry/README.md
  blueapps/opentelemetry/setup.py
  blueapps/opentelemetry/utils.py
  config/default.py
  gcloud/core/middlewares.py
  requirements.txt
Labels: type/optimization, ignore-for-release-notes

#4490 节点锚点拖动连线优化
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
Labels: type/optimization

#4441 修复表单勾选为全局变量后事件重复监听的问题
  frontend/desktop/src/components/common/RenderForm/formMixins.js
Labels: type/bug

#4499 修复全业务执行作业插件查询任务结果业务ID传参不正确问题
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_0.py
Labels: type/bug

#4502 节点管理新建任务插件添加版本号
  pipeline_plugins/components/collections/sites/open/nodeman/create_task/v2_0.py
Labels: type/bug

#4507 修复接口创建任务参数未传元变量时table类型变量默认值获取失败问题
  gcloud/taskflow3/models.py
Labels: type/bug

#4494 NodeDispatcher add bk_sops.task_id trace attribute
  env.py
  gcloud/taskflow3/apis/django/api.py
  gcloud/taskflow3/apis/django/v4/node_callback.py
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/taskflow3/models.py
  gcloud/tests/mock_settings.py
  gcloud/tests/taskflow3/models/taskflow/test_callback.py
  gcloud/tests/taskflow3/models/taskflow/test_get_node_data.py
  gcloud/tests/taskflow3/models/taskflow/test_get_node_detail.py
  gcloud/tests/taskflow3/models/taskflow/test_nodes_action.py
  gcloud/tests/taskflow3/models/taskflow/test_spec_nodes_timer_reset.py
  pipeline_plugins/components/collections/sites/open/bk/approve/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/execute_task/execute_task_base.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v1_0_0.py
  pipeline_plugins/components/utils/sites/open/utils.py
  pipeline_plugins/tests/utils/sites/open/test_utils.py
  requirements.txt
Labels: type/optimization

#4500 首页申请创建任务权限时错误问题修复
  frontend/desktop/src/pages/home/MyCollection.vue
Labels: type/bug, type/test-stage-bug

#4508 minor: release 3.9.23
  app.yml
  config/default.py
  version_log/version_logs_md/V3.9.23_2021-11-15.md
Labels: ignore-for-release-notes

#4510 Release V3.10.2
  app.yml
  app_desc.yaml
  blueapps/opentelemetry/README.md
  blueapps/opentelemetry/setup.py
  blueapps/opentelemetry/utils.py
  config/default.py
  env.py
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  gcloud/core/middlewares.py
  gcloud/taskflow3/apis/django/api.py
  gcloud/taskflow3/apis/django/v4/node_callback.py
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/taskflow3/models.py
  gcloud/tests/mock_settings.py
  gcloud/tests/taskflow3/models/taskflow/test_callback.py
  gcloud/tests/taskflow3/models/taskflow/test_get_node_data.py
  gcloud/tests/taskflow3/models/taskflow/test_get_node_detail.py
  gcloud/tests/taskflow3/models/taskflow/test_nodes_action.py
  gcloud/tests/taskflow3/models/taskflow/test_spec_nodes_timer_reset.py
  pipeline_plugins/components/collections/sites/open/bk/approve/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/execute_task/execute_task_base.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v1_0_0.py
  pipeline_plugins/components/utils/sites/open/utils.py
  pipeline_plugins/tests/utils/sites/open/test_utils.py
  requirements.txt
  version_log/version_logs_md/V3.10.2_2021-11-15.md
  version_log/version_logs_md/V3.9.23_2021-11-15.md
Labels: ignore-for-release-notes

#4512 节点使用第三方插件时点开详情面板会报错问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug

#4516 minor: release 3.9.24
  app.yml
  config/default.py
  version_logs_md/V3.9.24_2021-11-16.md
Labels: ignore-for-release-notes

#4513 计划任务创建失败时需要添加用户通知
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/NotifyTypeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
Labels: type/feature

#4515 计划任务创建失败支持通知
  gcloud/clocked_task/migrations/0003_auto_20211115_1511.py
  gcloud/clocked_task/models.py
  gcloud/clocked_task/serializer.py
  gcloud/clocked_task/tasks.py
  gcloud/shortcuts/message/__init__.py
  gcloud/shortcuts/message/common.py
Labels: type/feature

#4524 插件服务插件列表接口更新 & 插件数据获取接口支持转发本地上传文件
  blueapps/opentelemetry/utils.py
  plugin_service/api.py
  plugin_service/plugin_client.py
  plugin_service/serializers.py
  plugin_service/urls.py
Labels: type/feature

#4527 修复 opentelemetry 接入后导致 paasv2 uwsgi 进程无法启动的问题
  support-files/supervisord.conf
Labels: type/bug

#4529 调整 uwsgi 进程启动命令
  support-files/supervisord.conf
Labels: ignore-for-release-notes

#4526 计划任务创建失败支持配置通知
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/NotifyTypeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  gcloud/clocked_task/migrations/0003_auto_20211115_1511.py
  gcloud/clocked_task/models.py
  gcloud/clocked_task/serializer.py
  gcloud/clocked_task/tasks.py
  gcloud/shortcuts/message/__init__.py
  gcloud/shortcuts/message/common.py
Labels: type/feature

#4523 支持项目级别的用户自定义配置
  config/default.py
  config/urls_custom.py
  gcloud/conf/user/__init__.py
  gcloud/conf/user/apps.py
  gcloud/conf/user/constants.py
  gcloud/conf/user/decorator.py
  gcloud/conf/user/migrations/0001_initial.py
  gcloud/conf/user/migrations/__init__.py
  gcloud/conf/user/models.py
  gcloud/conf/user/serializer.py
  gcloud/conf/user/urls.py
  gcloud/conf/user/views/__init__.py
  gcloud/conf/user/views/get_userconf_by_fields.py
  gcloud/conf/user/views/set_userconf.py
  gcloud/tests/user/__init__.py
  gcloud/tests/user/models/test_userconf.py
Labels: type/feature

#4535 修复过期登陆后登陆成功页面不自动关闭问题
  blueapps/account/templates/account/login_success.html
Labels: type/bug

#4536 blueking工具包放入packages文件夹
  blueapps/patch/settings_open_saas.py
  config/sites/community/ver_settings.py
  config/sites/enterprise/ver_settings.py
  gcloud/conf/sites/community/ver_settings.py
  gcloud/conf/sites/enterprise/ver_settings.py
  packages/blueking/__init__.py
  packages/blueking/component/README
  packages/blueking/component/__init__.py
  packages/blueking/component/apis/__init__.py
  packages/blueking/component/apis/bk_login.py
  packages/blueking/component/apis/bk_paas.py
  packages/blueking/component/apis/cc.py
  packages/blueking/component/apis/cmsi.py
  packages/blueking/component/apis/esb.py
  packages/blueking/component/apis/gse.py
  packages/blueking/component/apis/itsm.py
  packages/blueking/component/apis/job.py
  packages/blueking/component/apis/jobv3.py
  packages/blueking/component/apis/monitor.py
  packages/blueking/component/apis/nodeman.py
  packages/blueking/component/apis/sops.py
  packages/blueking/component/apis/usermanage.py
  packages/blueking/component/base.py
  packages/blueking/component/client.py
  packages/blueking/component/collections.py
  packages/blueking/component/conf.py
  packages/blueking/component/exceptions.py
  packages/blueking/component/shortcuts.py
  packages/blueking/component/utils.py
Labels: ignore-for-release-notes

#4544 全业务执行作业插件get_node_callback_url同步修改
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_0.py
Labels: ignore-for-release-notes

#4545 勾选变量后全局变量窗口卡死问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug

#4547 minor: 文本框变量去除必填校验
  pipeline_plugins/variables/static/variables/input.js
  pipeline_plugins/variables/static/variables/textarea.js
Labels: ignore-for-release-notes

#4556 minor: IS_OPEN_V3 环境变量判断优化
  env.py
  env_v2.py
  env_v3.py
Labels: ignore-for-release-notes

#4561 minor: app_maker适配器 IS_OPEN_V3 环境变量判断优化
  gcloud/core/api_adapter/app_maker/__init__.py
  gcloud/core/api_adapter/app_maker/v3.py
Labels: ignore-for-release-notes

#4530 前端请求接口错误时错误信息中展示trace_id
  frontend/desktop/src/App.vue
  frontend/desktop/src/api/index.js
  frontend/desktop/src/config/setting.js
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/utils/errorNotify.js
Labels: type/feature

#4565 分发本地文件 2.0 插件上传文件后，在前端展示文件的MD5
  files/bartenders/upload_module.py
  files/bartenders/utils.py
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
Labels: type/feature

#4521 修复带子流程的模板运营数据创建失败
  gcloud/analysis_statistics/tasks.py
  gcloud/tests/analysis_statistics/tasks/test_tasktemplate_post_save_statistics_task.py
  gcloud/tests/mock_settings.py
  gcloud/tests/test_data.py
Labels: type/bug

#4568 去除job插件跳转作业平台url产生的多余斜杠
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_1.js
Labels: type/bug

#4569 修复 V2 引擎任务未执行时查看全局变量面板 500 的问题
  gcloud/taskflow3/domains/dispatchers/task.py
  gcloud/tests/taskflow3/dispatchers/task/test_render_current_constants_v2.py
Labels: type/bug

#4578 全业务快速执行脚本插件表单目标账户添加必填校验
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_0.py
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
Labels: type/optimization

#4579 minor: release 3.10.4
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.10.4_2021-11-23.md
Labels: ignore-for-release-notes

#4551 第三方插件接口调用逻辑调整
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/atomForm.js
Labels: type/optimization

#4581 运营数据-流程/任务统计数据不匹配问题修复
  frontend/desktop/src/pages/admin/statistics/Percentage.vue
Labels: type/bug

#4582 修复节点管理新建任务插件TJJ认证不可用的问题
  api/collections/nodeman.py
  pipeline_plugins/components/static/components/atoms/nodeman/create_task/v2_0.js
Labels: type/bug

#4583 修复插件多表单监听同一事件不生效的问题
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/formMixins.js
Labels: type/test-stage-bug

#4584 minor: release 3.10.5
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.10.5_2021-11-24.md
Labels: ignore-for-release-notes

#4577 任务节点支持配置自动重试
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/store/modules/template.js
Labels: type/feature

#4525 feature: 支持配置节点自动重试
  config/default.py
  gcloud/apigw/views/create_task.py
  gcloud/clocked_task/tasks.py
  gcloud/constants.py
  gcloud/periodictask/signals/handlers.py
  gcloud/taskflow3/admin.py
  gcloud/taskflow3/apis/tastypie/resources.py
  gcloud/taskflow3/celery/settings.py
  gcloud/taskflow3/celery/tasks.py
  gcloud/taskflow3/domains/auto_retry.py
  gcloud/taskflow3/migrations/0017_auto_20211116_1526.py
  gcloud/taskflow3/models.py
  gcloud/taskflow3/signals/handlers.py
  gcloud/tests/taskflow3/domains/__init__.py
  gcloud/tests/taskflow3/domains/test_auto_retry.py
  gcloud/tests/taskflow3/signals/__init__.py
  gcloud/tests/taskflow3/signals/handlers/__init__.py
  gcloud/tests/taskflow3/signals/handlers/test__dispatch_auto_retry_node_task.py
  gcloud/tests/taskflow3/tasks/test_auto_retry_node.py
  gcloud/tests/taskflow3/tasks/test_ensure_node_can_retry.py
Labels: type/feature

#4585 全业务快速执行脚本云区域 ID 字段调整为必填
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
Labels: type/optimization

#4594 节点管理新建任务插件认证方式为TJJ时auth_key为非必填
  pipeline_plugins/components/static/components/atoms/nodeman/create_task/v2_0.js
Labels: type/optimization

#4596 minor: release 3.10.6
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.10.6_2021-11-25.md
Labels: ignore-for-release-notes

#4591 节点自动重试禁用自动跳过，icon替换
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
Labels: ignore-for-release-notes

#4600 bugfix: 容器化版本人员选择器数据源 & IAM Host问题修复
  env_v3.py
Labels: ignore-for-release-notes

#4606 运营数据支持展示第三方插件
  frontend/desktop/src/pages/admin/statistics/Atom.vue
Labels: type/optimization

#4599 轻应用权限关联添加流程查看权限
  bksops_iam_migrations/migrations/0012_bk_sops_202111251154.py
  support-files/iam/12_update_mini_app_related_actions.json
Labels: type/optimization

#4597 修复ip选择器过滤条件传空字符串时筛选逻辑问题
  pipeline_plugins/cmdb_ip_picker/utils.py
  pipeline_plugins/tests/cmdb_ip_picker/utils/test_format_condition_value.py
  pipeline_plugins/tests/cmdb_ip_picker/utils/test_get_ip_picker_result.py
Labels: type/bug

#4601 跳转权限中心链接去掉path
  frontend/desktop/src/components/layout/permissionApply.vue
Labels: ignore-for-release-notes

#4615 修复快速执行脚本v1.1插件回调失败问题
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_1.py
Labels: type/bug

#4616 minor: V3.6.10 begin
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.10.7_2021-11-29.md
Labels: ignore-for-release-notes

#4617 修复周期任务新建任务面板中提示需要申请计划任务权限的问题
  frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
Labels: type/bug

#4607 修复第三方插件搜索不生效的问题
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
Labels: type/bug

#4580 新建的周期任务默认使用 V2 版本引擎
  gcloud/periodictask/models.py
  gcloud/tests/periodictask/models/test_periodic_task.py
Labels: type/feature

#4626 minor: release 3.11.0
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.11.0_2021-11-30.md
Labels: ignore-for-release-notes

#4396 子流程搜索不支持特殊符号问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
Labels: type/bug

#4416 节点循环切换标题文案调整
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: type/optimization

#4422 导入临时执行方案功能支持匹配tab
  frontend/desktop/src/pages/task/TaskCreate/EditScheme.vue
Labels: type/optimization

#4567 循环角标复数时显示优化
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/scss/iconfont.scss
Labels: type/optimization

#4589 bugfix: 修复克隆任务时没有克隆节点重试策略的问题
  gcloud/taskflow3/apis/django/api.py
  gcloud/taskflow3/models.py
  gcloud/tests/mock_settings.py
  gcloud/tests/taskflow3/models/taskflow/test_clone.py
Labels: type/bug, ignore-for-release-notes

#4624 流程模板表格字段支持自定义排序
  frontend/desktop/src/components/common/TableSettingContent.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/store/index.js
  support-files/supervisord.conf
Labels: type/feature

#4531 一次性任务再创建按钮置灰与无权限置灰分开
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: type/optimization

#4604 节点自动重试问题修复
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
Labels: ignore-for-release-notes

#4560 节点管理新建任务插件支持非对称加密传输敏感信息
  api/collections/nodeman.py
  gcloud/utils/crypto.py
  pipeline_plugins/components/collections/sites/open/nodeman/base.py
  pipeline_plugins/components/collections/sites/open/nodeman/create_task/v2_0.py
  pipeline_plugins/tests/components/collections/sites/open/nodeman_test/create_task_test/test_nodeman_v2_create_task.py
  requirements.txt
Labels: type/optimization

#4632 运营数据支持展示第三方插件
  frontend/desktop/src/pages/admin/statistics/Atom.vue
  frontend/desktop/src/store/modules/atomForm.js
Labels: type/optimization, type/feature

#4493 支持用户自行配置变量隐藏
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/feature
