Repository TencentBlueKing/bk-sops, pull requests merged in 2021-03, with the labels that each got.

#3328 imporvement:图表插件由plotly.js替换为bkcharts
  dev_log/dev/fannluo_202102231734.yaml
  frontend/desktop/package.json
  frontend/desktop/src/pages/admin/statistics/VerticalBarChart.vue
  frontend/desktop/src/pages/admin/statistics/index.vue
Labels: V3.6.X_dev, optimization

#3301 feature: 执行方案编辑调整到模板编辑页面中&&修复轻应用流程预览界面通过url进入时缺少参数修复
  dev_log/dev/v_xugzhou_202102041951.yaml
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/task/NodePreview.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/scss/iconfont.scss
  frontend/desktop/src/store/modules/task.js
Labels: V3.6.X_dev

#3346 bugfix: 修复密码变量解密失败的问题
  dev_log/dev/homholueng_20210302.yaml
  pipeline/utils/crypt.py
Labels: V3.5.X, bug

#3336 bugfix:修复参数填写页面表格动态加载列不生效的问题
  dev_log/dev/fannluo_202102241908.yaml
  frontend/desktop/src/pages/task/TaskParamEdit.vue
Labels: V3.5.X, bug

#3347 minor:更新jsflow包文件
  frontend/packages/jsflow/.gitignore
  frontend/packages/jsflow/src/lib/defaultOptions.js
  frontend/packages/jsflow/src/lib/dom.js
  frontend/packages/jsflow/src/lib/uuid.js
  frontend/packages/jsflow/webpack.config.js
Labels: optimization

#3168 minor:新增任务、模版记录流水功能
  config/default.py
  dev_log/dev/v_feifzhao_202012281202.yaml
  gcloud/apigw/views/create_task.py
  gcloud/apigw/views/fast_create_task.py
  gcloud/apigw/views/operate_node.py
  gcloud/apigw/views/operate_task.py
  gcloud/apigw/views/start_task.py
  gcloud/commons/template/resources.py
  gcloud/contrib/operate_record/__init__.py
  gcloud/contrib/operate_record/admin.py
  gcloud/contrib/operate_record/apps.py
  gcloud/contrib/operate_record/constants.py
  gcloud/contrib/operate_record/core.py
  gcloud/contrib/operate_record/decorators.py
  gcloud/contrib/operate_record/migrations/0001_initial.py
  gcloud/contrib/operate_record/migrations/__init__.py
  gcloud/contrib/operate_record/models.py
  gcloud/taskflow3/api.py
  gcloud/taskflow3/apis/views/v4/node_action.py
  gcloud/taskflow3/resources.py
  gcloud/tasktmpl3/resources.py
Labels: V3.6.X_dev, feature

#3340 bugfix: 修复 分发本地文件插件 多文件同时上传时tag错误问题
  dev_log/dev/normal-wls_202102251901.yaml
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v1_0_0.py
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files.js
  pipeline_plugins/tests/components/collections/sites/open/job_test/push_local_files/test_v1_0_0.py
  static/components/atoms/job/job_push_local_files.js
Labels: V3.5.X, bug

#3323 optimization: engine admin 页面性能优化
  pipeline/engine/admin.py
Labels: V3.6.X_dev, optimization

#3356 bugfix: 修复本地上传文件后前端列表不更新问题
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files.js
  static/components/atoms/job/job_push_local_files.js
Labels: V3.5.X, bug

#3352 bugfix: jsencrypt依赖包引入方式修改
  frontend/desktop/package.json
  frontend/desktop/src/components/common/RenderForm/tags/TagPassword.vue
Labels: V3.6.X, bug

#3357 bugfix: 修复分发本地文件插件 多文件同时上传时tag错误问题
  dev_log/dev/normal-wls_202102251901.yaml
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v1_0_0.py
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v2_0.py
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v1_0_0.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
  pipeline_plugins/tests/components/collections/sites/open/job_test/push_local_files/test_v1_0_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/push_local_files/test_v2_0.py
  static/components/atoms/job/job_push_local_files/v1_0_0.js
  static/components/atoms/job/job_push_local_files/v2_0.js
Labels: V3.6.X, bug

#3359 minor: V3.5.31 begin
  app.yml
  config/default.py
  dev_log/3.5.31/normal-wls_202103031901.yaml
  docs/release.md
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.5.31_2021-03-03.md
Labels: V3.5.X

#3361 minor: V3.6.33 begin
  app.yml
  config/default.py
  dev_log/3.6.33/javhou_202102251902.yaml
  dev_log/3.6.33/normal-wls_202102251901.yaml
  docs/release.md
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.6.33_2021-03-04.md
Labels: V3.6.X

#3369 bugfix: 修复集群资源筛选变量获取模块数量接口参数不正确问题
  frontend/desktop/src/store/index.js
Labels: V3.6.X, bug

#3335 bugfix:修复参数填写页面表格动态加载列不生效的问题
  dev_log/dev/fannluo_202102241908.yaml
  frontend/desktop/src/pages/task/TaskParamEdit.vue
Labels: V3.6.X_dev, bug

#3329 feature:前端检测静态资源更新时自动刷新页面
  frontend/desktop/src/routers/index.js
Labels: V3.6.X_dev, optimization

#3364 bugfix: 修复ip选择器动态分组topo筛选失败问题
  dev_log/dev/normal-wls_202103042057.yaml
  gcloud/utils/cmdb.py
  pipeline_plugins/cmdb_ip_picker/utils.py
  pipeline_plugins/tests/cmdb_ip_picker/utils/test_get_ip_picker_result.py
  scripts/new_dev_log.sh
Labels: V3.6.X, bug

#3377 improve: 汇聚网关文案调整
  dev_log/3.6.29/v_xugzhou_202103081420.yaml
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
Labels: V3.6.X_dev

#3375 feature: 列表页面支持用户配置视图，自定义需要展示的列
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
Labels: V3.6.X_dev

#3367 feature: 模板、任务操作流水功能
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/OperationFlow.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/SettingTabs.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabOperationFlow.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/index.vue
  frontend/desktop/src/scss/iconfont.scss
  frontend/desktop/src/store/modules/task.js
Labels: V3.6.X_dev

#3378 minor:集群资源筛选调用查询主机时增加search_host_lock参数
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
  frontend/desktop/src/store/index.js
Labels: V3.6.X, optimization

#3373 bugfix: 修复企业微信发送消息插件支持 Markdown 类型后老版本执行失败的问题问题
  dev_log/dev/homholueng_202103091454.yaml
  pipeline_plugins/components/collections/sites/open/wechat_work/wechat_work_send_message/v1_0.py
Labels: V3.6.X, bug

#3379 bugfix: 修复ip选择器查询主机加锁状态问题
  dev_log/dev/normal-wls_202103101038.yaml
  pipeline_plugins/cmdb_ip_picker/query.py
Labels: V3.6.X

#3385 minor: 3.6.35 begin
  app.yml
  config/default.py
  dev_log/3.6.35/homholueng_202103091454.yaml
  dev_log/3.6.35/normal-wls_202103101038.yaml
  docs/release.md
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.6.35_2021-03-12.md
Labels: V3.6.X

#3383 improve: 轻应用创建的任务名跟随轻应用名
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
Labels: V3.6.X_dev

#3381 improve: 修复VeeValidate组件计算属性中的名称和自定义列里面的名称重复问题
  frontend/desktop/src/components/common/Individualization/loopRuleSelect.vue
  frontend/desktop/src/main.js
  frontend/desktop/src/pages/admin/manage/SourceEdit/CacheForm.vue
  frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
  frontend/desktop/src/pages/task/TaskList/TaskCloneDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateSnapshoot.vue
Labels: V3.6.X_dev

#3393 optimization: 运营数据-任务统计页面性能优化
  gcloud/contrib/analysis/analyse_items/task_flow_instance.py
  gcloud/taskflow3/mixins.py
Labels: V3.6.X_dev, optimization

#3401 improve: 运营数据支持插件多版本
  frontend/desktop/src/pages/admin/statistics/Atom.vue
Labels: V3.6.X_dev

#3400 improve: IP 选择器筛选条件支持自定义分隔符
  dev_log/dev/v_xugzhou_202103161506.yaml
  frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
Labels: V3.6.X_dev

#3376 improve: 集群资源筛选主机资源所述支持搜索
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
Labels: V3.6.X_dev

#3384 feature: 提供根据 KEY 获取 renderform context 中变量值的方法
  dev_log/3.6.29/v_xugzhou_202103111920.yaml
  frontend/desktop/src/components/common/RenderForm/formMixins.js
Labels: V3.6.X_dev

#3396 improvement: get_task_status和get_task_detail接口添加基于业务的60s缓存
  dev_log/dev/normal-wls_202103161754.yaml
  gcloud/apigw/utils.py
  gcloud/apigw/views/get_task_detail.py
  gcloud/apigw/views/get_task_status.py
Labels: V3.6.X_dev

#3374 minor: pylint 问题修复
  api/__init__.py
  api/utils/thread.py
  blueapps/middleware/xss/middlewares.py
  blueapps/middleware/xss/pxfilter.py
  gcloud/commons/template/utils.py
  gcloud/commons/template/validators.py
  gcloud/contrib/admin/migration_api/staff_group.py
  gcloud/core/resources.py
  gcloud/utils/dates.py
  gcloud/utils/validate.py
  iam/api/client.py
  iam/auth/models.py
  iam/contrib/converter/base.py
  iam/contrib/django/dispatcher/dispatchers.py
  iam/contrib/drf/permission.py
  iam/contrib/drf/resource.py
  iam/contrib/tastypie/authorization.py
  iam/contrib/tastypie/resource.py
  iam/resource/dispatcher.py
  iam/resource/provider.py
  packages/blueking/component/client.py
  pipeline/contrib/statistics/tasks.py
  pipeline/core/data/context.py
  pipeline/engine/core/handlers/base.py
  pipeline/engine/models/core.py
  pipeline/parser/utils.py
  pipeline/utils/mako_utils/checker.py
  pipeline/utils/mako_utils/visitors.py
  pipeline_plugins/components/collections/sites/open/nodeman/create_task/legacy.py
  pipeline_plugins/components/collections/sites/open/wechat_work/wechat_work_send_message/v1_0.py
  pipeline_plugins/components/http.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_set_module_selector.py
  pipeline_web/drawing_new/rank/feasible_tree.py
  pipeline_web/wrapper.py
  scripts/auto_reload_tools/auto_reload_worker.py
  scripts/extract_version_log.py
Labels: V3.6.X, optimization

#3386 improvement: 变量解析新增os.path下函数支持
  config/default.py
  dev_log/dev/normal-wls_202103150131.yaml
  pipeline/core/data/sandbox.py
Labels: V3.6.X_dev

#3287 improvement:密码变量中公私钥支持从环境变量中读取
  config/sites/community/ver_settings.py
  config/sites/enterprise/ver_settings.py
  dev_log/dev/normal-wls_202102011636.yaml
  env.py
Labels: V3.6.X_dev

#3316 improvement: 优化批量修改主机属性插件校验逻辑，支持云区域ID:IP的填写方式
  dev_log/dev/normal-wls_202102191756.yaml
  pipeline_plugins/components/collections/sites/open/cc/batch_update_host/v1_0.py
Labels: V3.6.X_dev, optimization

#3286 improvement: 优化 快速执行脚本v1.0版本 脚本名称模糊匹配问题
  dev_log/dev/normal-wls_202101311558.yaml
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
Labels: V3.6.X_dev

#3333 minor:本地上传文件支持跨业务
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v1_0_0.py
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v2_0.py
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v1_0_0.js
  pipeline_plugins/components/utils/common.py
  static/components/atoms/job/job_push_local_files/v1_0_0.js
  static/components/atoms/job/job_push_local_files/v2_0.js
Labels: V3.6.X_dev, feature

#3409 bugfix: 修复带子流程模版导入后无法打开问题
  dev_log/dev/normal-wls_202103221711.yaml
  gcloud/tasktmpl3/models.py
  pipeline_web/wrapper.py
Labels: V3.6.X

#3358 minor: job执行作业支持ip跨业务
  pipeline_plugins/components/collections/sites/open/job/execute_task/legacy.py
  pipeline_plugins/components/static/components/atoms/job/job_execute_task.js
  static/components/atoms/job/job_execute_task.js
Labels: feature

#3397 feature:renderform 组件内置获取任一表单值的方法
  dev_log/dev/fannluo_202011081511.yaml
  docs/develop/tag_usage_dev.md
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/components/common/RenderForm/formMixins.js
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.5.X, feature

#3415 improve: 后台管理配置主包源S3类型子目录去掉必填校验
  dev_log/dev/v_xugzhou_202103231541.yaml
  frontend/desktop/src/pages/admin/manage/SourceEdit/PackageForm.vue
Labels: V3.6.X_dev

#3414 minor：骨架屏样式调整
  frontend/desktop/src/components/skeleton/index.vue
  frontend/desktop/src/components/skeleton/loaders/appmakerList.vue
  frontend/desktop/src/components/skeleton/loaders/commonList.vue
  frontend/desktop/src/components/skeleton/loaders/taskList.vue
  frontend/desktop/src/components/skeleton/loaders/templateList.vue
  frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
  frontend/desktop/src/pages/appmaker/index.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/audit/index.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/functor/index.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
Labels: V3.6.X_dev, feature

#3411 improvement: 模板列表支持展示最后更新人
  dev_log/dev/v_xugzhou_202103221452.yaml
  frontend/desktop/src/pages/template/TemplateList/index.vue
Labels: V3.6.X_dev

#3420 minor: 代码格式修改
  frontend/desktop/src/components/skeleton/loaders/templateList.vue
Labels: V3.6.X_dev

#3419 improvement:插件列表按照版本号递增排序
  dev_log/dev/fannluo_202103231717.yaml
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.6.X_dev, optimization

#3412 improvement: 运营数据-任务数据 按时间查询项目过滤参数修改
  dev_log/dev/v_xugzhou_202103221111.yaml
  frontend/desktop/src/pages/admin/statistics/Instance.vue
Labels: V3.6.X_dev

#3387 bugfix:修复表格tag部分列导入数据不成功问题
  dev_log/dev/fannluo_202103151505.yaml
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
Labels: V3.6.X_dev, bug

#3418 improve: 公共流程再创建报错问题修复
  dev_log/dev/v_xugzhou_202103231523.yaml
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/index.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/store/modules/task.js
Labels: V3.5.X

#3388 bugfix:修复表格tag部分列导入数据不成功问题
  dev_log/3.5.32/fannluo_202103151511.yaml
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
Labels: V3.5.X, bug

#3403 minor: taskflow statistics where statement optimization
  gcloud/taskflow3/mixins.py
Labels: V3.6.X_dev, optimization

#3422 improvement:申请权限弹窗操作按钮交互优化；页面最小宽度设置
  frontend/desktop/src/App.vue
  frontend/desktop/src/components/common/modal/PermissionModal.vue
  frontend/desktop/src/components/layout/CopyrightFooter.vue
  frontend/desktop/src/components/layout/Navigation.vue
  frontend/desktop/src/components/layout/permissionApply.vue
Labels: V3.6.X_dev, optimization

#3362 MAKO 变量预渲染
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
  pipeline_web/parser/format.py
  pipeline_web/tests/parser/format/test_format_web_data_to_pipeline.py
Labels: V3.6.X_dev, feature

#3390 improve: 运营数据相同请求发两次问题修复
  dev_log/3.6.29/v_xugzhou_202103160920.yaml
  frontend/desktop/src/pages/admin/statistics/index.vue
Labels: V3.6.X_dev

#3429 minor:全站样式调整
  frontend/desktop/src/components/layout/Navigation.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/home/MyDynamic.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
Labels: V3.6.X_dev

#3344 improvement:前端构建性能优化
  frontend/desktop/builds/webpack.base.js
  frontend/desktop/package.json
Labels: V3.6.X_dev, optimization

#3368 bugfix: 修复某些流程结构出现时保存流程导致网关合法性校验死循环的问题
  dev_log/dev/homholueng_202103081431.yaml
  pipeline/tests/validators/cases.py
  pipeline/validators/gateway.py
Labels: V3.6.X_dev, bug

#3427 improve: 轻应用的分类改为下拉列表
  dev_log/dev/v_xugzhou_202103251610.yaml
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
Labels: V3.6.X_dev

#3318 minor: 增加 celery 任务状态事件发送配置
  config/default.py
Labels: V3.6.X_dev, optimization

#3293 bugfix:修复 处理api/status接口&微信端流程权限问题
  dev_log/dev/normal-wls_202102031619.yaml
  gcloud/iam_auth/view_interceptors/taskflow.py
  gcloud/taskflow3/api.py
  weixin/resources.py
Labels: V3.6.X_dev

#3324 improvement: 添加业务下最大周期任务数限制，默认为50, 支持管理员配置。
  dev_log/dev/normal-wls_202102201114.yaml
  env.py
  gcloud/apigw/views/create_periodic_task.py
  gcloud/core/migrations/0021_auto_20210219_1936.py
  gcloud/core/migrations/0022_merge_20210326_1511.py
  gcloud/core/models.py
  gcloud/periodictask/resources.py
Labels: V3.6.X_dev, optimization

#3434 bugfix: 修复系统时间插件前端时间单位没有标题问题
  dev_log/dev/normal-wls_202103291521.yaml
  dev_log/dev/normal-wls_202103291627.yaml
  pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
  pipeline_plugins/variables/static/variables/current_time.js
  requirements.txt
  static/components/atoms/job/job_fast_execute_script.js
  static/variables/current_time.js
Labels: V3.6.X_dev

#3436 bugfix: 处理自动排版后条件网关outgoing不合法问题
  config/default.py
  dev_log/dev/normal-wls_202103301510.yaml
  pipeline_web/drawing_new/utils.py
Labels: V3.6.X_dev

#3439 bugfix:修复项目进入配置页面权限问题
  dev_log/3.6.36/fannluo_202003301743.yaml
  frontend/desktop/src/pages/project/index.vue
Labels: V3.6.X, bug

#3438 improvement：ip选择器支持自定义分隔符
  dev_log/dev/normal-wls_202103161628.yaml
  pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_ip_selector.py
  pipeline_plugins/variables/collections/sites/open/cc.py
  pipeline_plugins/variables/static/variables/cmdb/var_cmdb_ip_selector.js
  static/variables/cmdb/var_cmdb_ip_selector.js
Labels: V3.6.X_dev

#3417 improvement: 流程模板分类弱化前端修改
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/components/common/advanceSearchForm/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/home/AddCollectionDialog.vue
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
  frontend/desktop/src/pages/template/TemplateEdit/SettingTabs.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
  frontend/desktop/src/scss/common.scss
  frontend/desktop/src/store/modules/project.js
  frontend/desktop/src/store/modules/template.js
Labels: optimization

#3437 bugfix: 修复节点执行日志接口报错问题
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: V3.5.X
