Repository TencentBlueKing/bk-sops, pull requests merged in 2021-07, with the labels that each got.

#3717 minor: 元变量表单hookable改为true
  pipeline_plugins/variables/static/variables/datatable.js
  pipeline_plugins/variables/static/variables/select.js
Labels: V3.6.X

#3692 feature: 历史任务清理功能合入
  config/default.py
  env.py
  gcloud/taskflow3/dispatchers/task.py
  gcloud/taskflow3/models.py
  gcloud/taskflow3/resources.py
Labels: V3.6.X_dev

#3704 bugfix: 修复预渲染变量条件判断问题
  pipeline_web/parser/format.py
Labels: V3.6.X

#3715 bugfix: 修复系统变量在新版本引擎子流程中无法渲染的问题
  gcloud/taskflow3/dispatchers/task.py
  requirements.txt
Labels: bug

#3709 bugfix: 修复 get_tasks_status 在处理 children 字段时未判断是否存在的问题
  gcloud/apigw/views/get_tasks_status.py
Labels: bug

#3729 bugfix: 修复 TaskCommandDispatcher.start_v1 任务 ID 获取方式不正确的问题
  gcloud/taskflow3/dispatchers/task.py
Labels: bug

#3744 bugfix: 修复 engine v2 任务启动时不支持有环任务及周期任务未传入额外流程上下文的问题
  config/default.py
  engine_pickle_obj/__init__.py
  engine_pickle_obj/context.py
  gcloud/taskflow3/context.py
  gcloud/taskflow3/dispatchers/task.py
  requirements.txt
Labels: bug

#3743 improvement: V3.6.X体验问题修复
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskCreateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.6.X_dev, optimization

#3745 improvement: 表格列储存的storage添加兼容处理
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
Labels: V3.6.X_dev, optimization

#3749 minor: V3.6.43 begin
  app.yml
  config/default.py
  dev_log/3.6.41/fannluo_202106291559.yaml
  dev_log/3.6.41/fannluo_202106291612.yaml
  dev_log/3.6.42/fannluo_202106091503.yaml
  dev_log/3.6.42/fannluo_202106092113.yaml
  dev_log/3.6.42/fannluo_202106101733.yaml
  dev_log/3.6.42/homholueng_202106152027.yaml
  dev_log/3.6.42/homholueng_202106161659.yaml
  dev_log/3.6.43/15191008900_202106092033.yaml
  dev_log/3.6.43/fannluo_202104301453.yaml
  dev_log/3.6.43/fannluo_202105201015.yaml
  dev_log/3.6.43/fannluo_202105271131.yaml
  dev_log/3.6.43/fannluo_202105311103.yaml
  dev_log/3.6.43/fannluo_202106012041.yaml
  dev_log/3.6.43/fannluo_202106012048.yaml
  dev_log/3.6.43/fannluo_202106012120.yaml
  dev_log/3.6.43/fannluo_202106081439.yaml
  dev_log/3.6.43/fannluo_202106181046.yaml
  dev_log/3.6.43/homholueng_202106281537.yaml
  dev_log/3.6.43/v_xugzhou_202105261549.yaml
  dev_log/3.6.43/v_xugzhou_202106241200.yaml
  dev_log/3.6.43/waylonshi_202106171022.yaml
  dev_log/3.6.43/waylonshi_202106172341.yaml
  docs/release.md
  frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/template.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.6.42_2021-06-29.md
  version_log/version_logs_md/V3.6.43_2021-07-07.md
Labels: V3.6.X

#3751 bugfix: 修复创建集群插件设计容量字段为int校验不通过问题
  pipeline_plugins/components/collections/sites/open/cc/create_set/v1_0.py
  pipeline_plugins/components/collections/sites/open/cc/create_set/v2_0.py
Labels: V3.6.X

#3753 fixbug: 表格列储存的兼容时数据类型异常问题修复
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
Labels: bug

#3770 bugfix: 修复导入模板和执行方案时执行方案内节点 ID 未替换的问题
  pipeline_web/wrapper.py
Labels: V3.6.X, bug

#3771 feature: 流程模板列表支持批量操作
  dev_log/dev/fannluo_202107141950.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
  frontend/desktop/src/scss/common.scss
  frontend/desktop/src/store/modules/templateList.js
Labels: V3.6.X_dev, feature

#3785 optimization: 批量更新主机所属业务模块表单优化
  pipeline_plugins/components/static/components/atoms/cc/batch_transfer_host_module/v1_0.js
  static/components/atoms/cc/batch_transfer_host_module/v1_0.js
Labels: optimization

#3795 bugfix: 测试问题修复
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
  frontend/desktop/src/pages/appmaker/index.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
Labels: bug

#3798 feature: filemanager.push_files_to_ips 支持传入 timeout 参数
  files/managers/base.py
  files/managers/nfs.py
  files/managers/upload_module.py
Labels: V3.6.X, bug

#3747 improvement:流程列表默认先倒序排序
  frontend/desktop/src/pages/template/TemplateList/index.vue
Labels: optimization

#3724 feature: 提示用户去更新父流程
  dev_log/3.6.40/v_zyxazhang_202107011525.yaml
  frontend/desktop/src/components/common/advanceSearchForm/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/store/modules/template.js
Labels: feature

#3805 improvement: 修改参数无数据时获取组件dom失败问题修复
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
Labels: bug, optimization

#3803 bugfix: 测试问题修复
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: V3.6.X, bug

#3766 bugfix: 修复隐藏状态的下拉框变量取值的问题
  frontend/desktop/src/pages/task/ParameterInfo.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
Labels: bug

#3813 optimization: 后台增加对业务级别环境变量 key 的校验逻辑
  gcloud/project_constants/apis/drf/serializers.py
Labels: optimization

#3816 feature: 添加JOB获取任务日志插件
  dev_log/dev/waylonshi_202107281529.yaml
  pipeline_plugins/components/collections/sites/open/job/base.py
  pipeline_plugins/components/collections/sites/open/job/fetch_task_log/__init__.py
  pipeline_plugins/components/collections/sites/open/job/fetch_task_log/v1_0.py
  pipeline_plugins/components/static/components/atoms/job/fetch_task_log/v1_0.js
  pipeline_plugins/tests/components/collections/sites/open/job_test/fetch_task_log/__init__.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/fetch_task_log/test_v1_0.py
  static/components/atoms/job/fetch_task_log/v1_0.js
Labels: V3.6.X_dev
