Repository TencentBlueKing/bk-sops, pull requests merged in 2021-06, with the labels that each got.

#3564 improvement: 变量预渲染逻辑放到EmptyStartHandler中处理
  dev_log/dev/waylonshi_202105131503.yaml
  pipeline_web/parser/format.py
  pipeline_web/tests/parser/format/test_format_web_data_to_pipeline.py
Labels: V3.6.X_dev

#3354 feature: 新增 历史引擎任务运行时数据定时清理 功能
  config/default.py
  dev_log/dev/normal-wls_202103022209.yaml
  env.py
  gcloud/taskflow3/api.py
  gcloud/taskflow3/models.py
  gcloud/taskflow3/resources.py
  pipeline/conf/default_settings.py
  pipeline/engine/states.py
  pipeline/engine/tasks.py
  pipeline/migrations/0029_auto_20210302_1946.py
  pipeline/models.py
  pipeline/tests/engine/test_states.py
Labels: V3.6.X_dev, feature

#3630 模板接口公共代码提取
  gcloud/common_template/apis/django/api.py
  gcloud/common_template/apis/django/validators.py
  gcloud/tasktmpl3/apis/django/api.py
  gcloud/tasktmpl3/apis/django/validators.py
  gcloud/tasktmpl3/models.py
  gcloud/template_base/apis/django/api.py
  gcloud/template_base/apis/django/validators.py
Labels: V3.6.X_dev, optimization

#3640 bugfix: 模板 API 统一后导出模板 500 问题修复
  gcloud/common_template/apis/django/api.py
  gcloud/iam_auth/view_interceptors/common_template.py
  gcloud/iam_auth/view_interceptors/template.py
  gcloud/tasktmpl3/apis/django/api.py
  gcloud/template_base/apis/django/api.py
  gcloud/template_base/apis/django/validators.py
Labels: V3.6.X_dev, bug

#3642 optimization: schema_convertor 联调问题修复
  gcloud/common_template/models.py
  gcloud/tasktmpl3/models.py
  gcloud/template_base/domains/importer.py
Labels: optimization

#3647 feature: 新增通过环境变量添加 JOB 日志变量提取模式功能
  dev_log/dev/homholueng_202106101226.yaml
  env.py
  pipeline_plugins/components/collections/sites/open/job/base.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_legacy.py
Labels: V3.6.X, feature

#3639 feature:全局变量新增克隆功能
  dev_log/dev/fannluo_202106081439.yaml
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
Labels: V3.6.X_dev, feature

#3633 bugfix:修复子流程更新时下拉框变量选项同步失败的问题
  dev_log/dev/fannluo_202106071030.yaml
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: V3.6.X, bug

#3565 improvement: 历史数据清理前端处理
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/mixins/task.js
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  frontend/desktop/src/scss/task.scss
Labels: V3.6.X_dev, optimization

#3577 feature: 元变量支持勾选为全局变量
  dev_log/dev/fannluo_202105201015.yaml
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: V3.6.X_dev, feature

#3531 improvement: renderform表单正则校验默认通过格式类型值
  dev_log/dev/fannluo_202104301453.yaml
  frontend/desktop/src/components/common/RenderForm/formMixins.js
Labels: V3.6.X_dev, optimization

#3597 minor:公共流程编辑去掉执行代理人配置
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
Labels: V3.6.X_dev

#3605 feature: 任务执行页面动态设置浏览器tab的title/icon功能
  dev_log/dev/fannluo_202105271131.yaml
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/index.vue
  frontend/desktop/src/utils/dom.js
  static/core/images/bk_sops_created.png
  static/core/images/bk_sops_failed.png
  static/core/images/bk_sops_finished.png
  static/core/images/bk_sops_running.png
Labels: V3.6.X_dev, feature

#3622 minor：分支网关表达式说明提到外面
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
Labels: V3.6.X_dev, optimization

#3606 minor:条件并行网关icon补充
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/assets/html/index-dev.html
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ConditionalParallelGateway.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/scss/iconfont.scss
Labels: V3.6.X_dev, optimization

#3609 improvement: 自动忽略错误跳过的节点需要有角标标记
  dev_log/dev/v_xugzhou_202105261549.yaml
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: V3.6.X_dev, feature, optimization

#3623 feature: 参数填写页面增加变量key显示
  dev_log/dev/fannluo_202106012048.yaml
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
Labels: V3.6.X_dev, feature

#3624 feature: 模板添加任务类型偏好设置
  dev_log/dev/fannluo_202106012120.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/store/modules/template.js
Labels: V3.6.X_dev, feature

#3613 feature:任务执行树支持查看控制节点执行详情
  dev_log/dev/fannluo_202105311103.yaml
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: V3.6.X_dev, feature

#3575 improvement:子流程加载时机优化
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.6.X_dev, feature

#3621 feature: 轻应用列表新增复制桌面链接操作
  dev_log/dev/fannluo_202106012041.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/appmaker/AppCard.vue
Labels: V3.6.X_dev, feature

#3576 feature: 子流程批量更新
  frontend/desktop/builds/mock/config/index.js
  frontend/desktop/builds/mock/index.js
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/SubflowUpdateTips.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/template.js
Labels: V3.6.X_dev, feature

#3389 improve: 代码检查问题处理
  frontend/desktop/builds/mock/index.js
  frontend/desktop/builds/webpack.dev.config.js
  frontend/desktop/src/api/fileDownload.js
  frontend/desktop/src/api/index.js
  frontend/desktop/src/components/common/RenderForm/formMixins.js
  frontend/desktop/src/config/login.js
  frontend/desktop/src/config/setting.js
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/constants/timeZones.js
  frontend/desktop/src/directives/cursor.js
  frontend/desktop/src/directives/index.js
  frontend/desktop/src/main.js
  frontend/desktop/src/mixins/permission.js
  frontend/desktop/src/mixins/task.js
  frontend/desktop/src/pages/atomdev/atomConfigSchema.js
  frontend/desktop/src/pages/atomdev/importTag.js
  frontend/desktop/src/routers/index.js
  frontend/desktop/src/store/index.js
  frontend/desktop/src/store/modules/atomForm.js
  frontend/desktop/src/store/modules/periodic.js
  frontend/desktop/src/store/modules/project.js
  frontend/desktop/src/store/modules/task.js
  frontend/desktop/src/store/modules/template.js
  frontend/desktop/src/store/modules/templateList.js
  frontend/desktop/src/utils/atomFilter.js
  frontend/desktop/src/utils/checkDataType.js
  frontend/desktop/src/utils/dom.js
  frontend/desktop/src/utils/errorHandler.js
  frontend/desktop/src/utils/formSchema.js
  frontend/desktop/src/utils/nodeFilter.js
  frontend/desktop/src/utils/tools.js
  frontend/desktop/src/utils/tplSnapshoot.js
  frontend/desktop/src/utils/transAtom.js
  frontend/desktop/src/utils/uuid.js
  frontend/desktop/src/utils/validatePipeline.js
  frontend/desktop/test/unit/components/RenderForm/combinePlugin.js
  frontend/desktop/test/unit/components/RenderForm/singlePlugin.js
  frontend/mobile/mock/ajax/app/index.js
  frontend/mobile/mock/ajax/util.js
  frontend/mobile/src/api/cached-promise.js
  frontend/mobile/src/api/index.js
  frontend/mobile/src/api/request-queue.js
  frontend/mobile/src/common/auth.js
  frontend/mobile/src/common/preload.js
  frontend/mobile/src/common/util.js
  frontend/mobile/src/router/index.js
  frontend/mobile/src/store/index.js
  frontend/mobile/src/store/modules/component.js
  frontend/mobile/src/store/modules/task.js
  frontend/mobile/src/store/modules/taskList.js
  frontend/mobile/src/store/modules/template.js
  frontend/mobile/src/utils/errorHandler.js
  frontend/mobile/src/utils/tools.js
Labels: V3.6.X_dev

#3655 bugfix: 勾选变量无法显示默认值问题修复
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: V3.6.X, bug

#3654 minor: 模板编辑页loading时机优化
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.6.X_dev

#3604 improvement: datatable导出excel数据类型扩展
  dev_log/dev/fannluo_202105571036.yaml
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
Labels: V3.6.X, optimization

#3657 minor: V3.6.41 begin
  app.yml
  config/default.py
  dev_log/3.6.41/fannluo_202105571036.yaml
  dev_log/3.6.41/fannluo_202106071030.yaml
  dev_log/3.6.41/homholueng_202106101226.yaml
  docs/release.md
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.6.41_2021-06-15.md
Labels: V3.6.X

#3658 bugfix: 修复batch_form接口version和template不对应问题
  gcloud/common_template/apis/django/api.py
  gcloud/template_base/apis/django/api.py
  gcloud/template_base/apis/drf/viewsets/template_scheme.py
Labels: V3.6.X_dev

#3660 bugfix: 修复变量预渲染选择后值绑定不正确的问题
  dev_log/3.6.41/fannluo_202106161626.yaml
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: V3.6.X, bug

#3659 集群模块 IP 选择器问题修复
  dev_log/dev/homholueng_202106152027.yaml
  gcloud/constants.py
  pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_set_module_ip_selector.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
  pipeline_plugins/variables/query/sites/open/query.py
  pipeline_plugins/variables/utils.py
Labels: V3.6.X, bug

#3661 bugfix: 修复 lazy 类型变量支持预渲染引入的问题
  dev_log/dev/homholueng_202106161659.yaml
  pipeline_web/parser/format.py
Labels: V3.6.X, bug

#3665 minor: status接口去掉iam鉴权逻辑
  gcloud/iam_auth/view_interceptors/taskflow.py
  gcloud/taskflow3/api.py
Labels: V3.6.X

#3638 minor: page_not_found兼容各个环境
  gcloud/core/views.py
Labels: V3.6.X

#3664 bugfix: 修复create_task接口创建未传元变量参数时对应参数默认值获取失败问题
  dev_log/dev/waylonshi_202106172341.yaml
  gcloud/taskflow3/models.py
Labels: V3.6.X_dev

#3649 bugfix: 修复集群资源筛选变量导入excel数据时ip列为空问题
  dev_log/dev/fannluo_202106101733.yaml
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceList.vue
  frontend/desktop/src/components/common/RenderForm/SetAllocation/index.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
Labels: V3.6.X, bug

#3645 bugfix: 修复表格tag操作按钮在任务执行开始后禁用态不生效问题
  dev_log/dev/fannluo_202106091503.yaml
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
Labels: V3.6.X, bug

#3644 improvement:全局异常信息展示优化
  dev_log/dev/fannluo_202106092113.yaml
  frontend/desktop/src/App.vue
  frontend/desktop/src/api/index.js
  frontend/desktop/src/config/setting.js
  frontend/desktop/src/scss/common.scss
  frontend/desktop/src/utils/errorHandler.js
  frontend/desktop/src/utils/errorNotify.js
Labels: V3.6.X, optimization

#3656 minor: 任务执行页面节点树样式优化
  frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
Labels: V3.6.X_dev

#3679 feature: 流程模板导入、导出YAML文件
  frontend/desktop/package.json
  frontend/desktop/postcss.config.js
  frontend/desktop/src/components/common/advanceSearchForm/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
  frontend/desktop/src/pages/template/TemplateList/ImportDatTplDialog.vue
  frontend/desktop/src/pages/template/TemplateList/ImportYamlTplDialog.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
  frontend/desktop/src/store/modules/templateList.js
Labels: feature

#3674 feature: 支持任务通知分级功能
  dev_log/dev/waylonshi_202106211955.yaml
  gcloud/periodictask/models.py
  gcloud/shortcuts/message/__init__.py
  gcloud/taskflow3/models.py
  gcloud/tasktmpl3/apis/tastypie/resources.py
Labels: V3.6.X_dev

#3676 bugfix: 修复 bamboo-engine worker 进程命令不正确的问题
  support-files/supervisord.conf
Labels: V3.6.X_dev, bug

#3677 bugfix: 修复查看子流程中节点详情时 500 的问题
  gcloud/taskflow3/dispatchers/node.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v1.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py
Labels: V3.6.X_dev, bug

#3690 feature: 流程模板支持消息分级配置
  dev_log/dev/fannluo_202106251016.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/store/modules/template.js
Labels: feature

#3696 feature: Yaml Schema Converter添加条件并行网关支持
  gcloud/template_base/domains/schema_converter.py
Labels: V3.6.X_dev

#3702 feature: 批量更新主机所属业务模块支持输入不带业务名的路径拓扑
  dev_log/dev/homholueng_202106281537.yaml
  pipeline_plugins/components/collections/sites/open/cc/base.py
  pipeline_plugins/components/collections/sites/open/cc/batch_transfer_host_module/v1_0.py
  pipeline_plugins/components/static/components/atoms/cc/batch_transfer_host_module/v1_0.js
  pipeline_plugins/tests/components/collections/sites/open/cc_test/batch_transfer_host_module/test_v1_0.py
Labels: feature

#3681 feature: 子流程新增总是使用最新版本选项
  dev_log/dev/fannluo_202106181046.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: feature

#3705 improvement: tag text新增是否保留文本原始格式配置项
  dev_log/dev/fannluo_202106282156.yaml
  docs/develop/tag_usage_dev.md
  frontend/desktop/src/components/common/RenderForm/tags/TagText.vue
Labels: V3.6.X_dev, optimization

#3697 improvement: 查看变量引用节点操作路径优化
  dev_log/dev/fannluo_202106252215.yaml
  frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.6.X_dev, optimization

#3698 bugfix: 修复表格tag导入文件数据列与表格列不匹配导致失败的问题
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
Labels: V3.6.X, bug

#3708 bugfix: 修复职能化任务页面无法返回上一页的问题
  dev_log/3.6.41/fannluo_202106291612.yaml
  frontend/desktop/src/pages/task/TaskExecute/index.vue
Labels: V3.6.X, bug

#3707 bugfix: 修复ip选择器被子流程勾选为变量后点开节点会抛异常的问题
  dev_log/3.6.41/fannluo_202106291559.yaml
  frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
Labels: V3.6.X, bug
