Repository TencentBlueKing/bk-sops, pull requests merged in 2021-12, with the labels that each got.

#4514 职能化任务失败支持通知认领人
  gcloud/taskflow3/models.py
  gcloud/tests/taskflow3/models/taskflow/test_function_task_claimant.py
Labels: type/optimization

#4486 添加系统内置全局变量 TASK_URL
  gcloud/taskflow3/domains/context.py
  gcloud/tests/mock.py
  gcloud/tests/taskflow3/context/task_context/test_task_url.py
Labels: type/feature

#4603 父流程更新子流程远程拉取数据问题修复
  frontend/desktop/src/components/common/RenderForm/IpSelector/SingleIpSelector.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
Labels: type/bug

#4639 支持用户自定义项目配置
  config/default.py
  gcloud/resources/urls.py
  gcloud/tasktmpl3/apis/tastypie/resources.py
  gcloud/tests/user_custom_config/__init__.py
  gcloud/tests/user_custom_config/constants/__init__.py
  gcloud/tests/user_custom_config/constants/test_get_options_by_fileds.py
  gcloud/tests/user_custom_config/models/__init__.py
  gcloud/tests/user_custom_config/models/test_userconf.py
  gcloud/tests/user_custom_config/serializer/__init__.py
  gcloud/tests/user_custom_config/serializer/test_user_custom_project_config_options_serializer.py
  gcloud/user_custom_config/__init__.py
  gcloud/user_custom_config/apps.py
  gcloud/user_custom_config/constants.py
  gcloud/user_custom_config/migrations/0001_initial.py
  gcloud/user_custom_config/migrations/__init__.py
  gcloud/user_custom_config/models.py
  gcloud/user_custom_config/serializer.py
  gcloud/user_custom_config/viewsets/__init__.py
  gcloud/user_custom_config/viewsets/user_custom_config.py
  gcloud/user_custom_config/viewsets/user_custom_config_options.py
Labels: type/feature

#4643 minor: release 3.13.0
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.13.0_2021-12-02.md
Labels: ignore-for-release-notes

#4646 修复找不到BK_SOPS_HOST配置导致任务启动失败
  config/default.py
Labels: type/bug

#4655 docs: V3.13.0版本日志更新
  version_logs_md/V3.13.0_2021-12-02.md
Labels: ignore-for-release-notes

#4652 插件服务拉取带详情插件列表接口增加插件名称进行排序
  plugin_service/api.py
  plugin_service/plugin_client.py
Labels: type/optimization

#4658 公共流程创建任务传参错误问题修复
  frontend/desktop/src/pages/home/SelectCreateTaskDialog.vue
Labels: type/bug

#4631 ui自动化测试修复和补充
  frontend/desktop/src/components/common/advanceSearchForm/index.vue
  frontend/desktop/src/pages/admin/manage/AdminPeriodic.vue
  frontend/desktop/src/pages/admin/manage/AdminSearch/SearchResult.vue
  frontend/desktop/src/pages/admin/manage/AdminSearch/index.vue
  frontend/desktop/src/pages/appmaker/AppCard.vue
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/appmaker/index.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/task/ClockedList/DeleteClockedDialog.vue
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/ClockedList/index.vue
  frontend/desktop/src/pages/task/PeriodicList/BootRecordDialog.vue
  frontend/desktop/src/pages/task/PeriodicList/DeletePeriodicDialog.vue
  frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  frontend/desktop/src/pages/task/TaskList/TaskCloneDialog.vue
  frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/NotifyTypeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
Labels: type/optimization

#4633 Notify通知提示样式展示错误问题修复
  frontend/desktop/src/App.vue
Labels: type/bug

#4651 前端体验测试问题修复
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/TaskCreate/EditScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
Labels: type/optimization

#4657 修复增加节点自动重试后无法启动计划任务的问题
  gcloud/clocked_task/tasks.py
  gcloud/tests/clocked_task/__init__.py
  gcloud/tests/clocked_task/test_tasks.py
  gcloud/tests/mock_settings.py
Labels: type/bug

#4668 pre-commit hook 添加本地commit lint校验
  .pre-commit-config.yaml
Labels: ignore-for-release-notes

#4673 优化IP选择器过滤结果为空时的错误提示
  pipeline_plugins/cmdb_ip_picker/utils.py
  pipeline_plugins/tests/cmdb_ip_picker/utils/test_get_ip_picker_result.py
Labels: type/optimization

#4674 supervisord.conf 中添加对 node_auto_retry 队列的监听
  support-files/supervisord.conf
Labels: type/optimization

#4672 修复插件统计列表无法获取内置插件数据
  gcloud/taskflow3/models.py
  gcloud/tasktmpl3/models.py
Labels: type/bug

#4664 添加node callback重试延迟逻辑
  gcloud/taskflow3/apis/django/api.py
  gcloud/taskflow3/apis/django/v4/node_callback.py
Labels: type/optimization

#4675 feature: bamboo-pipeline upgrade to 3.10.0
  requirements.txt
Labels: type/feature

#4676 release 3.12.1
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.12.1_2021-12-06.md
Labels: ignore-for-release-notes

#4669 流程表格支持用户自定义排序字段
  frontend/desktop/src/App.vue
  frontend/desktop/src/components/common/TableSettingContent.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/store/modules/project.js
Labels: ignore-for-release-notes

#4665 用户自行配置变量隐藏逻辑问题修复
  frontend/desktop/src/components/common/RenderForm/IpSelector/SingleIpSelector.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/bug

#4680 节点管理创建任务插件表单左右空白宽度不对称问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
Labels: type/optimization

#4677 已执行任务不允许修改变量
  frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicGroup.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicIp.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/SingleIpSelector.vue
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceList.vue
Labels: type/bug

#4683 流程表格支持用户自定义排序字段
  frontend/desktop/src/App.vue
  frontend/desktop/src/components/common/TableSettingContent.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/store/modules/project.js
Labels: type/feature, ignore-for-release-notes

#4687 release 3.13.1
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.13.1_2021-12-07.md
Labels: ignore-for-release-notes

#4685 全局变量拖拽bug修复
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
Labels: type/bug

#4696 Merge master
  .github/workflows/eslint.yml
  .pre-commit-config.yaml
  app.yml
  app_desc.yaml
  config/default.py
  frontend/desktop/src/App.vue
  frontend/desktop/src/components/common/advanceSearchForm/index.vue
  frontend/desktop/src/pages/admin/manage/AdminPeriodic.vue
  frontend/desktop/src/pages/admin/manage/AdminSearch/SearchResult.vue
  frontend/desktop/src/pages/admin/manage/AdminSearch/index.vue
  frontend/desktop/src/pages/appmaker/AppCard.vue
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/appmaker/index.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/task/ClockedList/DeleteClockedDialog.vue
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/ClockedList/index.vue
  frontend/desktop/src/pages/task/PeriodicList/BootRecordDialog.vue
  frontend/desktop/src/pages/task/PeriodicList/DeletePeriodicDialog.vue
  frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  frontend/desktop/src/pages/task/TaskList/TaskCloneDialog.vue
  frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/NotifyTypeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  gcloud/taskflow3/apis/django/api.py
  gcloud/taskflow3/apis/django/v4/node_callback.py
  gcloud/taskflow3/models.py
  gcloud/tasktmpl3/models.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_set_module_selector.py
  plugin_service/api.py
  plugin_service/plugin_client.py
  requirements.txt
  version_logs_md/V3.12.1_2021-12-06.md
  version_logs_md/V3.13.1_2021-12-07.md
Labels: ignore-for-release-notes

#4704 项目流程默认排序字段修改为ID降序
  gcloud/tests/user_custom_config/models/test_userconf.py
  gcloud/user_custom_config/models.py
Labels: type/optimization

#4702 修复查看使用了某些变量的任务全局变量时 500 的问题
  gcloud/taskflow3/apis/drf/viewsets/render_current_constants.py
  gcloud/tests/utils/test_json.py
  gcloud/utils/json.py
Labels: type/bug

#4705 app_desc.yaml 添加 node_auto_retry 队列
  app_desc.yaml
Labels: type/bug

#4692 input组件配置showpassword属性后查看模式不显示实际值
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
Labels: type/optimization

#4706 流程模版表格表头排序设置保存
  frontend/desktop/src/pages/template/TemplateList/index.vue
Labels: type/optimization

#4713 bugfix: 节点参数js报错问题修复
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: type/bug

#4712 第三方插件滚动加载拿不到dom问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
Labels: type/bug

#4711 默认执行方案报错bug修复
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/store/modules/task.js
Labels: type/bug

#4695 可输入下拉框通过样式标记用户输入选项
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
Labels: type/optimization

#4714 release 3.13.2
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.13.2_2021-12-13.md
Labels: ignore-for-release-notes

#4682 节点详情面板增加节点 ID 的展示
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: type/optimization

#4724 项目流程可排序字段去掉pipeline_template前缀
  gcloud/tasktmpl3/apis/tastypie/resources.py
  gcloud/user_custom_config/constants.py
Labels: type/optimization

#4717 删除模板时添加消息提示
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/NotifyTypeConfig.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
Labels: type/optimization

#4681 暂停或失败或执行中的任务显示全局变量
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
Labels: type/optimization

#4690 minor: plugin detail list 文档更新
  plugin_service/serializers.py
Labels: type/feature, ignore-for-release-notes

#4679 导入Yaml格式文件支持自动填入对应业务ID
  gcloud/tasktmpl3/models.py
  gcloud/template_base/apis/django/api.py
  gcloud/template_base/domains/importer.py
  gcloud/template_base/utils.py
Labels: type/optimization

#4689 获取资源类apigw-api新增响应字段auth_actions
  gcloud/apigw/views/get_common_template_list.py
  gcloud/apigw/views/get_periodic_task_list.py
  gcloud/apigw/views/get_task_list.py
  gcloud/apigw/views/get_template_list.py
  gcloud/apigw/views/utils.py
  gcloud/iam_auth/conf.py
  gcloud/iam_auth/res_factory.py
  gcloud/iam_auth/utils.py
  gcloud/tests/apigw/views/test_get_common_template_list.py
  gcloud/tests/apigw/views/test_get_periodic_task_list.py
  gcloud/tests/apigw/views/test_get_task_list.py
  gcloud/tests/apigw/views/test_get_template_list.py
Labels: type/feature

#4694 插件表单输入参数支持获取前端传入的need_render字段
  pipeline_web/parser/format.py
  pipeline_web/tests/parser/format/test_format_web_data_to_pipeline.py
  requirements.txt
Labels: type/feature

#4723 optimization: 职能化任务转交功能需求
  config/urls_custom.py
  gcloud/contrib/function/api.py
  gcloud/contrib/function/serializers.py
  gcloud/contrib/function/urls.py
Labels: type/optimization

#4718 optimization: 审批插件支持在标准运维页面上也进行审批
  api/collections/itsm.py
  pipeline_plugins/components/query/sites/open/itsm.py
  pipeline_plugins/components/query/sites/open/query.py
Labels: type/optimization

#4703 自动化测试批量删除接口
  gcloud/auto_test/__init__.py
  gcloud/auto_test/apis/__init__.py
  gcloud/auto_test/apis/authentication.py
  gcloud/auto_test/apis/mixin.py
  gcloud/auto_test/apis/permission.py
  gcloud/auto_test/apis/serilaziers/__init__.py
  gcloud/auto_test/apis/serilaziers/common.py
  gcloud/auto_test/apis/viewsets/__init__.py
  gcloud/auto_test/apis/viewsets/periodic_task.py
  gcloud/auto_test/apis/viewsets/template.py
  gcloud/auto_test/apis/viewsets/token.py
  gcloud/auto_test/apps.py
  gcloud/auto_test/urls.py
  gcloud/resources/urls.py
Labels: type/feature

#4743 连线标签点击事件触发增加移动阈值范围
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
Labels: type/bug

#4739 项目流程可排序字段去掉pipeline_template前缀
  gcloud/tasktmpl3/apis/tastypie/resources.py
  gcloud/user_custom_config/constants.py
Labels: type/optimization

#4741 体验问题修复
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
Labels: type/bug

#4742 变量编辑页面增加格式化语句的快捷插入操作面板
  frontend/desktop/builds/webpack.dev.config.js
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/store/modules/template.js
Labels: type/feature

#4747 画布移动时渲染性能优化
  frontend/desktop/src/assets/js/flow.js
Labels: type/optimization

#4722 子流程任务状态轮询逻辑优化
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/optimization

#4726 模板列表页表格自定表头支持渲染排序icon
  frontend/desktop/src/pages/template/TemplateList/index.vue
Labels: type/bug

#4710 全局变量面板优化
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/TheadPopover.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableCitedList.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariablePreviewValue.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/feature

#4776 optimization: 职能化任务转交功能需求
  config/urls_custom.py
  gcloud/contrib/function/api.py
  gcloud/contrib/function/serializers.py
  gcloud/contrib/function/urls.py
Labels: type/optimization

#4772 optimization: 审批插件支持在标准运维页面上也进行审批
  api/collections/itsm.py
  pipeline_plugins/components/query/sites/open/itsm.py
  pipeline_plugins/components/query/sites/open/query.py
Labels: type/optimization

#4780 optimization: 审批插件支持在标准运维页面上也进行审批
  api/collections/itsm.py
  pipeline_plugins/components/query/sites/open/itsm.py
  pipeline_plugins/components/query/sites/open/query.py
Labels: type/optimization

#4779 optimization: 职能化任务转交功能需求
  config/urls_custom.py
  gcloud/contrib/function/api.py
  gcloud/contrib/function/serializers.py
  gcloud/contrib/function/urls.py
Labels: type/optimization

#4783 无权限用户调用apigw获取资源类api添加空的auth_actions字段
  gcloud/apigw/views/get_common_template_list.py
  gcloud/apigw/views/get_periodic_task_list.py
  gcloud/apigw/views/get_task_list.py
  gcloud/apigw/views/get_template_list.py
  gcloud/tests/apigw/views/test_get_template_list.py
Labels: type/optimization

#4792 全局变量体验问题修复
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/TheadPopover.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#4788 快捷插入操作面板体验问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug

#4815 模板生成器 operator 文案优化
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/optimization

#4817 子流程节点更新按钮优化
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/optimization

#4816 全局变量面板优化
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/TheadPopover.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
Labels: type/optimization

#4808 子流程勾选第三方插件参数创建任务时报错问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
Labels: type/bug

#4796 节点输入参数支持配置是否渲染变量
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
  frontend/desktop/src/scss/iconfont.scss
Labels: type/feature

#4801 职能化任务转交
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/store/modules/function.js
Labels: type/feature

#4818 itsm审批插件支持在标准运维审批
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/store/modules/task.js
Labels: type/feature

#4778 任务节点支持配置超时控制策略
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/store/modules/template.js
  gcloud/constants.py
Labels: type/feature

#4805 yaml导出流程命名与dat导出流程保持一致
  gcloud/template_base/apis/django/api.py
Labels: type/optimization

#4813 修复返回路径的基本名称,返回路径的目录名模板不生效问题
  gcloud/mako_template_helper/hub.py
Labels: type/bug

#4824 optimization: 审批插件支持在标准运维页面上也进行审批itsm接口版
  api/collections/itsm.py
  pipeline_plugins/components/query/sites/open/itsm.py
Labels: type/optimization

#4838 修复插件插件服务数据接口带参数GET请求转发参数丢失问题
  plugin_service/api.py
Labels: type/bug

#4837 添加节点超时最大时长配置
  config/default.py
  gcloud/core/context_processors.py
  gcloud/taskflow3/utils.py
Labels: type/optimization, ignore-for-release-notes

#4836 快捷插入操作面板体验问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/optimization

#4844 minor: start V3.13.4
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.13.3_2021-12-20.md
  version_logs_md/V3.13.4_2021-12-24.md
Labels: ignore-for-release-notes

#4845 节点超时配置文案、时长数据类型、最大时长调整
  frontend/desktop/src/assets/html/index-dev.html
  frontend/desktop/src/assets/html/index.html
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
Labels: ignore-for-release-notes

#4843 快速执行脚本优化重复数据接口请求问题
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
Labels: type/optimization

#4804 修复轻应用环境域名切换后跳转问题
  gcloud/contrib/appmaker/models.py
  gcloud/contrib/appmaker/resources.py
Labels: type/bug

#4848 minor: start V3.13.5
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.13.5_2021-12-24.md
Labels: ignore-for-release-notes

#4777 使用create替代update_or_create保存任务统计数据避免产生死锁
  gcloud/analysis_statistics/tasks.py
  gcloud/tests/analysis_statistics/tasks/test_taskflowinstance_post_save_statistics_task.py
  gcloud/tests/mock_settings.py
Labels: type/bug

#4850 修改html注入的int类型变量接收方式
  frontend/desktop/src/assets/html/index.html
Labels: ignore-for-release-notes

#4857 itsm审批插件支持在标准运维审批(依赖itsm2.6.0)
  api/collections/itsm.py
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/store/modules/task.js
  pipeline_plugins/components/query/sites/open/itsm.py
Labels: type/feature

#4855 触发条件字段为空时报错修复
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/bug

#4859 minor: start V3.14.0
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.14.0_2021-12-27.md
Labels: ignore-for-release-notes

#4862 minor: start V3.13.6
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.13.6_2021-12-28.md
Labels: ignore-for-release-notes

#4863 minor: key为空值时处理
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: ignore-for-release-notes

#4864 轻应用link字段域名更新采用settings.APP_HOST
  gcloud/contrib/appmaker/resources.py
Labels: type/optimization

#4867 修复login_success窗口无法自动关闭问题
  blueapps/patch/settings_open_saas.py
Labels: type/bug

#4866 修复excel导入空单元格不识别的问题
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
Labels: type/bug

#4868 minor: start V3.13.7
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.13.7_2021-12-29.md
Labels: ignore-for-release-notes

#4869 修复 v2 引擎任务 get_task_detail API 无法获取任务输出的问题
  gcloud/taskflow3/models.py
Labels: type/bug

#4885 节点超时进程日志补充
  gcloud/taskflow3/management/commands/node_timeout_process.py
Labels: ignore-for-release-notes

#4896 bugfix: 在项目纬度下的页面切换业务后，跳转到首页，记住选择的项目
  frontend/desktop/src/components/common/modal/PermissionModal.vue
  frontend/desktop/src/components/layout/NavigatorHeadRight.vue
  frontend/desktop/src/routers/index.js
  frontend/desktop/src/store/modules/project.js
Labels: type/bug

#4886 bamboo-pipeline upgrade to 3.11.1
  requirements.txt
Labels: type/feature
