Repository TencentBlueKing/bk-sops, pull requests merged in 2021-05, with the labels that each got.

#3528 improvement: 节点操作流水逻辑优化
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/OperationFlow.vue
  frontend/desktop/src/store/modules/task.js
Labels: optimization

#3517 feature: 支持一层 lazy 变量引用渲染
  pipeline_web/parser/format.py
  pipeline_web/tests/parser/format/test_format_web_data_to_pipeline.py
Labels: V3.6.X_dev, optimization

#3527 修复节点能否重试/跳过属性设置在后台不生效的问题
  dev_log/dev/homholueng_202104291035.yaml
  pipeline/parser/pipeline_parser.py
Labels: V3.6.X, bug

#3530 improvement: 变量名长度放宽到 50
  dev_log/dev/v_xugzhou_202104301149.yaml
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
Labels: optimization

#3515 improvement: 模板维度执行代理人配置添加说明
  dev_log/dev/v_xugzhou_202104251537.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
Labels: optimization

#3537 bugfix: 集群资源筛选变量过滤条件修改为主机所有属性
  dev_log/dev/waylonshi_202105061610.yaml
  pipeline_plugins/variables/static/variables/cmdb/var_cmdb_resource_allocation.js
  static/variables/cmdb/var_cmdb_resource_allocation.js
Labels: V3.6.X

#3533 bugfix: 修复流程标签无法清空问题
  gcloud/tasktmpl3/resources.py
Labels: V3.6.X

#3534 optimization: 优化 CMDB/JOB 系列插件及集群模块 IP 选择器变量从 CMDB 拉取 IP 时的速度
  dev_log/dev/homholueng_202105061446.yaml
  pipeline_plugins/components/utils/sites/open/utils.py
  pipeline_plugins/tests/components/utils/__init__.py
  pipeline_plugins/tests/components/utils/test_cc_get_ips_info_by_str.py
Labels: V3.6.X, optimization

#3541 minor: 项目名称长度限制修改为192
  gcloud/core/migrations/0021_auto_20210427_1455.py
  gcloud/core/models.py
Labels: V3.6.X

#3432 improvement：对于插件和变量相关接口请求返回为False情况添加统一处理逻辑
  api/utils/request.py
  config/default.py
  dev_log/dev/normal-wls_202103260030.yaml
  gcloud/exceptions.py
  pipeline_plugins/components/query/sites/open/cc.py
  pipeline_plugins/middlewares.py
  pipeline_plugins/tests/components/collections/sites/open/cc_test/update_set_service_status/test_v1_1.py
  pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_set_group_selector.py
  pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_set_module_selector.py
  pipeline_plugins/variables/collections/common.py
  pipeline_plugins/variables/collections/sites/open/cc.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_set_group_selector.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_set_module_selector.py
  pipeline_plugins/variables/query/sites/open/query.py
  pipeline_plugins/variables/utils.py
Labels: V3.6.X_dev, optimization

#3514 minor: 解决未登录情况下非首页地址无法正常跳转登陆弹窗问题
  gcloud/core/views.py
Labels: V3.6.X

#3479 improve: 新建任务时修改资源集群的集群报错问题修复
  frontend/desktop/src/components/common/RenderForm/SetAllocation/index.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
Labels: optimization

#3529 improvement: 创建执行方案校验不通过时显示错误信息
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
Labels: optimization

#3536 feature: create_task API 支持简化变量类型
  dev_log/dev/homholueng_202105061556.yaml
  docs/apidoc/en/create_task.md
  docs/apidoc/zh_hans/create_task.md
  gcloud/apigw/views/create_task.py
  gcloud/taskflow3/models.py
  gcloud/tests/apigw/views/test_create_task.py
Labels: V3.6.X, feature

#3525 V3.6.x develop all node detail backend
  config/default.py
  gcloud/taskflow3/api.py
  gcloud/taskflow3/dispatchers/node.py
  gcloud/taskflow3/dispatchers/task.py
  gcloud/taskflow3/models.py
  gcloud/tests/mock_settings.py
  gcloud/tests/taskflow3/dispatchers/__init__.py
  gcloud/tests/taskflow3/dispatchers/node/__init__.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/__init__.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v1.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_detail_v1.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_detail_v2.py
  gcloud/tests/taskflow3/models/taskflow/test_get_node_detail.py
  requirements.txt
Labels: V3.6.X_dev, feature

#3545 improvement: 勾选执行方案后报错问题修复
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/store/modules/task.js
Labels: optimization

#3473 bugfix: 修复通过 create_task API 创建任务时下拉框等元变量无法展示的问题
  dev_log/dev/homholueng_202104121605.yaml
  gcloud/taskflow3/models.py
Labels: V3.6.X, bug

#3559 bugfix: 部分测试问题修复
  dev_log/dev/waylonshi_202105122009.yaml
  gcloud/core/models.py
  pipeline_plugins/components/collections/sites/open/monitor/alarm_shield/v1_1.py
  pipeline_plugins/components/collections/sites/open/monitor/alarm_shield_strategy/v1_1.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield/test_v1_1.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield_strategy/test_v1_1.py
Labels: V3.6.X

#3560 bugfix: 标准插件统计插件多版本全选中问题修复
  dev_log/dev/v_xugzhou_202105122104.yaml
  frontend/desktop/src/pages/admin/statistics/Atom.vue
Labels: bug

#3558 bugfix: 表格分页后第一条数据编辑取消或删除后显示不正确问题和文本框字体大小问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
Labels: V3.6.X, bug

#3555 bugfix: 修复ip选择器变量已存的静态ip属性和当前ip列表对应属性不匹配问题
  dev_log/3.6.38/fannluo_202105121234.yaml
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
Labels: V3.6.X, bug

#3554 bugfix: 运营数据刷新页面项目列表不可选修复
  frontend/desktop/src/components/layout/Navigation.vue
  frontend/desktop/src/pages/admin/statistics/index.vue
Labels: V3.6.X, bug

#3553 bugfix: 轻应用列表高级搜索筛选修复
  dev_log/dev/fannluo_202105121114.yaml
  frontend/desktop/src/pages/appmaker/index.vue
Labels: V3.6.X, bug

#3566 bugfix: 标准插件统计插件多版本全选中问题修复
  frontend/desktop/src/pages/admin/statistics/Atom.vue
Labels: bug

#3567 minor: V3.6.39 begin
  app.yml
  config/default.py
  dev_log/3.6.39/fannluo_202102231734.yaml
  dev_log/3.6.39/fannluo_202102241908.yaml
  dev_log/3.6.39/fannluo_202103151505.yaml
  dev_log/3.6.39/fannluo_202103221005.yaml
  dev_log/3.6.39/fannluo_202103231717.yaml
  dev_log/3.6.39/fannluo_202104131017.yaml
  dev_log/3.6.39/fannluo_202105121114.yaml
  dev_log/3.6.39/homholueng_202102221034.yaml
  dev_log/3.6.39/homholueng_202103081431.yaml
  dev_log/3.6.39/homholueng_202104211425.yaml
  dev_log/3.6.39/homholueng_202104291035.yaml
  dev_log/3.6.39/homholueng_202105061446.yaml
  dev_log/3.6.39/homholueng_202105061556.yaml
  dev_log/3.6.39/normal-wls_202101311558.yaml
  dev_log/3.6.39/normal-wls_202102011636.yaml
  dev_log/3.6.39/normal-wls_202102031619.yaml
  dev_log/3.6.39/normal-wls_202102191756.yaml
  dev_log/3.6.39/normal-wls_202102201114.yaml
  dev_log/3.6.39/normal-wls_202103150131.yaml
  dev_log/3.6.39/normal-wls_202103161628.yaml
  dev_log/3.6.39/normal-wls_202103161754.yaml
  dev_log/3.6.39/normal-wls_202103191804.yaml
  dev_log/3.6.39/normal-wls_202103191809.yaml
  dev_log/3.6.39/normal-wls_202103291521.yaml
  dev_log/3.6.39/normal-wls_202103291627.yaml
  dev_log/3.6.39/normal-wls_202103301510.yaml
  dev_log/3.6.39/normal-wls_202104201528.yaml
  dev_log/3.6.39/spacesun_202101191158.yaml
  dev_log/3.6.39/v_feifzhao_202012281202.yaml
  dev_log/3.6.39/v_feifzhao_202101281532.yaml
  dev_log/3.6.39/v_feifzhao_202102031203.yaml
  dev_log/3.6.39/v_feifzhao_202103161135.yaml
  dev_log/3.6.39/v_feifzhao_202103251610.yaml
  dev_log/3.6.39/v_xugzhou_202101261635.yaml
  dev_log/3.6.39/v_xugzhou_202102041951.yaml
  dev_log/3.6.39/v_xugzhou_202102191435.yaml
  dev_log/3.6.39/v_xugzhou_202103161506.yaml
  dev_log/3.6.39/v_xugzhou_202103221111.yaml
  dev_log/3.6.39/v_xugzhou_202103221452.yaml
  dev_log/3.6.39/v_xugzhou_202103231541.yaml
  dev_log/3.6.39/v_xugzhou_202103251610.yaml
  dev_log/3.6.39/v_xugzhou_202105122104.yaml
  dev_log/3.6.39/waylonshi_202104262238.yaml
  dev_log/3.6.39/waylonshi_202105061610.yaml
  dev_log/3.6.39/waylonshi_202105122009.yaml
  docs/release.md
  readme.md
  readme_en.md
  version_log/version_logs_md/V3.6.38_2021-04-14.md
  version_log/version_logs_md/V3.6.39_2021-05-13.md
Labels: V3.6.X

#3547 minor: 修复cc_find_host_by_topo接口结果判断问题
  pipeline_plugins/components/query/sites/open/cc.py
Labels: V3.6.X_dev

#3551 improvement: 任务执行页面控制节点支持查看节点详情
  frontend/desktop/src/main.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: V3.6.X_dev, optimization

#3570 feature: 新增节点详情，节点历史异常信息敏感信息屏蔽功能
  dev_log/dev/homholueng_202105171505.yaml
  gcloud/taskflow3/dispatchers/node.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_detail_v2.py
  requirements.txt
Labels: V3.6.X_dev, feature

#2992 feature: 任务启动操作添加基于业务的次数限制及对应设置选项
  dev_log/dev/normal-wls_202011152347.yaml
  env.py
  gcloud/apigw/views/operate_task.py
  gcloud/apigw/views/start_task.py
  gcloud/taskflow3/admin.py
  gcloud/taskflow3/api.py
  gcloud/taskflow3/migrations/0014_auto_task_threshold.py
  gcloud/taskflow3/migrations/0016_merge_20210519_1911.py
  gcloud/taskflow3/models.py
  gcloud/tests/mock.py
  gcloud/tests/mock_settings.py
  gcloud/tests/utils/throttle/__init__.py
  gcloud/tests/utils/throttle/test_check_task_operation_throttle.py
  gcloud/utils/throttle.py
  requirements.txt
Labels: V3.6.X_dev

#3500 优化变量使用场景，变量增加使用说明文档
  dev_log/dev/homholueng_202104191501.yaml
  gcloud/core/resources.py
  pipeline_plugins/variables/collections/common.py
  pipeline_plugins/variables/collections/sites/open/cc.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_set_group_selector.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_set_module_selector.py
Labels: V3.6.X_dev, optimization

#3557 minor: 优化插件 IP 字段填写提示
  pipeline_plugins/components/static/components/atoms/cc/cmdb_add_host_lock/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/cmdb_delete_host_lock/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/host_custom_property_change/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/transfer_host_module/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
  pipeline_plugins/components/static/components/atoms/job/job_fast_push_file.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v1_0_0.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
  pipeline_plugins/components/static/components/atoms/job/local_content_upload/v1_0.js
  pipeline_plugins/components/static/components/atoms/nodeman/create_task/v2_0.js
  pipeline_plugins/components/static/components/atoms/nodeman/plugin_operate/v1_0.js
  static/components/atoms/cc/cmdb_add_host_lock/v1_0.js
  static/components/atoms/cc/cmdb_delete_host_lock/v1_0.js
  static/components/atoms/cc/host_custom_property_change/v1_0.js
  static/components/atoms/cc/transfer_host_module/v1_0.js
  static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
  static/components/atoms/job/all_biz_fast_push_file/v1_0.js
  static/components/atoms/job/fast_execute_script/v1_0.js
  static/components/atoms/job/job_fast_execute_script.js
  static/components/atoms/job/job_fast_push_file.js
  static/components/atoms/job/job_push_local_files/v1_0_0.js
  static/components/atoms/job/job_push_local_files/v2_0.js
  static/components/atoms/job/local_content_upload/v1_0.js
  static/components/atoms/nodeman/create_task/v2_0.js
  static/components/atoms/nodeman/plugin_operate/v1_0.js
Labels: V3.6.X_dev, optimization

#3583 improvement: 流水操作记录操作时间显示不全优化&& 流水操作节点name前端实现
  dev_log/dev/v_xugzhou_202105201531.yaml
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/OperationFlow.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabOperationFlow.vue
Labels: optimization

#3592 bugfix: 测试问题处理
  dev_log/dev/fannluo_202105251038.yaml
  frontend/desktop/src/components/layout/Navigation.vue
  frontend/desktop/src/pages/home/CommonlyUsed.vue
  frontend/desktop/src/pages/task/PeriodicList/BootRecordDialog.vue
Labels: V3.6.X, bug

#3582 improvement: 新建流程模板时没有选择任何节点插件时报错提示优化
  dev_log/3.6.39/v_xugzhou_202105201525.yaml
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.6.X, optimization

#3581 improvement: 周期任务crontab没有重置问题修复
  dev_log/3.6.39/v_xugzhou_202105201522.yaml
  frontend/desktop/src/components/common/Individualization/loopRuleSelect.vue
Labels: V3.6.X, optimization

#3580 improvement: 静态IP选择器动态拓扑搜索框优化
  dev_log/3.6.39/v_xugzhou_202105201455.yaml
  frontend/desktop/src/components/common/RenderForm/IpSelector/IpSearchInput.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/SingleIpSelector.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue
Labels: optimization

#3590 minor： 测试问题修复
  dev_log/dev/waylonshi_202105241749.yaml
  dev_log/dev/waylonshi_202105242013.yaml
  dev_log/dev/waylonshi_202105242059.yaml
  gcloud/core/urls.py
  gcloud/iam_auth/view_interceptors/taskflow.py
  pipeline_plugins/components/static/components/atoms/cc/batch_update_host/v1_0.js
  static/components/atoms/cc/batch_update_host/v1_0.js
  version_log/version_logs_md/V3.6.39_2021-05-13.md
Labels: V3.6.X

#3572 bugfix: 修复删除接口调用返回500问题
  dev_log/dev/waylonshi_202105171705.yaml
  gcloud/core/middlewares.py
Labels: V3.6.X

#3573 bugfix:修复节点管理插件任务无法正常显示任务链接
  dev_log/dev/waylonshi_202105171951.yaml
  env.py
  pipeline_plugins/tests/components/collections/sites/open/nodeman_test/plugin_operate_test/test_nodeman_plugin_operate_v1_0.py
Labels: V3.6.X

#3593 improvement: 下载画布时未获取到移出屏幕外的节点问题修复
  dev_log/3.6.39/v_xugzhou_202105251052.yaml
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
Labels: V3.6.X, optimization

#3589 improvement: 新增执行方案权限异常问题修复
  dev_log/3.6.39/v_xugzhou_202105242005.yaml
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
Labels: V3.6.X, optimization

#3595 improvement: 体验问题修复
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.6.X, optimization

#3599 feature: 新增 时间日期(支持格式自定义) 变量
  dev_log/dev/waylonshi_202105261531.yaml
  pipeline_plugins/variables/collections/common.py
  pipeline_plugins/variables/static/variables/format_support_datetime.js
  static/variables/format_support_datetime.js
Labels: V3.6.X_dev

#3598 improvement: 公共流程不能创建方案问题修复&&克隆流程时添加先保存再设置方案弹框
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/task.js
Labels: V3.6.X, optimization

#3600 improvement: api接口分页优化慢查询，最大支持200条数据
  dev_log/dev/waylonshi_202105261723.yaml
  gcloud/apigw/views/get_functionalization_task_list.py
  gcloud/apigw/views/get_task_list.py
  gcloud/apigw/views/utils.py
  gcloud/taskflow3/models.py
Labels: V3.6.X

#3602 improvement: 公共流程暂时禁用执行方案功能
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
Labels: V3.6.X, optimization

#3601 improvement: 克隆流程保存时同时需要保存执行方案
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: V3.6.X, optimization

#3610 optimization: 添加 django-prometheus
  config/default.py
  gcloud/core/urls.py
  requirements.txt
Labels: V3.6.X_dev, optimization

#3615 minor: LabelViewSet使用allow_or_raise_auth_failed进行鉴权
  gcloud/label/viewsets.py
Labels: V3.6.X_dev

#3603 improvement: 转移主机模块插件模块拓扑树默认收起
  dev_log/dev/waylonshi_202105262036.yaml
  pipeline_plugins/components/collections/sites/open/cc/transfer_host_module/legacy.py
  pipeline_plugins/components/static/components/atoms/cc/cc_transfer_host_module.js
  pipeline_plugins/components/static/components/atoms/cc/transfer_host_module/v1_0.js
  static/components/atoms/cc/cc_transfer_host_module.js
  static/components/atoms/cc/transfer_host_module/v1_0.js
Labels: V3.6.X_dev

#3608 minor: 丰富 JOB 插件 log_outputs 字段的描述
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/execute_task/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/local_content_upload/v1_0.py
Labels: V3.6.X_dev, optimization

#3441 minor: 企业微信发送消息插件增加使用说明
  pipeline_plugins/components/collections/sites/open/wechat_work/wechat_work_send_message/v1_0.py
Labels: V3.6.X_dev, optimization

#3616 feature: mini app list add desktop_url field
  env.py
  gcloud/contrib/appmaker/resources.py
Labels: V3.6.X_dev, feature

#3588 feature: 新增作业平台(JOB)-本地文本框内容上传支持跨业务功能
  dev_log/dev/homholueng_202105241717.yaml
  pipeline_plugins/components/collections/sites/open/job/local_content_upload/v1_0.py
  pipeline_plugins/components/static/components/atoms/job/local_content_upload/v1_0.js
  pipeline_plugins/tests/components/collections/sites/open/job_test/local_content_upload/test_v1_0.py
  static/components/atoms/job/local_content_upload/v1_0.js
Labels: V3.6.X_dev, feature

#3607 feature: 后台增加模板默认偏好流程类型字段
  gcloud/tasktmpl3/migrations/0019_tasktemplate_default_flow_type.py
  gcloud/tasktmpl3/models.py
Labels: V3.6.X_dev, feature

#3586 optimization: batch_request 请求中注入引擎当前节点上下文
  api/utils/request.py
  packages/blueking/component/base.py
Labels: V3.6.X_dev, optimization

#3587 feature: 新增JOB执行作业插件允许部分IP跨业务功能
  dev_log/dev/homholueng_202105241454.yaml
  pipeline_plugins/components/collections/sites/open/job/execute_task/legacy.py
  pipeline_plugins/components/utils/sites/open/utils.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_legacy.py
Labels: V3.6.X_dev, feature
