Repository TencentBlueKing/bk-sops, pull requests merged in 2022-10, with the labels that each got.

#6091 修复子任务流程模版展示&周期子任务查看相关问题
  app_desc.yaml
  gcloud/core/apis/drf/serilaziers/task_template.py
  gcloud/core/apis/drf/viewsets/common_template.py
  gcloud/core/apis/drf/viewsets/task_template.py
  pipeline_plugins/components/collections/subprocess_plugin/converter.py
  pipeline_plugins/tests/components/collections/subprocess_plugin/test_converter.py
Labels: type/bug

#6098 修改job快速分发文件，业务集快速分发文件文案
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_push_file/v1_1.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_1.py
Labels: type/optimization

#6105 release goat alpha2
  app.yml
  app_desc.yaml
  config/default.py
  frontend/desktop/src/components/layout/Navigation.vue
  gcloud/apigw/management/commands/sync_saas_apigw.py
  version_logs_md/V3.25.11_2022-09-22.md
  version_logs_md/V3.25.12_2022-09-26.md
Labels: ignore-for-release-notes

#6110 job系列插件文案优化
  pipeline_plugins/components/query/sites/open/cc.py
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_2.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v2_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v1_0_0.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/local_content_upload/v1_1.js
Labels: type/optimization

#6109 修复独立子任务数据转换过程中pipeline_template_id找不到问题
  pipeline_plugins/components/collections/subprocess_plugin/converter.py
Labels: type/bug

#6113 流程公共信息中添加执行方案相关数据
  gcloud/core/apis/drf/viewsets/common_template.py
  gcloud/core/apis/drf/viewsets/task_template.py
Labels: type/optimization

#6106 bugfix: 权限中心异常时，openapi将不再返回500
  gcloud/iam_auth/intercept.py
Labels: type/bug

#6137 权限中心的报错改为在return_json_response装饰器中捕获
  gcloud/apigw/decorators.py
  gcloud/iam_auth/intercept.py
Labels: type/optimization

#6138 优化任务完成后多次发送回调请求问题
  gcloud/taskflow3/celery/tasks.py
  gcloud/taskflow3/domains/callback.py
Labels: type/optimization

#6139 变量名最大长度调整到50
  pipeline_web/parser/schemas.py
Labels: type/optimization

#6144 minor: version bumps to 3.26.0-beta1
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6182 补充环境部署文档
  docs/install/dev_deploy.md
Labels: type/optimization

#6189 运营数据-流程引用数据去重问题处理
  gcloud/tasktmpl3/models.py
Labels: type/optimization

#6174 修复失败时提取变量的问题
  pipeline_plugins/components/collections/sites/open/job/base.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_2.py
Labels: type/bug

#6195 job 快速执行脚本系列插件添加默认脚本内容
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_2.js
  pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
Labels: type/optimization

#6196 修复独立子任务嵌套时变量勾选渲染报错问题
  pipeline_plugins/components/collections/subprocess_plugin/v1_0_0.py
Labels: type/bug

#6194 任务配置支持对单任务配置节点重试填参
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/taskflow3/models.py
Labels: type/optimization

#6177 流程嵌套支持嵌套层数限制，默认最大为200层
  config/default.py
  env.py
  gcloud/core/apis/drf/viewsets/periodic_task.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  pipeline_web/wrapper.py
Labels: type/optimization

#6198 修复create_and_start_task接口自动失败重试失效问题 #6190
  gcloud/apigw/views/create_and_start_task.py
Labels: type/bug

#6192 后台管理—计划任务接口开发
  gcloud/clocked_task/permissions.py
  gcloud/clocked_task/serializer.py
  gcloud/clocked_task/viewset.py
Labels: type/feature

#6200 minor: job 新插件系列执行账号改为下拉框
  pipeline_plugins/components/query/sites/open/job.py
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_2.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/local_content_upload/v1_1.js
Labels: type/optimization

#6206 运营数据流程&任务面板显示异常问题
  gcloud/taskflow3/models.py
  gcloud/tasktmpl3/models.py
Labels: type/bug

#6214 minor: 执行账号支持可编辑下拉框，账号列表新增筛选条件
  pipeline_plugins/components/query/sites/open/job.py
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_2.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/local_content_upload/v1_1.js
Labels: type/optimization

#6211 minor: 快速执行脚本legacy 版本脚本内容添加默认值
  pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
Labels: type/bug

#6226 job 滚动执行策略添加注释
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_2.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/local_content_upload/v1_1.js
Labels: type/optimization

#6207 输出变量展示重命名之后的变量
  gcloud/taskflow3/domains/dispatchers/node.py
Labels: type/bug

#6205 修复模版标签统计计数不准确问题
  gcloud/label/models.py
Labels: type/bug

#6219 模版标签默认按名称进行排序
  gcloud/label/viewsets.py
  gcloud/utils/models.py
Labels: type/optimization

#6213 下拉框输入不存在选项时支持按回车键选中
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
Labels: type/optimization

#6235 输出变量重命名修改为从pipeline tree 中获取
  gcloud/taskflow3/domains/dispatchers/node.py
Labels: type/bug
