Repository TencentBlueKing/bk-sops, pull requests merged in 2022-02, with the labels that each got.

#5052 minor: release 3.15.0
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.15.0_2022-02-10.md
Labels: ignore-for-release-notes

#5062 bugfix: 插件接口列表返回数据格式前端调整
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#5069 后台支持配置节点自动重试间隔
  gcloud/constants.py
  gcloud/taskflow3/admin.py
  gcloud/taskflow3/domains/auto_retry.py
  gcloud/taskflow3/migrations/0020_autoretrynodestrategy_interval.py
  gcloud/taskflow3/models.py
  gcloud/taskflow3/signals/handlers.py
  gcloud/tests/taskflow3/domains/test_auto_retry.py
  gcloud/tests/taskflow3/signals/handlers/test__dispatch_auto_retry_node_task.py
Labels: ignore-for-release-notes

#5077 页面title&footer统一调整&国际化
  gcloud/conf/sites/community/ver_settings.py
  gcloud/conf/sites/enterprise/ver_settings.py
  gcloud/core/footer/sites/open/footer.py
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/djangojs.mo
  locale/zh_hans/LC_MESSAGES/django.mo
  locale/zh_hans/LC_MESSAGES/django.po
  locale/zh_hans/LC_MESSAGES/djangojs.mo
Labels: type/optimization

#5076 获取标准插件配置项接口返回结构前端调整
  frontend/desktop/src/store/modules/atomForm.js
Labels: type/bug

#5079 minor: 查看子流程更新交互优化
  frontend/desktop/src/pages/template/TemplateList/index.vue
Labels: type/optimization

#5081 develop merge release_bridge
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/store/modules/atomForm.js
Labels: ignore-for-release-notes

#5075 第三方插件默认选中最新版本
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
Labels: type/optimization

#5072 remote_plugin插件v1.0.0失败情况下加载返回数据outputs字段
  pipeline_plugins/components/collections/remote_plugin/v1_0_0.py
  pipeline_plugins/tests/components/collections/remote_plugin/test_plugin.py
Labels: type/optimization

#5082 minor: 表格组件文档补充，方法调用参数优化
  docs/develop/tag_usage_dev.md
  en_docs/develop/tag_usage_dev.md
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
Labels: ignore-for-release-notes

#5056 完善转移主机模块插件描述信息
  pipeline_plugins/components/collections/sites/open/cc/transfer_host_module/v1_0.py
Labels: type/optimization

#5067 节点管理插件操作API修复停止类任务传参错误
  pipeline_plugins/components/collections/sites/open/nodeman/plugin_operate/v1_0.py
Labels: type/bug

#5058 yaml格式流程导入第三方插件变量勾选支持
  gcloud/template_base/domains/schema_converter.py
Labels: type/bug

#5084 minor: start V3.15.1
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.15.1_2022-02-16.md
Labels: ignore-for-release-notes

#5085 Master merge release bridge
  app.yml
  app_desc.yaml
  config/default.py
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
  gcloud/template_base/apis/drf/viewsets/template_scheme.py
  gcloud/template_base/domains/schema_converter.py
  pipeline_plugins/components/collections/remote_plugin/v1_0_0.py
  pipeline_plugins/components/collections/sites/open/cc/transfer_host_module/v1_0.py
  pipeline_plugins/components/collections/sites/open/nodeman/plugin_operate/v1_0.py
  pipeline_plugins/tests/components/collections/remote_plugin/test_plugin.py
  version_logs_md/V3.15.1_2022-02-16.md
  version_logs_md/V3.16.0_2022-02-16.md
Labels: ignore-for-release-notes

#5096 固定footer去除"关注我们"选项
  gcloud/core/footer/sites/open/footer.py
  static/core/images/bk_qr_code.png
Labels: ignore-for-release-notes

#5100 任务流量全量切换到 V2 引擎
  gcloud/core/models.py
  gcloud/tests/apigw/views/test_create_and_start_task.py
  gcloud/tests/apigw/views/test_create_task.py
  gcloud/tests/clocked_task/test_tasks.py
  gcloud/tests/core/models/test_engine_config.py
Labels: type/feature

#5073 feature: v1 引擎节点日志持久化时间支持配置
  config/default.py
  env.py
Labels: type/feature

#5107 drf二期联调问题修改
  gcloud/core/apis/drf/filters.py
  gcloud/core/apis/drf/filtersets.py
  gcloud/core/apis/drf/lookups.py
  gcloud/core/apis/drf/viewsets/appmaker.py
  gcloud/core/apis/drf/viewsets/base.py
  gcloud/core/apis/drf/viewsets/business.py
  gcloud/core/apis/drf/viewsets/common_project.py
  gcloud/core/apis/drf/viewsets/common_template.py
  gcloud/core/apis/drf/viewsets/function_task.py
  gcloud/core/apis/drf/viewsets/label.py
  gcloud/core/apis/drf/viewsets/periodic_task.py
  gcloud/core/apis/drf/viewsets/project.py
  gcloud/core/apis/drf/viewsets/sync_task.py
  gcloud/core/apis/drf/viewsets/task_template.py
  gcloud/core/apis/drf/viewsets/user_project.py
Labels: type/optimization

#5093 运营数据选择超出当前时间范围时占比计算错误问题修复
  frontend/desktop/src/pages/admin/statistics/Percentage.vue
Labels: type/bug

#5106 bugfix: drf1期部分接口支持全量拉取联调
  frontend/desktop/src/components/layout/NavigatorHeadRight.vue
  frontend/desktop/src/pages/admin/statistics/index.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/store/modules/project.js
  frontend/desktop/src/store/modules/template.js
Labels: type/bug

#5103 bugfix: 子流程模板名称获取失败问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug

#5110 minor: start V3.15.2
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.15.2_2022-02-22.md
Labels: ignore-for-release-notes

#5120 feature: drf2期前端联调
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/appmaker/index.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/home/AddCollectionDialog.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
  frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
  frontend/desktop/src/pages/template/TemplateList/ImportYamlTplDialog.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
  frontend/desktop/src/store/modules/appmaker.js
  frontend/desktop/src/store/modules/atomForm.js
  frontend/desktop/src/store/modules/function.js
  frontend/desktop/src/store/modules/periodic.js
  frontend/desktop/src/store/modules/template.js
  frontend/desktop/src/store/modules/templateList.js
Labels: type/feature

#5108 页面国际化补充和文案修改
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: ignore-for-release-notes

#5091 子流程选择执行方案兼容节点不可选的情况
  pipeline_web/preview.py
  pipeline_web/preview_base.py
  pipeline_web/tests/prview/test_preview.py
  pipeline_web/tests/prview/test_preview_base.py
  pipeline_web/tests/wrapper/pipeline_template_web_wrapper/test_unfold_subprocess.py
  pipeline_web/wrapper.py
Labels: type/bug

#5121 bugfix: 新建流程名，任务名时间默认带上时区转换
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#5122 optimization: taskflow default engine version bump to 2
  gcloud/taskflow3/models.py
Labels: type/optimization

#5099 bugfix: 子流程标签筛选失效问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
Labels: type/bug

#5124 修复remote_plugin插件获取outputs报错问题
  pipeline_plugins/components/collections/remote_plugin/v1_0_0.py
Labels: type/bug

#5125 start V3.15.3
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.15.3_2022-02-23.md
Labels: ignore-for-release-notes

#5127 start V3.16.1
  app.yml
  app_desc.yaml
  config/default.py
  gcloud/taskflow3/models.py
  pipeline_plugins/components/collections/remote_plugin/v1_0_0.py
  version_logs_md/V3.15.2_2022-02-22.md
  version_logs_md/V3.15.3_2022-02-23.md
  version_logs_md/V3.16.1_2022-02-24.md
Labels: ignore-for-release-notes

#5132 bugfix: drf1期部分接口支持全量拉取联调
  frontend/desktop/src/components/layout/NavigatorHeadRight.vue
  frontend/desktop/src/pages/admin/statistics/index.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/store/modules/project.js
  frontend/desktop/src/store/modules/template.js
Labels: ignore-for-release-notes

#5134 合并错误问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: ignore-for-release-notes

#5129 plugin_service从插件信息接口获取apigw_name
  plugin_service/plugin_client.py
Labels: type/optimization

#5139 minor: add pipeline module level logger
  config/default.py
Labels: ignore-for-release-notes
