Repository TencentBlueKing/bk-sops, pull requests merged in 2022-12, with the labels that each got.

#6375 监控屏蔽插件指标新增 1分钟平均负载 & 15分钟平均负载
  pipeline_plugins/components/static/components/atoms/monitor/alarm_shield/v1_0.js
  pipeline_plugins/components/static/components/atoms/monitor/alarm_shield/v1_1.js
Labels: type/optimization

#6384 minor: release V3.26.3
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.26.3_2022-12-01.md
Labels: ignore-for-release-notes

#6389 minor: 兼容errorsource为error的msg格式
  frontend/desktop/src/utils/errorNotify.js
Labels: type/bug

#6395 feature: ipv6支持云区域
  gcloud/utils/ip.py
  pipeline_plugins/cmdb_ip_picker/utils.py
  pipeline_plugins/components/collections/sites/open/cc/base.py
  pipeline_plugins/components/collections/sites/open/cc/ipv6_utils.py
  pipeline_plugins/components/collections/sites/open/job/ipv6_base.py
  pipeline_plugins/components/collections/sites/open/nodeman/ip_v6_base.py
  pipeline_plugins/components/utils/sites/open/utils.py
Labels: type/feature

#6406 github ci指定对应ubuntu版本
  .github/workflows/commitlint.yml
  .github/workflows/eslint.yml
  .github/workflows/flake8_and_black.yml
  .github/workflows/unittest.yml
Labels: ignore-for-release-notes

#6404 执行作业插件输入ip校验失败时添加异常信息
  .github/workflows/commitlint.yml
  .github/workflows/eslint.yml
  .github/workflows/flake8_and_black.yml
  .github/workflows/unittest.yml
  pipeline_plugins/components/collections/sites/open/job/execute_task/execute_task_base.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_legacy.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_v1_1.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_v1_2.py
Labels: type/bug

#6401 变量主机属性查询器 & 集群模块IP选择器 支持ipv6
  .github/workflows/commitlint.yml
  .github/workflows/eslint.yml
  .github/workflows/flake8_and_black.yml
  .github/workflows/unittest.yml
  pipeline_plugins/variables/collections/sites/open/cc.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
Labels: type/feature

#6393 修复独立子流程中节点无法统计执行时间问题
  gcloud/core/apis/drf/serilaziers/periodic_task.py
  pipeline_plugins/components/collections/subprocess_plugin/v1_0_0.py
Labels: type/bug

#6386 修复集群模块ip选择器集群名中含all字符导致筛选失效问题
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
Labels: type/bug

#6390 bugfix: ip选择器支持输出host_id&job 全局变量输出host_id
  pipeline_plugins/components/query/sites/open/job.py
Labels: type/bug

#6407 minor: release V3.26.4
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.26.4_2022-12-06.md
Labels: ignore-for-release-notes

#6409 修复ip选择器ipv6输出不支持云区域&动态分组展示问题
  gcloud/utils/cmdb.py
  pipeline_plugins/cmdb_ip_picker/utils.py
  pipeline_plugins/components/utils/sites/open/utils.py
  pipeline_plugins/variables/collections/sites/open/cc.py
Labels: type/bug

#6416 优化JobRepo本地上传时的上传速度
  files/bartenders/job_repo.py
  files/bartenders/utils.py
  files/managers/job_repo.py
  files/tests/managers/test_job_repo.py
Labels: type/optimization

#6423 Ipv6 branch merge master
  app.yml
  app_desc.yaml
  config/default.py
  files/bartenders/job_repo.py
  files/bartenders/utils.py
  files/managers/job_repo.py
  files/tests/managers/test_job_repo.py
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  pipeline_plugins/components/collections/sites/open/job/execute_task/execute_task_base.py
  pipeline_plugins/components/collections/subprocess_plugin/v1_0_0.py
  pipeline_plugins/components/static/components/atoms/monitor/alarm_shield/v1_0.js
  pipeline_plugins/components/static/components/atoms/monitor/alarm_shield/v1_1.js
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_legacy.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_v1_1.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_v1_2.py
  version_logs_md/V3.26.2_2022-11-29.md
  version_logs_md/V3.26.3_2022-12-01.md
  version_logs_md/V3.26.4_2022-12-06.md
Labels: ignore-for-release-notes

#6417 修复ipv6环境下执行作业变量拉取到的ip类型变量为host_id问题
  pipeline_plugins/components/query/sites/open/job.py
  pipeline_plugins/components/utils/sites/open/utils.py
Labels: type/bug

#6418 iam 业务运维权限添加公共流程相关 action
  bksops_iam_migrations/migrations/0015_bk_sops_202212122120.py
  support-files/iam/15_update_biz_operator_actions.json
Labels: type/optimization

#6432 修复独立子流程引用隐藏变量时变量被渲染问题
  pipeline_plugins/components/collections/subprocess_plugin/v1_0_0.py
Labels: type/bug

#6434 minor: release V3.27.0
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.27.0_2022-12-14.md
Labels: ignore-for-release-notes

#6436 修复因克隆流程导致节点执行时间不准的问题
  gcloud/apigw/views/get_task_node_data.py
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: type/bug

#6437 独立子任务带上原流程ID信息
  gcloud/core/apis/drf/serilaziers/taskflow_instance.py
Labels: type/optimization

#6439 minor: bamboo-pipeline bumps to 3.24.2
  requirements.txt
Labels: ignore-for-release-notes

#6442 第三方插件文件上传支持更大文件
  plugin_service/plugin_client.py
Labels: type/optimization

#6452 get_task_node_detail api接口支持 loop 传参
  docs/apidoc/en/get_task_node_detail.md
  docs/apidoc/zh_hans/get_task_node_detail.md
  gcloud/apigw/views/get_task_node_detail.py
  gcloud/tests/apigw/views/test_get_task_node_detail.py
Labels: type/optimization

#6460 minor: release V3.26.5
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.26.5_2022-12-27.md
Labels: ignore-for-release-notes

#6464 feature: 支持用户收藏项目
  gcloud/core/admin.py
  gcloud/core/apis/drf/serilaziers/project.py
  gcloud/core/apis/drf/viewsets/user_project.py
  gcloud/core/migrations/0025_auto_20221227_1502.py
  gcloud/core/models.py
  gcloud/tests/core/models/test_user_favorite_project.py
Labels: type/feature
