Repository TencentBlueKing/bk-sops, pull requests merged in 2022-06, with the labels that each got.

#5657 用户自定义流程表排序配置支持公共流程管理页
  gcloud/resources/urls.py
Labels: type/feature

#5678 optimization: 计划任务添加编辑人、编辑时间、创建时间字段
  gcloud/clocked_task/migrations/0004_auto_20220601_1602.py
  gcloud/clocked_task/models.py
  gcloud/clocked_task/serializer.py
  gcloud/clocked_task/viewset.py
  gcloud/core/apis/drf/serilaziers/periodic_task.py
Labels: type/optimization

#5672 周期任务支持记录执行方案列表&局部更新部分字段
  gcloud/core/apis/drf/serilaziers/periodic_task.py
  gcloud/core/apis/drf/viewsets/periodic_task.py
  gcloud/periodictask/migrations/0010_periodictask_template_scheme_ids.py
  gcloud/periodictask/models.py
Labels: type/feature

#5681 计划任务指定执行方案删除时任务启动报错
  gcloud/clocked_task/serializer.py
  gcloud/clocked_task/tasks.py
  gcloud/core/apis/drf/serilaziers/periodic_task.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
  pipeline_web/preview_base.py
  pipeline_web/tests/prview/test_preview_base.py
Labels: type/optimization

#5684 周期任务支持更新到流程最新状态
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/scss/iconfont.scss
  frontend/desktop/src/store/modules/periodic.js
Labels: type/optimization

#5677 批量更新子流程传参错误修复
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#5683 流程模板为查看模式时不记录tab数
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#5689 minor: release_eagle merge master branch
  app.yml
  app_desc.yaml
  config/default.py
  docs/install/dev_deploy.md
  env.py
  frontend/desktop/src/pages/admin/statistics/Atom.vue
  frontend/desktop/src/pages/admin/statistics/Template.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/template.js
  gcloud/core/apis/drf/serilaziers/template.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/taskflow3/apis/drf/viewsets/engine_v2_node_log.py
  gcloud/taskflow3/domains/dispatchers/task.py
  gcloud/taskflow3/domains/node_log.py
  gcloud/template_base/domains/schema_converter.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_push_file/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/base.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_1.py
  pipeline_plugins/components/query/sites/open/job.py
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_0.js
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_execute_job_plan/test_v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_execute_task/test_legacy.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_push_file/test_v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/fast_execute_task/test_legacy.py
  pipeline_plugins/variables/static/variables/cmdb/var_set_module_ip_selector.js
  requirements.txt
  version_logs_md/V3.20.5_2022-05-17.md
  version_logs_md/V3.21.0_2022-05-18.md
  version_logs_md/V3.21.1_2022-05-18.md
  version_logs_md/V3.21.2_2022-05-18.md
  version_logs_md/V3.21.3_2022-05-19.md
  version_logs_md/V3.21.4_2022-05-24.md
  version_logs_md/V3.21.5_2022-05-26.md
  version_logs_md/V3.21.6_2022-05-27.md
  version_logs_md/V3.22.0_2022-05-30.md
  version_logs_md/V3.23.0_2022-05-31.md
Labels: ignore-for-release-notes

#5691 bugfix: eagle版本联调问题修复
  gcloud/clocked_task/serializer.py
  gcloud/core/apis/drf/viewsets/periodic_task.py
  gcloud/periodictask/models.py
  gcloud/user_custom_config/constants.py
  requirements.txt
Labels: type/bug

#5693 bugfix: 修复 get_user_project_detail 获取 project_id 方式不正确的问题
  gcloud/apigw/views/get_user_project_detail.py
  gcloud/iam_auth/utils.py
Labels: ignore-for-release-notes

#5696 test_create_clocked_task unit test fix
  gcloud/clocked_task/serializer.py
  gcloud/tests/clocked_task/test_clocked_task_api.py
Labels: ignore-for-release-notes

#5700 upgrade apigw-manager to 1.1.1
  requirements.txt
Labels: type/feature

#5703 修复 get_user_project_detail 读取 IAM 结果时使用的 project_id 不正确的问题
  gcloud/apigw/views/get_user_project_detail.py
Labels: type/bug

#5705 修复enable状态周期任务更新报错问题
  gcloud/periodictask/models.py
Labels: type/bug

#5707 周期/计划任务执行方案改为必选
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
Labels: type/optimization

#5727 在 app_desc.yaml 中添加 bk_monitor 配置
  app_desc.yaml
Labels: type/feature

#5697 节点切换后日志滚动加载失效问题修复
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: type/bug

#5702 快速执行脚本legacy版本支持查询显示脚本名称（job 3.5.0.18）
  pipeline_plugins/components/query/sites/open/job.py
  pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
Labels: type/optimization

#5708 修复create_periodic_task接口缺少template_version报错问题
  gcloud/apigw/views/create_periodic_task.py
  gcloud/tests/apigw/views/test_create_periodic_task.py
Labels: type/bug

#5716 job快速执行脚本相关插件接口升级job v3
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_1.py
  pipeline_plugins/components/query/sites/open/job.py
  pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
  pipeline_plugins/tests/components/collections/sites/open/job_test/fast_execute_task/test_legacy.py
Labels: type/optimization

#5709 optimization: get_node_data支持渲染已用了输出变量的未执行节点
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py
Labels: type/optimization

#5725 optimization: 减少流程模板列表返回的不必要字段
  gcloud/core/apis/drf/serilaziers/common_template.py
  gcloud/core/apis/drf/serilaziers/task_template.py
  gcloud/core/apis/drf/viewsets/common_template.py
  gcloud/core/apis/drf/viewsets/task_template.py
Labels: type/optimization

#5711 业务集插件业务集判断条件优化(cmdb v3.10.12+)
  packages/blueking/component/apis/cc.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_push_file/v1_0.py
  pipeline_plugins/components/utils/__init__.py
  pipeline_plugins/components/utils/cc.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_execute_job_plan/test_v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_execute_scripts/__init__.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_execute_scripts/test_legacy.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_push_file/test_v1_0.py
Labels: type/optimization

#5728 流程删除时支持对计划任务/周期任务的引用检查
  gcloud/clocked_task/admin.py
  gcloud/clocked_task/migrations/0005_clockedtask_state.py
  gcloud/clocked_task/models.py
  gcloud/clocked_task/serializer.py
  gcloud/clocked_task/tasks.py
  gcloud/constants.py
  gcloud/template_base/domains/template_manager.py
  gcloud/template_base/models.py
Labels: type/optimization

#5732 egale测试体验问题修复
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/ClockedList/index.vue
  frontend/desktop/src/pages/task/NodePreview.vue
  frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
Labels: type/bug, type/optimization, type/feature

#5731 周期任务/计划任务列表接口添加流程查看权限信息
  gcloud/clocked_task/viewset.py
  gcloud/core/apis/drf/viewsets/periodic_task.py
Labels: type/optimization

#5733 修复流程带有子流程时计划任务创建失败问题
  gcloud/clocked_task/tasks.py
  gcloud/taskflow3/models.py
  gcloud/tests/clocked_task/test_tasks.py
Labels: type/bug

#5735 配置项NODE_CALLBACK_RETRY_TIMES优化
  env.py
Labels: type/optimization

#5722 文本框类型变量正则为空时，再进行正则匹配时失效问题修复
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/bug

#5737 快速执行脚本相关插件优化
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_1.py
  pipeline_plugins/components/query/sites/open/job.py
  pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
  pipeline_plugins/tests/components/collections/sites/open/job_test/fast_execute_task/test_legacy.py
Labels: type/optimization

#5739 blueapps upgrade to 4.4.3
  requirements.txt
Labels: type/feature

#5740 job获取脚本名称列表只返回线上脚本版本
  pipeline_plugins/components/query/sites/open/job.py
Labels: type/optimization

#5741 minor: release 3.23.1
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.23.1_2022-06-16.md
Labels: ignore-for-release-notes

#5745 get_task_status API 缓存过期时间缩短为 10s
  gcloud/apigw/views/get_task_status.py
Labels: type/feature

#5743 更新 get_user_project_detail API 文档
  docs/apidoc/en/get_user_project_detail.md
  docs/apidoc/zh_hans/get_user_project_detail.md
Labels: ignore-for-release-notes

#5749 get_user_project_detail err message fix
  gcloud/apigw/views/get_user_project_detail.py
Labels: ignore-for-release-notes

#5751 优化职能化任务显示时间格式
  gcloud/core/apis/drf/serilaziers/function_task.py
Labels: type/optimization

#5752 职能化时间过滤添加默认执行时间
  frontend/desktop/src/pages/functor/FunctionList.vue
Labels: type/bug

#5753 release_eagle_merge_master
  app.yml
  app_desc.yaml
  config/default.py
  docs/apidoc/en/get_user_project_detail.md
  docs/apidoc/zh_hans/get_user_project_detail.md
  frontend/desktop/src/api/index.js
  frontend/desktop/src/pages/functor/FunctionList.vue
  gcloud/apigw/views/get_task_status.py
  gcloud/apigw/views/get_user_project_detail.py
  gcloud/core/apis/drf/serilaziers/function_task.py
  pipeline_plugins/components/query/sites/open/job.py
  requirements.txt
  version_logs_md/V3.23.1_2022-06-16.md
Labels: ignore-for-release-notes

#5756 minor: release V3.23.2
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.23.2_2022-06-17.md
Labels: ignore-for-release-notes

#5757 添加自动化测试埋点
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
Labels: type/optimization

#5760 optimization: commit lint忽略merge情况
  commitlint.config.js
Labels: ignore-for-release-notes

#5762 修复快速执行脚本脚本执行时不匹配导致的报错问题
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_1.py
Labels: type/bug

#5772 旧版公共周期任务不支持编辑&编辑权限优先级调整
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/task/ClockedList/index.vue
  frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
Labels: type/optimization

#5774 文案提示调整
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
Labels: type/optimization

#5773 跨流程克隆变量过长报错提示&&克隆/新增变量提示优化
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableClone.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
Labels: type/optimization

#5778 optimization: 优化我的动态查询接口拉取速度
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: type/optimization

#5781 minor: release V3.24.1
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.24.1_2022-06-24.md
Labels: ignore-for-release-notes

#5782 修复job插件获取日志失败时节点状态返回错误问题
  pipeline_plugins/components/collections/sites/open/job/base.py
Labels: type/bug

#5783 计划/周期任务添加执行方案被删除逻辑 & 节点配置默认选中最新版本逻辑调整
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#5785 minor: release V3.24.2
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.24.2_2022-06-27.md
Labels: ignore-for-release-notes

#5794 优化我的动态查询接口拉取速度
  gcloud/core/apis/drf/viewsets/taskflow.py
  plugin_service/plugin_client.py
Labels: type/optimization

#5795 create_task新增回调功能
  app_desc.yaml
  config/default.py
  env.py
  gcloud/apigw/views/create_task.py
  gcloud/constants.py
  gcloud/taskflow3/admin.py
  gcloud/taskflow3/celery/settings.py
  gcloud/taskflow3/celery/tasks.py
  gcloud/taskflow3/domains/callback.py
  gcloud/taskflow3/migrations/0022_taskcallbackrecord.py
  gcloud/taskflow3/models.py
  gcloud/taskflow3/signals/handlers.py
  gcloud/tests/taskflow3/tasks/test_task_callback.py
  gcloud/utils/requests.py
  support-files/supervisord.conf
Labels: type/feature
