Repository TencentBlueKing/bk-sops, pull requests merged in 2022-01, with the labels that each got.

#4902 minor: start V3.13.9
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.13.9_2022-01-04.md
Labels: ignore-for-release-notes

#4899 修复网关线条操作面板生成节点位置不正确问题
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
Labels: type/bug

#4898 节点超时控制提示信息位置调整
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
Labels: ignore-for-release-notes

#4906 bugfix: 内置变量需要隐藏部分表单配置项
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
Labels: type/bug

#4912 后台支持配置节点自动重试间隔
  gcloud/constants.py
  gcloud/taskflow3/admin.py
  gcloud/taskflow3/domains/auto_retry.py
  gcloud/taskflow3/migrations/0020_autoretrynodestrategy_interval.py
  gcloud/taskflow3/models.py
  gcloud/taskflow3/signals/handlers.py
  gcloud/tests/taskflow3/domains/test_auto_retry.py
  gcloud/tests/taskflow3/signals/handlers/test__dispatch_auto_retry_node_task.py
Labels: type/feature

#4914 节点日志接口传参调整
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/index.vue
  frontend/desktop/src/store/modules/task.js
Labels: type/bug

#4916 v2版本引擎任务下节点执行记录使用新接口
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: ignore-for-release-notes

#4915 node timeout metrics add labels
  gcloud/taskflow3/celery/tasks.py
  gcloud/taskflow3/management/commands/node_timeout_process.py
  metrics.py
Labels: ignore-for-release-notes

#4920 节点超时进程数据入库前检查链接是否可用
  gcloud/taskflow3/management/commands/node_timeout_process.py
Labels: type/optimization

#4921 minor: release 3.14.1
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.14.1_2022-01-05.md
Labels: ignore-for-release-notes

#4911 add node auto retry related metrics
  gcloud/taskflow3/celery/tasks.py
  metrics.py
Labels: type/optimization

#4925 轻应用执行方案id错误问题修复
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: type/bug

#4934 修复 api/engine_v2/node_log 接口未替换部分信息的问题
  gcloud/taskflow3/apis/drf/viewsets/engine_v2_node_log.py
Labels: type/bug

#4933 修复公共流程编辑时保存无权限提示错误问题
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
Labels: type/bug

#4937 minor: release 3.14.2
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.14.2_2022-01-07.md
Labels: ignore-for-release-notes

#4938 节点超时控制最小时间间隔设置为10s
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/store/modules/template.js
Labels: ignore-for-release-notes

#4935 job插件轮询查询日志逻辑修改为轮询状态
  pipeline_plugins/components/collections/sites/open/job/base.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_push_file/test_v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/push_local_files/test_v2_0.py
Labels: type/optimization

#4939 minor: start V3.13.10
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.13.10_2022-01-09.md
Labels: ignore-for-release-notes

#4905 网关接口start_task增加data返回
  docs/apidoc/en/start_task.md
  docs/apidoc/zh_hans/start_task.md
  gcloud/apigw/views/start_task.py
  gcloud/tests/apigw/views/test_start_task.py
Labels: type/optimization

#4907 cc拓扑相关插件中提示去除 网络 层级
  locale/en/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/djangojs.po
  locale/zh_hans/LC_MESSAGES/django.po
  locale/zh_hans/LC_MESSAGES/djangojs.po
  pipeline_plugins/components/collections/sites/open/cc/create_module/legacy.py
  pipeline_plugins/components/collections/sites/open/cc/transfer_host_module/v1_0.py
  pipeline_plugins/components/collections/sites/open/cc/update_module/v1_0.py
  pipeline_plugins/components/collections/sites/open/cc/update_set/v1_0.py
  pipeline_plugins/components/collections/sites/open/cc/update_set_service_status/v1_0.py
  pipeline_plugins/components/static/components/atoms/cc/create_module/legacy.js
  pipeline_plugins/components/static/components/atoms/cc/transfer_host_module/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/update_module/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/update_set/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/update_set_service_status/v1_0.js
Labels: type/optimization

#4926 子流程节点默认支持自定义输入框变量使用时创建选项
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/feature

#4948 权限中心SDK依赖升级,支持使用API网关调用权限中心
  .github/workflows/unittest.yml
  config/default.py
  env.py
  gcloud/iam_auth/shortcuts.py
  requirements.txt
Labels: type/feature

#4946 添加蓝鲸插件开发URL相关配置
  config/default.py
  env.py
  gcloud/core/context_processors.py
Labels: type/feature

#4917 下拉框默认不支持自定义创建
  pipeline_plugins/variables/collections/common.py
  pipeline_plugins/variables/static/variables/select.js
Labels: type/feature

#4956 minor: update blueapps==3.6.1rc0
  gcloud/core/views.py
  requirements.txt
Labels: ignore-for-release-notes

#4957 minor: start V3.14.3
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.14.3_2022-01-12.md
Labels: ignore-for-release-notes

#4963 修复 ITSM 审批在页面上审批失败的问题
  api/collections/itsm.py
Labels: type/bug

#4961 更新apigw获取资源类api调用文档
  docs/apidoc/en/get_common_template_list.md
  docs/apidoc/en/get_periodic_task_list.md
  docs/apidoc/en/get_task_list.md
  docs/apidoc/en/get_template_list.md
  docs/apidoc/zh_hans/get_common_template_list.md
  docs/apidoc/zh_hans/get_periodic_task_list.md
  docs/apidoc/zh_hans/get_task_list.md
  docs/apidoc/zh_hans/get_template_list.md
Labels: type/optimization

#4968 minor: start V3.14.4
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.14.4_2022-01-13.md
Labels: ignore-for-release-notes

#4978 上报节点超时相关队列worker指标信息
  config/default.py
  gcloud/taskflow3/celery/tasks.py
  gcloud/taskflow3/management/commands/node_timeout_process.py
  metrics.py
Labels: ignore-for-release-notes

#4977 节点配置缺少步骤名称字段保存失败问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug

#4880 更新 Header & Footer
  gcloud/core/api.py
  gcloud/core/footer/sites/open/footer.py
  static/core/images/bk_qr_code.png
Labels: type/optimization

#4950 调整Devops流水线环境变量
  scripts/develop/sites/community/env.sh
Labels: ignore-for-release-notes

#4973 节点管理-插件操作1.0插件支持停止类任务
  pipeline_plugins/components/static/components/atoms/nodeman/plugin_operate/v1_0.js
Labels: type/feature

#4980 minor: start V3.14.5
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.14.5_2022-01-14.md
Labels: ignore-for-release-notes

#4962 feature: 我的收藏接口
  gcloud/core/apis/drf/viewsets/utils.py
  gcloud/iam_auth/resource_helpers/collection_template.py
  gcloud/resources/urls.py
  gcloud/tasktmpl3/apis/drf/filters.py
  gcloud/tasktmpl3/apis/drf/permissions.py
  gcloud/tasktmpl3/apis/drf/serilaziers/collection_template.py
  gcloud/tasktmpl3/apis/drf/viewsets/collection_template.py
Labels: type/feature

#4932 feature: 节点自动重试支持配置等待时间
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/store/modules/template.js
Labels: type/feature

#4982 minor: 收藏模板排序使用的属性字段修改为直接外键字段,增加了category字段的搜索和排序
  gcloud/tasktmpl3/apis/drf/filters.py
  gcloud/tasktmpl3/apis/drf/viewsets/collection_template.py
Labels: ignore-for-release-notes

#4990 优化celery多进程worker下监控上报失败问题
  config/default.py
  requirements.txt
Labels: type/bug

#4991 feature: 项目模板中增加我的收藏功能
  frontend/desktop/builds/webpack.dev.config.js
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/store/modules/templateList.js
Labels: type/feature

#4922 minor: 高级搜索标签表单样式异常修复
  frontend/desktop/src/components/common/advanceSearchForm/index.vue
Labels: type/optimization

#4995 preview_task_tree_with_schemes增加outputs返回
  pipeline_web/preview.py
  pipeline_web/tests/prview/test_preview.py
Labels: ignore-for-release-notes

#4958 optimization: 轻应用绑定有默认执行方案的模板时逻辑调整
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: type/optimization

#4989 修复页面操作节点没有流水记录的问题
  gcloud/contrib/operate_record/core.py
  gcloud/taskflow3/apis/django/api.py
Labels: type/bug

#4945 节点选择面板上增加开发插件跳转链接
  frontend/desktop/src/assets/html/index.html
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
Labels: type/feature

#5006 minor: 取消项目id的必传参数校验
  gcloud/taskflow3/apis/drf/viewsets/preview_task_tree.py
  pipeline_web/preview.py
  pipeline_web/tests/prview/test_preview.py
Labels: ignore-for-release-notes

#5010 添加template_source为project时，project_id的参数校验
  gcloud/taskflow3/apis/drf/viewsets/preview_task_tree.py
Labels: ignore-for-release-notes

#4986 表格tag行支持手动拖拽排序
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
Labels: type/feature

#5008 流程Yaml导出接口增加全量导出支持
  gcloud/template_base/apis/django/api.py
  gcloud/template_base/apis/django/validators.py
Labels: type/optimization

#5001 全局变量快捷隐藏开关关闭面板后状态未保存问题修复
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
Labels: type/bug

#5012 公共流程支持编辑执行方案
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskCreateHeader.vue
Labels: type/optimization

#5015 修复任务参数修改元变量下拉框无法编辑问题
  frontend/desktop/src/pages/task/TaskParamEdit.vue
Labels: type/bug

#5013 minor: 更新容器化环境BK_IAM_SAAS_HOST获取方式
  env_v3.py
Labels: ignore-for-release-notes

#5011 节点管理新建任务插件v3.0支持多云区域IP操作
  pipeline_plugins/components/collections/sites/open/nodeman/create_task/v3_0.py
  pipeline_plugins/components/static/components/atoms/nodeman/create_task/v3_0.js
  pipeline_plugins/tests/components/collections/sites/open/nodeman_test/create_task_test/test_nodeman_v3_create_task.py
Labels: type/feature

#5016 minor: release 3.14.6
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.14.6_2022-01-23.md
Labels: ignore-for-release-notes

#5007 子流程节点支持选择执行方案
  frontend/desktop/src/assets/html/index-dev.html
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/atomForm.js
  frontend/desktop/src/store/modules/task.js
  frontend/desktop/src/store/modules/template.js
Labels: type/feature

#5019 修复创建职能化任务隐藏的元变量获取不到默认值的问题
  frontend/desktop/src/pages/task/TaskParamEdit.vue
Labels: type/bug

#5018 bamboo-pipeline upgrade to 3.14.0
  requirements.txt
Labels: type/feature

#5020 minor: start V3.14.7
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.14.7_2022-01-23.md
Labels: ignore-for-release-notes

#5017 minor: 子流程执行方案请求参数调整
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: ignore-for-release-notes

#4953 feature: 任务列表根据任务类型区分面板
  frontend/desktop/src/components/common/advanceSearchForm/index.vue
  frontend/desktop/src/components/layout/Navigation.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/task/TaskManage.vue
Labels: type/feature

#4952 optimization: 任务执行填参表单界面优化
  frontend/desktop/src/pages/task/TaskParamEdit.vue
Labels: type/optimization

#5025 minor: django upgrade to 2.2.26
  requirements.txt
Labels: ignore-for-release-notes

#5028 修复Lable获取api异常
  gcloud/core/apis/drf/serilaziers/label.py
Labels: type/bug

#5032 子流程节点配置展示未引用变量
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: ignore-for-release-notes

#5036 修复子流程无component字段报错问题
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: ignore-for-release-notes

#5034 公共list处理逻辑支持使用方配置不分页
  gcloud/core/apis/drf/viewsets/base.py
  gcloud/core/apis/drf/viewsets/collection.py
Labels: type/optimization

#5039 release 3.14.8
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.14.8_2022-01-25.md
Labels: ignore-for-release-notes

#5041 修复openapi文档解析错误
  gcloud/label/serilaziers.py
  gcloud/label/viewsets.py
  gcloud/resources/urls.py
  gcloud/tasktmpl3/apis/drf/serilaziers/collection_template.py
Labels: type/bug

#5040 outputs过滤掉执行方案未选中节点中的设置输出的component_inputs变量
  pipeline_web/preview.py
  pipeline_web/tests/prview/test_preview.py
Labels: ignore-for-release-notes

#5038 minor: 子流程选择执行方案tips文案修改
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: ignore-for-release-notes

#5043 drf一期前端联调
  frontend/desktop/src/pages/admin/manage/SourceEdit/index.vue
  frontend/desktop/src/pages/admin/manage/SourceManage/index.vue
  frontend/desktop/src/pages/admin/statistics/index.vue
  frontend/desktop/src/pages/appmaker/AppCard.vue
  frontend/desktop/src/pages/appmaker/index.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/home/AddCollectionDialog.vue
  frontend/desktop/src/pages/home/CommonlyUsed.vue
  frontend/desktop/src/pages/home/MyCollection.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
  frontend/desktop/src/store/index.js
  frontend/desktop/src/store/modules/atomForm.js
  frontend/desktop/src/store/modules/manage.js
  frontend/desktop/src/store/modules/project.js
  frontend/desktop/src/store/modules/template.js
Labels: type/optimization
