Repository TencentBlueKing/bk-sops, pull requests merged in 2022-07, with the labels that each got.

#5798 支持展示第三方插件调度失败时的错误信息
  pipeline_plugins/components/collections/remote_plugin/v1_0_0.py
Labels: type/optimization

#5800 修复职能化任务认领修改参数失败时接口返回成功问题
  gcloud/taskflow3/domains/dispatchers/task.py
  gcloud/taskflow3/models.py
Labels: type/bug

#5804 节点详情 API 支持获取子流程节点输入输出数据
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py
  requirements.txt
Labels: ignore-for-release-notes

#5799 职能化认领传参失效问题修复
  frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
Labels: type/bug

#5803 下拉框表单项粘贴时忽略大小写
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
Labels: type/optimization

#5802 子流程节点更新后取消变量勾选报错问题修复
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug

#5801 集群模块IP选择器切换为ip选择器后报错问题修复
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/bug

#5797 登录时保存模板编辑的数据
  frontend/desktop/src/App.vue
  frontend/desktop/src/api/index.js
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/optimization

#5807 minor: release V3.24.3
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.24.3_2022-07-04.md
Labels: ignore-for-release-notes

#5808 get_functionalization_task_list接口支持project_id过滤
  docs/apidoc/en/get_functionalization_task_list.md
  docs/apidoc/zh_hans/get_functionalization_task_list.md
  gcloud/apigw/forms/get_functionalization_task_list.py
  gcloud/apigw/views/get_functionalization_task_list.py
Labels: type/optimization

#5813 修复节点失败时非activity节点不发送失败信息问题
  gcloud/taskflow3/signals/handlers.py
Labels: type/bug

#5830 minor: 插件开发tag使用文档更新
  docs/develop/tag_usage_dev.md
  en_docs/develop/tag_usage_dev.md
Labels: ignore-for-release-notes

#5826 插件前端请求无权限报错支持直接进行无权限弹框
  api/utils/request.py
  gcloud/iam_auth/utils.py
  pipeline_plugins/components/query/sites/open/cc.py
  pipeline_plugins/components/query/sites/open/itsm.py
  pipeline_plugins/components/query/sites/open/job.py
  pipeline_plugins/components/query/sites/open/monitor.py
  pipeline_plugins/components/query/sites/open/nodeman.py
Labels: type/optimization

#5829 获取用户管理用户信息时用户电话字段不存在情况适配
  gcloud/core/api_adapter/user_info.py
Labels: type/optimization

#5828 修复请求重定向中间件query参数丢失问题
  gcloud/core/middlewares.py
Labels: type/bug

#5822 修复运营数据任务列表时间顺序显示问题
  gcloud/contrib/analysis/analyse_items/task_flow_instance.py
  gcloud/contrib/analysis/analyse_items/task_template.py
  gcloud/taskflow3/models.py
  gcloud/tasktmpl3/models.py
  gcloud/tests/taskflow3/models/taskflow/test_group_by_instance_node.py
Labels: type/bug

#5834 页面重定向配置支持只针对特定HOST
  config/default.py
  env.py
  gcloud/core/middlewares.py
Labels: type/optimization

#5833 资源列表搜索过滤字段支持
  gcloud/clocked_task/viewset.py
  gcloud/core/apis/drf/viewsets/function_task.py
  gcloud/core/apis/drf/viewsets/periodic_task.py
Labels: type/optimization

#5823 统一编辑态下离开页面的弹窗样式
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/index.js
Labels: type/bug, type/optimization

#5824 导入yaml模板文件时切换分页报错问题修复
  frontend/desktop/src/pages/template/TemplateList/ImportYamlTplDialog.vue
Labels: type/bug

#5837 下拉框tag粘贴单个时支持模糊匹配
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
Labels: type/optimization

#5840 任务新建弹框添加重复模板bug修复
  frontend/desktop/src/pages/task/TaskList/TaskCreateDialog.vue
Labels: type/bug

#5841 增加重定向豁免配置
  config/default.py
  env.py
  gcloud/core/middlewares.py
Labels: type/optimization

#5838 编辑模式下静态ip无法操作问题修复
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
Labels: type/bug

#5839 插件和系统报错进行去重展示
  frontend/desktop/src/App.vue
  frontend/desktop/src/utils/errorNotify.js
Labels: type/optimization

#5835 修复流程Yaml导出变量隐藏没有同步问题
  gcloud/template_base/domains/schema_converter.py
Labels: type/bug

#5843 release V3.24.4
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.24.4_2022-07-14.md
Labels: ignore-for-release-notes

#5853 搜索能力整体优化
  frontend/desktop/.babelrc
  frontend/desktop/package.json
  frontend/desktop/src/components/common/TableRenderHeader.vue
  frontend/desktop/src/components/common/searchSelect/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/constants/routes.js
  frontend/desktop/src/pages/appmaker/index.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/commonManage/CommonTplList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/task/ClockedList/index.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateList/CommonTplList.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
Labels: type/optimization

#5844 子流程输出参数配置获取失败问题修复
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#5854 标签页数量监听失效问题修复
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/index.js
Labels: type/bug

#5845 支持原地添加标签
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
  frontend/desktop/src/scss/common.scss
Labels: type/optimization

#5857 将bk_monitor添加到白名单应用中
  gcloud/apigw/constants.py
Labels: type/optimization

#5858 release V3.24.5
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.24.5_2022-07-18.md
Labels: ignore-for-release-notes

#5859 项目管理、任务列表搜索优化
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/core/apis/drf/viewsets/user_project.py
Labels: type/optimization

#5861 修改蓝鲸监控按策略插件v1.2版本字段顺序
  pipeline_plugins/components/static/components/atoms/monitor/alarm_shield_strategy/v1_2.js
Labels: type/optimization

#5862 验收问题修复
  frontend/desktop/src/components/common/searchSelect/index.vue
  frontend/desktop/src/components/common/searchSelect/selectTag.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
Labels: type/bug

#5856 模板克隆和新建模式下，返回逻辑优化调整
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/optimization

#5876 列表接口时间字段筛选支持
  gcloud/clocked_task/viewset.py
  gcloud/core/apis/drf/viewsets/periodic_task.py
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: type/optimization

#5872 修改字段顺序，调整字段文案
  pipeline_plugins/components/static/components/atoms/monitor/alarm_shield_strategy/v1_2.js
Labels: type/bug

#5866 轻应用复制链接调整
  frontend/desktop/src/pages/appmaker/AppCard.vue
Labels: type/optimization

#5868 修复total字段显示不准确的问题
  gcloud/taskflow3/models.py
  gcloud/tasktmpl3/models.py
  gcloud/tests/taskflow3/models/taskflow/test_group_by_instance_node.py
Labels: type/bug

#5880 cmdb_search_dynamic_group接口支持无权限499响应
  pipeline_plugins/cmdb_ip_picker/query.py
Labels: type/optimization

#5887 修复模版详情缺少标签数据问题
  gcloud/core/apis/drf/viewsets/task_template.py
Labels: type/bug

#5883 修复职能化任务列表过滤参数读取问题
  gcloud/apigw/forms/get_functionalization_task_list.py
Labels: type/bug

#5885 foal版本验收问题修复
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/CommonTplList.vue
Labels: type/bug, type/optimization

#5888 模板刷新后没有更新列表问题修复
  frontend/desktop/src/pages/commonManage/CommonTplList.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
Labels: type/optimization

#5892 文档社区课程链接更新
  readme.md
  readme_en.md
Labels: type/optimization

#5894 新增django sessions过期数据自动清理
  config/default.py
  env.py
  env_v2.py
  env_v3.py
  gcloud/core/tasks.py
Labels: type/feature

#5895 登陆豁免时不将时区信息写入session中
  gcloud/core/middlewares.py
Labels: type/optimization

#5896 minor: release V3.24.6
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.24.6_2022-07-29.md
Labels: ignore-for-release-notes

#5898 minor: get_ip_result_by_input_method日志补充
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
Labels: ignore-for-release-notes
