Repository TencentBlueKing/bk-sops, pull requests merged in 2022-05, with the labels that each got.

#5522 导入yaml弹框文案展示优化
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/ImportYamlTplDialog.vue
Labels: type/optimization

#5518 修复集群资源筛选变量保存数据同步更新后还会提示更新的问题
  frontend/desktop/src/components/common/RenderForm/SetAllocation/index.vue
Labels: type/bug

#5526 公共流程管理去掉执行历史
  frontend/desktop/src/pages/commonManage/CommonTplList.vue
Labels: type/optimization

#5473 bugfix: 修复快速执行脚本插件超时时间必填的问题
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
Labels: type/bug

#5474 插件操作执行完成返回了多条任务链接
  pipeline_plugins/components/collections/sites/open/nodeman/plugin_operate/v1_0.py
Labels: type/bug

#5492 第三方插件data api传入bk_ticket
  plugin_service/api.py
  plugin_service/client_decorators.py
  plugin_service/env.py
  plugin_service/plugin_client.py
Labels: type/optimization

#5520 bugfix: 修复子流程节点配置总是使用最新时，source_info 过期导致无法创建任务的问题
  pipeline_web/tests/wrapper/pipeline_template_web_wrapper/test_unfold_subprocess.py
  pipeline_web/wrapper.py
Labels: type/bug

#5529 feature: blueapps upgrade to 4.3.0
  requirements.txt
Labels: type/feature

#5525 修复文本值下拉框远程数据源模式无法使用的问题
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
  gcloud/taskflow3/apis/django/api.py
  gcloud/taskflow3/domains/dispatchers/task.py
  gcloud/taskflow3/models.py
  pipeline_plugins/tests/variables/collections/test_text_value_select.py
  pipeline_plugins/variables/collections/common.py
  pipeline_web/parser/format.py
Labels: type/bug

#5519 修复总是使用最新版本开关取消后没有提示子流程更新问题
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
Labels: type/bug

#5460 optimization: 节点管理新建任务4.0从CC获取主机数据，节点管理侧尝试把不存在的主机尝试从cc同步回来
  gcloud/utils/cmdb.py
  pipeline_plugins/components/collections/sites/open/nodeman/create_task/v4_0.py
  pipeline_plugins/components/static/components/atoms/nodeman/create_task/v4_0.js
  pipeline_plugins/tests/components/collections/sites/open/nodeman_test/create_task_test/test_nodeman_v4_create_task.py
Labels: type/optimization

#5463 新建变量类型IP过滤器
  gcloud/constants.py
  gcloud/utils/ip.py
  pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_ip_filter.py
  pipeline_plugins/variables/collections/sites/open/cc.py
  pipeline_plugins/variables/collections/sites/open/ip_filter_base.py
  pipeline_plugins/variables/static/variables/cmdb/var_cmdb_ip_filter.js
Labels: type/feature

#5533 取消编辑执行方案后清除数据变动状态
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/optimization

#5537 Release cap metrics svr
  app_desc.yaml
  config/default.py
  gcloud/core/middlewares.py
Labels: type/feature

#5538 修复公共流程任务再创建无权限问题
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: type/bug

#5540 minor: update blueapps to 4.4.0
  requirements.txt
Labels: type/feature

#5539 调整新建流程/任务的命名时间戳
  frontend/desktop/src/App.vue
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/store/modules/project.js
Labels: type/optimization

#5541 minor: release cap 回归出包
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.20.0_2022-05-06.md
Labels: ignore-for-release-notes

#5543 修改获取APIGW的后端服务地址的环境变量名
  config/default.py
  env.py
  env_v2.py
  env_v3.py
Labels: type/bug

#5461 取消勾选全局变量时不再直接删除变量
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
Labels: type/optimization

#5462 全局变量切换类型时保留已录入的默认值信息
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/optimization

#5528 下拉框支持一次性筛选出多个选项
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
Labels: type/optimization

#5542 修改获取APIGW的后端服务地址的环境变量名
  config/default.py
  env.py
  env_v2.py
  env_v3.py
Labels: type/bug

#5544 minor: release V3.19.2
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.19.2_2022-05-07.md
Labels: ignore-for-release-notes

#5546 容器化Image包添加同步APIGW命令
  bin/pre_release
Labels: type/bug

#5547 caps回归体验问题修复
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu/SubflowList.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/optimization

#5548 插件操作执行完成返回了多条任务链接
  pipeline_plugins/components/collections/sites/open/nodeman/plugin_operate/v1_0.py
Labels: type/bug

#5549 修复节点配置总是使用最新版本切换后提示更新异常的问题
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
Labels: type/bug

#5551 minor: release V3.19.3
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.19.3_2022-05-07.md
Labels: ignore-for-release-notes

#5558 配置CELERY_SEND_EVENTS只在监控自定义上报开启时打开
  config/default.py
Labels: type/optimization

#5560 bugfix: 修复 JOB 插件超时时间必填的问题
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v2_0.js
  pipeline_plugins/components/static/components/atoms/job/job_fast_push_file.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
Labels: type/bug

#5564 ip过滤器获取supplier_id错误返回supplier_account
  pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_ip_filter.py
  pipeline_plugins/variables/collections/sites/open/ip_filter_base.py
Labels: type/bug

#5567 feature: blueapps upgrade to 4.4.1
  requirements.txt
Labels: type/feature

#5566 修复appmaker删除时PaaS轻应用没有级联删除问题
  gcloud/contrib/appmaker/models.py
Labels: type/bug

#5565 修复周期任务创建后没有自动启动问题
  gcloud/core/apis/drf/viewsets/periodic_task.py
Labels: type/bug

#5562 v2环境配置项BK_SOPS_HOST支持环境变量注入
  env_v2.py
Labels: type/optimization

#5555 编辑轻应用时模板选项添加权限校验
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
Labels: type/optimization

#5569 minor: start V3.19.4
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.19.4_2022-05-10.md
Labels: ignore-for-release-notes

#5568 cc list_service_template调用使用batch_request
  pipeline_plugins/components/query/sites/open/cc.py
  pipeline_plugins/variables/utils.py
Labels: type/optimization

#5570 创建计划任务添加时区显示
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
Labels: type/optimization

#5572 minor: Cap 3.20.1
  app.yml
  app_desc.yaml
  bin/pre_release
  config/default.py
  env_v2.py
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_ip_filter.py
  pipeline_plugins/variables/collections/sites/open/ip_filter_base.py
  version_logs_md/V3.19.2_2022-05-07.md
  version_logs_md/V3.19.3_2022-05-07.md
  version_logs_md/V3.19.4_2022-05-10.md
  version_logs_md/V3.20.1_2022-05-10.md
Labels: ignore-for-release-notes

#5553 Eagle版本前端测试问题修复
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableClone.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
Labels: type/bug

#5574 表单组件描述图标tips层级调整
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
Labels: type/optimization

#5575 新建轻应用的模板列表添加title
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
Labels: type/optimization

#5573 修复公共流程创建周期任务权限校验失败问题
  gcloud/core/apis/drf/viewsets/periodic_task.py
Labels: type/bug

#5578 drf权限校验优化
  gcloud/contrib/operate_record/apis/drf/viewsets/operate_record.py
  gcloud/core/apis/drf/permission.py
  gcloud/core/apis/drf/viewsets/appmaker.py
  gcloud/core/apis/drf/viewsets/common_project.py
  gcloud/core/apis/drf/viewsets/package_source.py
  gcloud/core/apis/drf/viewsets/resource_config.py
  gcloud/core/apis/drf/viewsets/sync_task.py
  gcloud/core/apis/drf/viewsets/user_project.py
Labels: type/optimization

#5545 全局变量中带有系统变量的脏数据处理
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/utils/dealVarDirtyData.js
Labels: type/optimization

#5582 minor: start V3.20.3
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.20.3_2022-05-12.md
Labels: ignore-for-release-notes

#5586 未批量获取执行方案列表，选择执行方案报500
  pipeline_plugins/components/query/sites/open/job.py
Labels: type/bug

#5588 minor: start V3.20.4
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.20.4_2022-05-13.md
Labels: ignore-for-release-notes

#5535 节点日志新增支持远程数据源拉取方式
  config/default.py
  env.py
  gcloud/taskflow3/apis/drf/viewsets/engine_v2_node_log.py
  gcloud/taskflow3/domains/node_log.py
Labels: type/feature

#5592 v2 引擎节点日志增加时间及日志级别
  config/default.py
Labels: type/feature

#5589 任务列表新增执行代理人字段
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: type/optimization

#5587 公共流程增加节点维度的执行代理人设置
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
Labels: type/optimization

#5595 v1 engine 启动任务不再 ping worker
  gcloud/taskflow3/domains/dispatchers/task.py
Labels: type/optimization

#5596 优化集群模块IP选择器的校验逻辑
  pipeline_plugins/variables/static/variables/cmdb/var_set_module_ip_selector.js
Labels: type/optimization

#5563 feature: 增加公共流程管理页面权限判断接口
  gcloud/iam_auth/__init__.py
  gcloud/iam_auth/api.py
  gcloud/iam_auth/shortcuts.py
  gcloud/iam_auth/urls.py
Labels: type/feature

#5594 修复任务列表我的动态过滤失效问题
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: type/bug

#5599 celery exporter 监听端口支持调整
  app_desc.yaml
Labels: type/optimization

#5600 minor: release V3.20.5
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.20.5_2022-05-17.md
Labels: ignore-for-release-notes

#5603 业务集系列 job 插件超时时间校验优化
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_0.js
Labels: type/optimization

#5604 minor: release 3.21.0
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.21.0_2022-05-18.md
Labels: ignore-for-release-notes

#5607 optimization: 管理员入口下模板调整链接跳转
  frontend/desktop/src/pages/admin/statistics/Atom.vue
  frontend/desktop/src/pages/admin/statistics/Template.vue
Labels: type/optimization

#5609 调整 celery exporter 进程名
  app_desc.yaml
Labels: type/optimization

#5610 release 3.21.1
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.21.1_2022-05-18.md
Labels: ignore-for-release-notes

#5611 调整 celery exporter 进程名
  app_desc.yaml
Labels: type/optimization

#5612 minor: release 3.21.2
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.21.2_2022-05-18.md
Labels: ignore-for-release-notes

#5571 后端支持配置节点维度执行代理人
  gcloud/taskflow3/apps.py
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/taskflow3/signals/handlers.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_detail_v2.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_retry_v2.py
  pipeline_web/parser/format.py
  pipeline_web/tests/parser/format/test_format_web_data_to_pipeline.py
  requirements.txt
Labels: type/feature

#5605 添加 get_mini_app_list 和 create_clocked_task 接口
  docs/apidoc/en/create_clocked_task.md
  docs/apidoc/en/get_mini_app_list.md
  docs/apidoc/zh_hans/create_clocked_task.md
  docs/apidoc/zh_hans/get_mini_app_list.md
  gcloud/apigw/urls.py
  gcloud/apigw/views/create_clocked_task.py
  gcloud/apigw/views/get_mini_app_list.py
  gcloud/iam_auth/conf.py
  gcloud/iam_auth/view_interceptors/apigw/create_clocked_task.py
Labels: type/feature

#5606 添加iam权限申请页面上下文
  gcloud/core/context_processors.py
Labels: type/feature

#5616 计划任务通知配置复用流程模版中通知配置
  gcloud/clocked_task/models.py
  gcloud/clocked_task/serializer.py
  gcloud/core/apis/drf/serilaziers/template.py
Labels: type/feature

#5608 项目权限申请页title跳转和跳转链接优化
  frontend/desktop/src/assets/html/index.html
  frontend/desktop/src/components/layout/Navigation.vue
  frontend/desktop/src/components/layout/NotPermissionComponent.vue
  frontend/desktop/src/pages/home/CommonlyUsed.vue
Labels: type/feature

#5585 项目流程高级搜索优化
  frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
  frontend/desktop/src/pages/appmaker/index.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/commonManage/CommonTplList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
Labels: type/optimization

#5583 全局变量体验问题优化
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableClone.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/optimization

#5626 分支网关、条件并行网关支持配置默认分支
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/template.js
Labels: type/feature

#5624 优化超时任务超过数量限制时报错提示
  gcloud/core/apis/drf/viewsets/utils.py
Labels: type/optimization

#5625 job执行作业IP变量传参为空时不进行变量过滤
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/execute_task/execute_task_base.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_v1_1.py
Labels: type/optimization

#5627 周期任务支持更新流程版本
  gcloud/core/apis/drf/serilaziers/periodic_task.py
  gcloud/core/apis/drf/viewsets/periodic_task.py
  gcloud/periodictask/admin.py
  gcloud/periodictask/migrations/0008_auto_20220520_2149.py
  gcloud/periodictask/migrations/0009_sync_periodic_task_creator.py
  gcloud/periodictask/models.py
  gcloud/tests/mock_settings.py
  gcloud/tests/periodictask/models/test_periodic_task.py
Labels: type/feature

#5628 bugfix: 部分 job 脚本相关接口切换回 job v2
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_1.py
  pipeline_plugins/components/query/sites/open/job.py
Labels: type/bug

#5630 django upgrade to 3.2.13
  requirements.txt
Labels: type/optimization

#5629 bugfix: 处理分支网关没有tag字段时yaml导出报错问题
  gcloud/template_base/domains/schema_converter.py
Labels: type/bug

#5631 minor: release 3.21.4
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.21.4_2022-05-24.md
Labels: ignore-for-release-notes

#5620 项目公共流程模板高级搜索优化
  frontend/desktop/src/pages/template/TemplateList/CommonTplList.vue
Labels: type/optimization

#5622 查看模式下跨流程克隆变量按钮样式调整
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
Labels: type/optimization

#5619 进入公共流程管理页添加鉴权
  frontend/desktop/src/pages/commonManage/index.vue
  frontend/desktop/src/store/index.js
Labels: type/feature

#5623 任务执行中途支持修改任务的输入参数
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/store/modules/task.js
Labels: type/feature

#5636 优化任务列表拉取慢查询
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: type/optimization

#5644 开发文档更新
  docs/install/dev_deploy.md
Labels: type/optimization

#5637 任务列表执行代理人字段调整
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: type/optimization

#5638 任务记录页分支网关展示调整
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/optimization

#5642 节点代理执行人禁止多选
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug

#5646 节点日志数据来源切换
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/store/modules/task.js
Labels: type/feature

#5650 任务实例添加执行代理人记录字段
  gcloud/taskflow3/domains/context.py
  gcloud/taskflow3/migrations/0021_auto_20220523_1521.py
  gcloud/taskflow3/models.py
  gcloud/tasktmpl3/domains/constants.py
  gcloud/tests/mock.py
  gcloud/tests/taskflow3/context/task_context/test_task_executor.py
  gcloud/tests/taskflow3/models/taskflow/test_executor_proxy.py
Labels: type/optimization

#5652 流程保存失败时前端逻辑优化
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#5651 节点重试时非输入框表单项修改值无效修复
  frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
Labels: type/bug

#5614 节点配置表单内部事件不生效处理
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug

#5653 job 快速执行脚本插件 legacy 版本切回 job v2 api
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/legacy.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/fast_execute_task/test_legacy.py
Labels: type/bug

#5654 minor: release V3.21.5
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.21.5_2022-05-26.md
Labels: ignore-for-release-notes

#5656 minor: requirements.txt update
  requirements.txt
Labels: ignore-for-release-notes

#5659 指定protobuf依赖版本
  requirements.txt
Labels: ignore-for-release-notes

#5658 修复通知类型旧数据加载失败问题
  gcloud/core/apis/drf/serilaziers/template.py
Labels: type/bug

#5661 minor: release V3.21.6
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.21.6_2022-05-27.md
Labels: ignore-for-release-notes

#5655 公共流程管理TAB添加表头排序设置
  frontend/desktop/src/pages/commonManage/CommonTplList.vue
  frontend/desktop/src/store/modules/project.js
Labels: type/optimization

#5648 添加默认网关分支样式
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/pages/task/TaskExecute/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
Labels: type/optimization

#5635 任务再创建支持重用原有参数
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/scss/common.scss
Labels: type/feature

#5662 节点日志数据来源切换
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/store/modules/task.js
Labels: type/optimization

#5667 optimization: job 业务集插件兼容老版本对业务的调用请求
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_push_file/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/base.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_execute_job_plan/test_v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_execute_task/test_legacy.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_push_file/test_v1_0.py
Labels: type/optimization

#5641 minor: 调整修改任务全局变量接口返回的提示信息
  gcloud/taskflow3/domains/dispatchers/task.py
Labels: type/optimization

#5660 开启非数据库节点日志数据源时取消数据库日志记录
  config/default.py
Labels: type/feature

#5632 minor: app white list add bk_paas
  gcloud/apigw/constants.py
Labels: type/optimization

#5664 流程保存失败时前端不进行处理跳转
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/template.js
Labels: type/bug

#5670 minor: start V3.22.0
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.22.0_2022-05-30.md
Labels: ignore-for-release-notes

#5671 默认分支，不保存对应的条件分支列表
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/ConditionEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/template.js
Labels: type/bug

#5673 新增get_mini_app_list接口
  docs/apidoc/en/get_mini_app_list.md
  docs/apidoc/zh_hans/get_mini_app_list.md
  gcloud/apigw/urls.py
  gcloud/apigw/views/get_mini_app_list.py
  gcloud/iam_auth/conf.py
Labels: type/feature

#5674 feature: pipeline upgrade to 3.19.0
  requirements.txt
Labels: type/feature

#5676 release 3.23.0
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.23.0_2022-05-31.md
Labels: ignore-for-release-notes
