Repository TencentBlueKing/bk-sops, pull requests merged in 2022-04, with the labels that each got.

#5308 未登录时重定向链接支持多请求参数情况
  gcloud/core/views.py
Labels: type/optimization

#5322 feature: add monitor reporter interval config
  config/default.py
  env.py
Labels: type/feature

#5320 变量值预览接口调整为V2引擎实现
  gcloud/tasktmpl3/domains/constants.py
Labels: type/optimization

#5313 修改节点时间时的节点失败动作不触发用户通知
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/taskflow3/models.py
  gcloud/tests/taskflow3/models/taskflow/test_spec_nodes_timer_reset.py
  requirements.txt
Labels: type/optimization

#5328 minor: 全业务系列插件名变更
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_push_file/v1_0.py
  pipeline_plugins/components/static/components/atoms/job/all_biz_execute_job_plan/all_biz_execute_job_plan.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_0.js
Labels: ignore-for-release-notes

#5331 minor: 全业务系列插件名变更
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_push_file/v1_0.py
  pipeline_plugins/components/static/components/atoms/job/all_biz_execute_job_plan/all_biz_execute_job_plan.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_0.js
Labels: ignore-for-release-notes

#5333 minor: release 3.17.1
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.17.1_2022-04-06.md
Labels: ignore-for-release-notes

#5345 优化部分 API 接口的错误处理
  gcloud/apigw/views/get_task_status.py
  gcloud/taskflow3/domains/dispatchers/node.py
Labels: type/optimization

#5346 add miss monitor reporter interval set
  config/default.py
Labels: ignore-for-release-notes

#5349 国际化代码补充
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/djangojs.mo
  locale/en/LC_MESSAGES/djangojs.po
  locale/zh_hans/LC_MESSAGES/django.mo
  pipeline_plugins/components/collections/sites/open/cc/batch_transfer_host_module/v1_0.py
  pipeline_plugins/components/collections/sites/open/cc/transfer_host_module/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/execute_task/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/execute_task/v1_1.py
  pipeline_plugins/components/collections/sites/open/job/fetch_task_log/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v1_0_0.py
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v2_0.py
  pipeline_plugins/components/collections/sites/open/nodeman/create_task/v3_0.py
  pipeline_plugins/components/static/components/atoms/nodeman/create_task/v2_0.js
  pipeline_plugins/components/static/components/atoms/nodeman/create_task/v3_0.js
  pipeline_plugins/variables/collections/common.py
  pipeline_plugins/variables/collections/datatable.py
  pipeline_plugins/variables/collections/sites/open/cc.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_set_group_selector.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_set_module_selector.py
Labels: type/optimization

#5351 minor: release 3.6.11
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.16.11_2022-04-08.md
Labels: ignore-for-release-notes

#5347 插件服务get_plugin_detail_list接口忽略插件地址信息
  plugin_service/api.py
Labels: type/optimization

#5348 快速执行脚本插件1.0&1.1公共脚本列表拉取不再依赖业务id
  pipeline_plugins/components/query/sites/open/job.py
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_1.js
Labels: type/optimization

#5353 bk-monitor-report bump to 1.1.2
  requirements.txt
Labels: type/feature

#5354 optimization: 子流程批量更新支持应用当前执行方案
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/template.js
Labels: type/optimization

#5352 输出变量勾选为全局变量name不显示问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
Labels: type/bug

#5355 bugfix: 公共流程测试问题处理
  frontend/desktop/src/constants/routes.js
  frontend/desktop/src/pages/commonManage/CommonTplList.vue
  frontend/desktop/src/pages/commonManage/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectPanel/plugin.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectPanel/subflow.vue
  frontend/desktop/src/pages/template/TemplateList/CommonTplList.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/routers/index.js
Labels: ignore-for-release-notes

#5338 improvement: 子流程批量更新后保存按钮文案更新
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/optimization

#5350 optimization: 表格右侧更多操作交互优化
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
  frontend/desktop/src/pages/template/common/CommonTemplateList.vue
Labels: type/optimization

#5335 bugfix: 修复集群资源筛选变量必填列为空为校验的问题
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/bug

#5359 Release cap merge master
  app.yml
  app_desc.yaml
  config/default.py
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  requirements.txt
  version_logs_md/V3.17.1_2022-04-06.md
Labels: ignore-for-release-notes

#5360 minor: remove admin templates
  templates/admin/base_site.html
  templates/admin/login.html
Labels: ignore-for-release-notes

#5361 optimization: 前端国际化处理
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
  frontend/desktop/src/scss/common.scss
Labels: type/optimization, ignore-for-release-notes

#5363 minor: 流程列表样式调整
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu/NodeMenu.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu/SubflowList.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectPanel/plugin.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
Labels: ignore-for-release-notes

#5362 bugfix: 批量更新时模板类型取值错误问题修复
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#5372 minor: 国际化补充
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/djangojs.mo
  locale/en/LC_MESSAGES/djangojs.po
  locale/zh_hans/LC_MESSAGES/django.mo
  pipeline_plugins/components/collections/sites/open/cc/batch_transfer_host_module/v1_0.py
  pipeline_plugins/components/collections/sites/open/cc/transfer_host_module/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/execute_task/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/execute_task/v1_1.py
  pipeline_plugins/components/collections/sites/open/job/fetch_task_log/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v1_0_0.py
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v2_0.py
  pipeline_plugins/components/collections/sites/open/nodeman/create_task/v3_0.py
  pipeline_plugins/components/static/components/atoms/nodeman/create_task/v2_0.js
  pipeline_plugins/components/static/components/atoms/nodeman/create_task/v3_0.js
  pipeline_plugins/variables/collections/common.py
  pipeline_plugins/variables/collections/datatable.py
  pipeline_plugins/variables/collections/sites/open/cc.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_set_group_selector.py
  pipeline_plugins/variables/collections/sites/open/cmdb/var_set_module_selector.py
Labels: type/optimization

#5373 optimization: 前端国际化处理
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
  frontend/desktop/src/scss/common.scss
Labels: ignore-for-release-notes

#5374 minor: release V3.17.2
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.17.2_2022-04-11.md
Labels: ignore-for-release-notes

#5383 流程列表支持收藏流程优先展示
  gcloud/core/apis/drf/filtersets.py
  gcloud/core/apis/drf/serilaziers/common_template.py
  gcloud/core/apis/drf/serilaziers/task_template.py
  gcloud/core/apis/drf/viewsets/common_template.py
  gcloud/core/apis/drf/viewsets/task_template.py
  gcloud/core/urls.py
Labels: type/feature

#5384 插件服务get_plugin_detail_list接口忽略插件地址信息
  plugin_service/api.py
Labels: type/optimization

#5387 流程收藏置顶列表接口新增collection_id字段
  gcloud/core/apis/drf/serilaziers/common_template.py
  gcloud/core/apis/drf/serilaziers/task_template.py
  gcloud/core/apis/drf/viewsets/common_template.py
  gcloud/core/apis/drf/viewsets/task_template.py
  gcloud/tasktmpl3/domains/constants.py
Labels: type/optimization

#5388 minor: release V3.17.3
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.17.3_2022-04-13.md
Labels: ignore-for-release-notes

#5391 bk-monitor-report upgrade to 1.2.0
  config/default.py
  env.py
  requirements.txt
Labels: type/feature

#5394 optimization: 流程列表页面收藏流程支持优先展示
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/pages/template/TemplateList/CommonTplList.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
  frontend/desktop/src/scss/iconfont.scss
  frontend/desktop/src/store/modules/templateList.js
Labels: type/optimization

#5398 公共流程置顶收藏接口添加项目下创建权限
  gcloud/core/apis/drf/viewsets/common_template.py
Labels: type/optimization

#5386 update urllib3 and requests
  requirements.txt
Labels: type/optimization

#5399 set_lang接口下线
  gcloud/core/urls.py
  gcloud/core/views.py
Labels: type/optimization

#5404 流程列表排序默认使用流程编辑时间降序
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/user_custom_config/models.py
Labels: type/optimization

#5395 JOB API 全量切换到 V3 版本
  files/managers/nfs.py
  files/managers/upload_module.py
  files/tests/managers/test_nfs.py
  files/tests/managers/test_upload_module.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_push_file/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/base.py
  pipeline_plugins/components/collections/sites/open/job/cron_task/legacy.py
  pipeline_plugins/components/collections/sites/open/job/execute_task/execute_task_base.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_1.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
  pipeline_plugins/components/collections/sites/open/job/local_content_upload/v1_0.py
  pipeline_plugins/components/query/sites/open/job.py
  pipeline_plugins/components/utils/job.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_execute_task/test_legacy.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_push_file/test_v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/cron_task/test_legacy.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_legacy.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_v1_1.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/fast_execute_task/test_legacy.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/local_content_upload/test_v1_0.py
Labels: type/feature

#5406 修复项目流程修改保存报错问题
  gcloud/core/apis/drf/viewsets/task_template.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/iam_auth/utils.py
Labels: type/bug

#5413 第三方插件过滤掉标准运维没有使用权限的插件
  config/default.py
  plugin_service/api.py
  plugin_service/conf.py
  plugin_service/plugin_client.py
Labels: type/feature

#5415 minor: release V3.17.4
  app.yml
  app_desc.yaml
  config/default.py
  requirements.txt
  version_logs_md/V3.17.4_2022-04-19.md
Labels: ignore-for-release-notes

#5419 支持通过环境变量配置 PLUGIN_DISTRIBUTOR_NAME
  config/default.py
  env.py
Labels: type/feature

#5421 optimization: 增加插件服务 PaaS 网关相关请求日志
  config/default.py
  plugin_service/plugin_client.py
Labels: type/optimization

#5418 optimization: 导入yaml操作优化
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/ImportYamlTplDialog.vue
Labels: type/optimization

#5408 optimization: 流程引用了子流程时，权限界面错误修复
  frontend/desktop/src/api/index.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/store/modules/template.js
Labels: type/optimization

#5402 bugfix: 第三方插件描述获取方式调整
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug, type/optimization

#5403 optimization: 公共流程列表支持排序和鉴权
  frontend/desktop/src/pages/commonManage/CommonTplList.vue
  frontend/desktop/src/pages/template/TemplateList/CommonTplList.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
  frontend/desktop/src/store/modules/task.js
Labels: type/optimization

#5422 minor: release V3.17.5
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.17.5_2022-04-19.md
Labels: ignore-for-release-notes

#5414 yaml导入仅引用子流程支持引用公共流程
  gcloud/template_base/apis/django/api.py
  gcloud/template_base/domains/importer.py
Labels: type/feature

#5424 bugfix: 公共流程模板创建任务权限申请逻辑调整
  frontend/desktop/src/pages/template/TemplateList/CommonTplList.vue
Labels: type/bug

#5426 bk-monitor-report upgrade to 1.2.1
  env.py
  requirements.txt
Labels: type/feature

#5429 bugfix: 修复运营数据模板列表模板 ID 返回不正确的问题
  gcloud/tasktmpl3/models.py
Labels: type/bug

#5427 修复ReadWriteSerializerMethodField使用问题
  gcloud/core/apis/drf/serilaziers/common_template.py
  gcloud/core/apis/drf/serilaziers/periodic_task.py
  gcloud/core/apis/drf/serilaziers/task_template.py
  gcloud/core/apis/drf/serilaziers/template.py
  gcloud/core/apis/drf/serilaziers/variable.py
Labels: type/bug

#5428 feature: 流程模板新增查看模式
  frontend/desktop/src/components/common/RenderForm/IpSelector/ConditionItem.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicGroup.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicIp.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagUpload.vue
  frontend/desktop/src/pages/commonManage/CommonTplList.vue
  frontend/desktop/src/pages/task/ClockedList/index.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/NotifyTypeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariablePreviewValue.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabPipelineTreeEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/CommonTplList.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
  frontend/desktop/src/routers/index.js
Labels: type/feature

#5435 导入yaml文件弹框添加权限校验
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/ImportYamlTplDialog.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
Labels: type/optimization

#5438 yaml导入引用场景鉴权逻辑补充
  gcloud/iam_auth/view_interceptors/base_template.py
  gcloud/taskflow3/domains/context.py
  gcloud/template_base/domains/importer.py
Labels: type/bug

#5443 caps版本前端测试问题修复
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/constants/routes.js
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskCreateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/CommonTplList.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
  frontend/desktop/src/routers/index.js
Labels: type/bug

#5444 optimization: 公共流程新增我创建的按钮
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/commonManage/CommonTplList.vue
  frontend/desktop/src/pages/template/TemplateList/CommonTplList.vue
Labels: type/optimization

#5445 体验问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagRadio.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/NotifyTypeConfig.vue
  frontend/desktop/src/pages/template/TemplateList/ImportYamlTplDialog.vue
Labels: type/optimization

#5449 minor: 体验问题修复
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/SubflowUpdateTips.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/ImportYamlTplDialog.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
Labels: type/optimization

#5451 修复任务实例过滤条件支持字段缺失问题
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: type/bug

#5452 optimization: 模板保存后切换到查看状态
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/optimization

#5455 模板保存后切换到查看状态
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
Labels: type/optimization

#5458 minor: start V3.18.0
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.18.0_2022-04-24.md
Labels: ignore-for-release-notes

#5475 minor: release 3.19.0
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.19.0_2022-04-26.md
Labels: ignore-for-release-notes

#5472 执行作业插件拉取全局变量接口异常
  pipeline_plugins/components/query/sites/open/job.py
Labels: type/bug

#5484 minor: release 3.19.1
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.19.1_2022-04-26.md
Labels: type/bug

#5490 修复获取api和callback模块的host报错问题
  env.py
Labels: type/bug

#5494 在v2环境使用环境变量注入host代替服务发现配置
  env.py
  env_v2.py
Labels: type/bug

#5510 v3.18.0前端测试问题修复
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu/SubflowList.vue
  frontend/desktop/src/pages/admin/statistics/Percentage.vue
  frontend/desktop/src/pages/appmaker/AppCard.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectPanel/subflow.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/NotifyTypeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/routers/index.js
  frontend/desktop/src/store/modules/appmaker.js
  frontend/desktop/src/store/modules/project.js
Labels: type/bug, type/optimization

#5517 修复 paas v2环境初始化加载esb公钥报错问题
  gcloud/apigw/apps.py
Labels: type/bug

#5509 远程数据源模式的文本值下拉框无法使用问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
Labels: type/bug

#5521 文本值下拉框远程数据源模式无法使用
  gcloud/taskflow3/apis/django/api.py
  gcloud/taskflow3/domains/dispatchers/task.py
  gcloud/taskflow3/models.py
  pipeline_plugins/tests/variables/collections/test_text_value_select.py
  pipeline_plugins/variables/collections/common.py
  pipeline_web/parser/format.py
Labels: type/bug

#5506 v3.18.0测试问题修复
  gcloud/core/apis/drf/resource_helpers.py
  gcloud/core/apis/drf/serilaziers/common_template.py
  gcloud/core/apis/drf/serilaziers/template.py
  gcloud/core/apis/drf/viewsets/appmaker.py
  gcloud/core/apis/drf/viewsets/function_task.py
  gcloud/core/apis/drf/viewsets/periodic_task.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/core/apis/drf/viewsets/utils.py
  gcloud/template_base/domains/importer.py
  gcloud/template_base/domains/template_manager.py
  gcloud/template_base/models.py
  pipeline_web/wrapper.py
Labels: type/bug

#5523 文本下拉框取值错误问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
Labels: type/optimization
