Repository TencentBlueKing/bk-sops, pull requests merged in 2022-03, with the labels that each got.

#5146 optimization: 公共流程新建任务操作不再关联任务查看操作
  bksops_iam_migrations/migrations/0013_bk_sops_202203010917.py
  support-files/iam/13_update_common_flow_create_task_relate_actions.json
Labels: type/optimization

#5147 minor: release v3.15.5
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.15.5_2022-03-01.md
Labels: ignore-for-release-notes

#5149 Start v3.16.2
  bksops_iam_migrations/migrations/0013_bk_sops_202203010917.py
  config/default.py
  docs/ops/version_update_notes.md
  plugin_service/plugin_client.py
  readme.md
  readme_en.md
  support-files/iam/13_update_common_flow_create_task_relate_actions.json
  version_logs_md/V3.15.2_2022-02-22.md
  version_logs_md/V3.15.4_2022-02-28.md
  version_logs_md/V3.15.5_2022-03-01.md
Labels: ignore-for-release-notes

#5159 minor: start V3.16.2
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.16.2_2022-03-02.md
Labels: ignore-for-release-notes

#5162 计划任务表单显示问题修复
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
Labels: type/bug

#5169 bugfix: 任务未执行节点预览报错参问题修复
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: type/bug

#5167 修复父流程勾选子流程下拉框变量时create_task报错问题
  gcloud/apigw/views/create_task.py
  gcloud/taskflow3/models.py
Labels: type/bug

#5170 minor: start V3.15.6
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.15.6_2022-03-03.md
Labels: ignore-for-release-notes

#5174 minor: start V3.15.7
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.15.7_2022-03-03.md
Labels: ignore-for-release-notes

#5182 修复V3环境轻应用图标修改失败问题
  gcloud/core/api_adapter/app_maker/v3.py
Labels: type/bug

#5176 feature: drf3期开发
  frontend/desktop/src/pages/admin/manage/AdminSearch/SearchResult.vue
  frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/home/MyDynamic.vue
  frontend/desktop/src/pages/task/PeriodicList/BootRecordDialog.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskExecute/index.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/store/modules/admin.js
  frontend/desktop/src/store/modules/audit.js
  frontend/desktop/src/store/modules/task.js
  frontend/desktop/src/store/modules/taskList.js
  frontend/mobile/src/store/modules/component.js
  frontend/mobile/src/store/modules/project.js
  frontend/mobile/src/store/modules/task.js
  frontend/mobile/src/store/modules/taskList.js
  frontend/mobile/src/store/modules/template.js
  frontend/mobile/src/views/home/index.vue
  frontend/mobile/src/views/task/create.vue
  frontend/mobile/src/views/task/list.vue
  frontend/mobile/src/views/template/index.vue
Labels: type/feature

#5183 引擎日志record中默认添加node_id和version字段
  config/default.py
  gcloud/core/logging.py
Labels: type/optimization

#5189 支持在 PaaS V3 上配置回调入口
  env.py
  pipeline_plugins/components/utils/sites/open/utils.py
Labels: type/feature

#5190 minor: 修改BK_APIGW_HOST为BK_IAM_APIGW_HOST
  config/default.py
  env.py
  gcloud/iam_auth/shortcuts.py
Labels: ignore-for-release-notes

#5192 Start v3.16.3
  app.yml
  app_desc.yaml
  config/default.py
  env.py
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/ReuseVarDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
  gcloud/apigw/views/create_task.py
  gcloud/core/api_adapter/app_maker/v3.py
  gcloud/core/logging.py
  gcloud/taskflow3/models.py
  pipeline_plugins/components/utils/sites/open/utils.py
  version_logs_md/V3.15.6_2022-03-03.md
  version_logs_md/V3.15.7_2022-03-03.md
  version_logs_md/V3.16.3_2022-03-07.md
Labels: ignore-for-release-notes

#5198 minor: start V3.16.4
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.16.4_2022-03-08.md
Labels: ignore-for-release-notes

#5201 bugfix: 修复子流程中勾选为输出的全局变量无法编辑的问题
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#5202 bugfix: 修复子流程中勾选为输出的变量在输入参数未引用变量不显示问题
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#5199 修复子流程自定义全局变量设置输出，在父流程中被未引用隐藏的问题
  pipeline_web/preview.py
  pipeline_web/tests/prview/test_preview.py
Labels: type/bug

#5203 minor: start V3.16.5
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.16.5_2022-03-09.md
Labels: ignore-for-release-notes

#5188 优化 JOB 插件超时时间表单的校验逻辑
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v2_0.js
  pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
  pipeline_plugins/components/static/components/atoms/job/job_fast_push_file.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
Labels: type/optimization

#5206 修改子流程节点的输入输出参数和之前逻辑保持一致
  pipeline_web/preview.py
  pipeline_web/tests/prview/test_preview.py
Labels: type/bug

#5200 容器化pipeline模块切换v2引擎后进程资源调整
  app_desc.yaml
Labels: type/optimization

#5224 修复子流程节点输出参数勾选不渲染问题&&子流程单节点更新和批量更新输入输出不一致问题
  pipeline_web/preview.py
  pipeline_web/preview_base.py
  pipeline_web/tests/wrapper/pipeline_template_web_wrapper/test_unfold_subprocess.py
  pipeline_web/wrapper.py
Labels: type/bug

#5228 minor: start V3.16.6
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.16.6_2022-03-11.md
Labels: ignore-for-release-notes

#5240 minor: start V3.16.7
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.16.7_2022-03-14.md
Labels: ignore-for-release-notes

#5239 bugfix: pipeline tree key pattern validation not work
  pipeline_web/parser/schemas.py
  pipeline_web/parser/validator.py
  pipeline_web/tests/parser/test_validator.py
Labels: type/bug

#5243 bugfix: 模板保存时改为put请求方式
  frontend/desktop/src/store/modules/template.js
Labels: type/bug

#5252 bugfix: 修正运营数据单元测试mock数据
  gcloud/tests/analysis_statistics/data_migrate/tasks/test_migrate_instance.py
  gcloud/tests/analysis_statistics/tasks/test_pipeline_archive_statistics_task.py
Labels: type/bug, ignore-for-release-notes

#5257 bugfix: 修复创建任务鉴权错误
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: ignore-for-release-notes

#5255 bugfix: 任务记录接口新增流程相关权限操作返回
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: ignore-for-release-notes

#5258 bugfix: 修复任务删除异常
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: ignore-for-release-notes

#5270 job v3 api 适配业务集特性
  files/managers/job_repo.py
  files/models.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/base.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_execute_job_plan/test_v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/fetch_task_log/test_v1_0.py
Labels: type/feature, ignore-for-release-notes

#5248 bugfix: 自定义变量 key 校验规则调整
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/main.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/ReuseVarDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/bug

#5250 v1引擎进程资源合并
  app_desc.yaml
  support-files/supervisord.conf
Labels: type/optimization

#5260 raven upgrade to 6.4.0
  requirements.txt
Labels: type/optimization

#5275 bugfix: 修复 JOB 业务集适配联调问题
  pipeline_plugins/components/collections/sites/open/job/base.py
Labels: type/bug

#5262 bugfix: drf测试问题修复
  frontend/desktop/src/pages/admin/manage/SourceSync/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectorPanel.vue
  frontend/desktop/src/store/modules/manage.js
Labels: type/bug

#5256 bugfix: 克隆模板保存执行方案报错修复
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/desktop/src/store/modules/template.js
Labels: type/bug

#5292 克隆生成的新任务默认使用 V2 引擎
  gcloud/taskflow3/models.py
Labels: type/feature

#5293 django3及相关依赖升级
  config/default.py
  gcloud/apigw/decorators.py
  gcloud/contrib/admin/migration_api/decorators.py
  gcloud/contrib/appmaker/decorators.py
  gcloud/contrib/operate_record/decorators.py
  gcloud/core/decorators.py
  gcloud/iam_auth/intercept.py
  gcloud/project_constants/apps.py
  gcloud/template_base/apis/django/api.py
  gcloud/utils/decorators.py
  gcloud/utils/strings.py
  packages/bkoauth/decorators.py
  pipeline_web/plugin_management/apps.py
  requirements.txt
  runtime.txt
  weixin/core/decorators.py
Labels: type/feature

#5245 添加批量插入基于项目插件的管理接口
  gcloud/contrib/admin/urls.py
  gcloud/contrib/admin/views/command.py
Labels: type/feature

#5282 支持第三方插件回调状态轮询
  pipeline_plugins/components/collections/remote_plugin/v1_0_0.py
  pipeline_plugins/tests/components/collections/remote_plugin/test_plugin.py
Labels: type/feature

#5195 引擎执行中断自动恢复功能
  gcloud/taskflow3/signals/handlers.py
  requirements.txt
Labels: type/feature

#5291 IP 选择器筛选后勾选全部依然会选中所有 #5268
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
Labels: type/bug

#5294 bugfix: 任务执行时js报错问题修复
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#5234 bugfix: 变量设置为隐藏后还会校验自动隐藏的条件
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/bug

#5299 minor: start 3.16.9
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.16.9_2022-03-25.md
Labels: ignore-for-release-notes

#5274 bugfix: job执行作业插件v1.1版本输出表单没有展示log_outputs字段
  pipeline_plugins/components/collections/sites/open/job/execute_task/v1_1.py
Labels: type/bug

#5301 ip tag support biz set
  pipeline_plugins/components/collections/sites/open/job/base.py
Labels: type/bug

#5300 IP 选择器筛选后勾选全部依然会选中所有 #5268
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
Labels: type/bug

#5302 minor: start 3.16.10
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.16.10_2022-03-25.md
Labels: ignore-for-release-notes

#5306 修复smart市场logo不显示问题
  bk_sops.png
Labels: type/bug

#5307 bugfix: 编辑轻应用logo不更新问题修复
  frontend/desktop/src/pages/appmaker/index.vue
Labels: type/bug

#5309 feature: JOB 插件支持 JOB 业务集版本
  files/managers/base.py
  files/managers/bk_repo.py
  files/managers/job_repo.py
  files/managers/nfs.py
  files/managers/upload_module.py
  files/models.py
  files/tests/managers/test_bk_repo.py
  files/tests/managers/test_job_repo.py
  files/tests/managers/test_nfs.py
  files/tests/managers/test_upload_module.py
  gcloud/constants.py
  gcloud/taskflow3/apis/django/api.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_push_file/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/base.py
  pipeline_plugins/components/collections/sites/open/job/cron_task/legacy.py
  pipeline_plugins/components/collections/sites/open/job/execute_task/execute_task_base.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_1.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/legacy.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
  pipeline_plugins/components/collections/sites/open/job/local_content_upload/v1_0.py
  pipeline_plugins/components/query/sites/open/job.py
  pipeline_plugins/components/static/components/atoms/job/all_biz_execute_job_plan/all_biz_execute_job_plan.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_execute_job_plan/all_biz_execute_job_plan_output.js
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_1.js
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_execute_job_plan/test_v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_execute_task/test_legacy.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_push_file/test_v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/cron_task/test_legacy.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_legacy.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/execute_task/test_v1_1.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/fast_execute_task/test_legacy.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/fetch_task_log/test_v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/local_content_upload/test_v1_0.py
Labels: type/feature

#5311 未执行节点允许跳过问题修复
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: type/bug

#5303 django prometheus metrics add hostname label
  config/default.py
  gcloud/core/middlewares.py
Labels: type/feature

#5315 minor: release V3.17.0
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.17.0_2022-03-29.md
Labels: ignore-for-release-notes

#5261 optimization: 变量输出勾选逻辑优化/勾选icon优化
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
  frontend/desktop/src/scss/iconfont.scss
Labels: type/optimization

#5316 在 V2 引擎任务中，重试面板参数回填逻辑调整 #5263
  frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/feature

#5297 集成Django-test-toolkit
  gcloud/tests/clocked_task/test_clocked_task_api.py
  requirements.txt
Labels: type/feature
