Repository TencentBlueKing/bk-sops, pull requests merged in 2022-09, with the labels that each got.

#6010 创建任务时多个远程数据源只有最后一个remote_data生效问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
Labels: type/bug

#6015 minor: release V3.25.7
  app.yml
  app_desc.yaml
  config/default.py
  scripts/start_new_version.sh
  version_logs_md/V3.25.7_2022-09-08.md
Labels: ignore-for-release-notes

#6003 修复下拉框隐藏变量时，子流程参数异常的问题
  pipeline_web/wrapper.py
Labels: type/bug

#6005 失败的情况下也需要进行ip tag分组
  pipeline_plugins/components/collections/sites/open/job/base.py
Labels: type/bug

#6029 子任务失败后恢复执行完成时父任务对应节点显示为完成状态并继续执行
  gcloud/taskflow3/domains/callback.py
Labels: type/feature

#6030 release goat merge master and develop
  pipeline_plugins/components/collections/sites/open/job/base.py
  pipeline_plugins/variables/collections/sites/open/cc.py
  pipeline_web/wrapper.py
Labels: ignore-for-release-notes

#6022 修复多层子流程嵌套时,itsm 插件审批异常的问题
  pipeline_plugins/components/query/sites/open/itsm.py
Labels: type/bug

#6032 修复任务清理时周期任务执行历史没有同步清理问题
  gcloud/contrib/cleaner/pipeline/bamboo_engine_tasks.py
  gcloud/contrib/cleaner/tasks.py
  gcloud/taskflow3/management/commands/node_timeout_process.py
Labels: type/bug

#6033 minor: release 3.26.0-alpha
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6026 job 系列插件优化
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_1.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_push_file/v1_1.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_2.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_1.py
  pipeline_plugins/components/static/components/atoms/job/all_biz_execute_job_plan/v1_1/all_biz_execute_job_plan_v1_1.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_2.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v2_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
  pipeline_plugins/components/static/components/atoms/job/job_fast_push_file.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v1_0_0.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
  pipeline_plugins/components/static/components/atoms/job/local_content_upload/v1_0.js
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_execute_scripts/test_v1_1.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_fast_push_file/test_v1_1.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/fast_execute_task/test_v1_2.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/test_fast_push_file/test_v2_1.py
Labels: type/optimization

#6036 下拉框组件默认显示勾选icon问题修复
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu/SubflowList.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectPanel/subflow.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableClone.vue
Labels: type/bug

#6051 minor: release V3.25.8
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.25.8_2022-09-19.md
Labels: ignore-for-release-notes

#6057 修复后台管理页面周期任务查看报错问题
  gcloud/core/apis/drf/viewsets/periodic_task.py
Labels: type/bug

#6058 minor: release V3.25.9
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.25.9_2022-09-20.md
Labels: ignore-for-release-notes

#6054 修复独立子任务功能周期任务不生效问题
  gcloud/periodictask/models.py
Labels: type/bug

#6063 swagger ui页面生产环境默认不展示
  config/default.py
  config/urls_custom.py
  env.py
Labels: type/optimization

#6062 权限中心添加业务只读权限快捷方式
  bksops_iam_migrations/migrations/0014_bk_sops_202209211105.py
  support-files/iam/14_add_biz_read_actions.json
Labels: type/feature

#6060 支持页面用户退出功能
  gcloud/core/urls.py
  gcloud/core/views.py
Labels: type/optimization

#6061 子任务不生成对应职能化任务
  gcloud/contrib/function/handlers.py
Labels: type/optimization

#6067 minor: release 3.25.10
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.25.10_2022-09-21.md
Labels: ignore-for-release-notes

#6069 files模块优化
  files/bartenders/base.py
  files/bartenders/bk_repo.py
  files/bartenders/job_repo.py
  files/bartenders/nfs.py
  files/bartenders/upload_module.py
  files/bartenders/utils.py
  files/managers/base.py
  files/managers/job_repo.py
  files/migrations/0005_fileuploadrecord.py
  files/models.py
  pipeline_plugins/components/query/sites/open/file_upload.py
Labels: type/optimization

#6068 checkbox组件支持只有一个可选项并且选项label为空显示默认label
  frontend/desktop/src/components/common/RenderForm/tags/TagCheckbox.vue
Labels: type/feature

#6070 minor: release goat alpha1
  app.yml
  app_desc.yaml
  config/default.py
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu/SubflowList.vue
  frontend/desktop/src/components/layout/Navigation.vue
  frontend/desktop/src/components/layout/NavigatorHeadRight.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/appmaker/index.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectPanel/subflow.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableClone.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
  gcloud/core/apis/drf/viewsets/periodic_task.py
  gcloud/core/urls.py
  gcloud/core/views.py
  version_logs_md/V3.25.10_2022-09-21.md
  version_logs_md/V3.25.8_2022-09-19.md
  version_logs_md/V3.25.9_2022-09-20.md
Labels: ignore-for-release-notes

#6075 minor: release V3.25.11
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.25.11_2022-09-22.md
Labels: ignore-for-release-notes

#6076 添加apigw网关自动发布逻辑
  gcloud/apigw/management/commands/sync_saas_apigw.py
Labels: type/feature

#6082 minor: release V3.25.12
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.25.12_2022-09-26.md
Labels: ignore-for-release-notes

#6078 支持实例审批人配置
  gcloud/iam_auth/resource_api/clocked_task.py
  gcloud/iam_auth/resource_api/common_flow.py
  gcloud/iam_auth/resource_api/flow.py
  gcloud/iam_auth/resource_api/mini_app.py
  gcloud/iam_auth/resource_api/periodic_task.py
  gcloud/iam_auth/resource_api/task.py
Labels: type/optimization
