Repository TencentBlueKing/bk-sops, pull requests merged in 2022-11, with the labels that each got.

#6240 修复周期任务时间修改时任务可能立即执行问题
  gcloud/periodictask/models.py
Labels: type/bug

#6246 修复cc创建集群枚举校验失败的问题
  pipeline_plugins/components/query/sites/open/cc.py
Labels: type/bug

#6248 滚动策略文案新增换行
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_2.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/local_content_upload/v1_1.js
Labels: type/optimization

#6136 标准运维任务管理端支持任务上下文注入
  gcloud/contrib/admin/urls.py
  gcloud/contrib/admin/views/taskflow.py
Labels: type/feature

#6216 任务支持查询节点历史执行时间
  config/default.py
  env.py
  gcloud/analysis_statistics/migrations/0007_taskflowexecutednodestatistics_template_node_id.py
  gcloud/analysis_statistics/models.py
  gcloud/analysis_statistics/tasks.py
  gcloud/core/apis/drf/serilaziers/taskflow_instance.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/periodictask/models.py
  gcloud/taskflow3/models.py
  gcloud/template_base/utils.py
Labels: type/feature

#6233 bamboo pipeline bumps to 3.23.0 & 集成引擎任务管理端
  config/default.py
  config/urls_custom.py
  requirements.txt
Labels: type/feature

#6262 minor: job成功历史新插件调整为仅在重试时展示&详情时有值展示
  pipeline_plugins/components/collections/sites/open/bk/approve/v1_0.py
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_2.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_2.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/local_content_upload/v1_1.js
Labels: type/optimization

#6231 导出流程yaml文件支持带默认分支的条件网关问题修复
  gcloud/template_base/domains/schema_converter.py
Labels: type/bug

#6287 minor: release V3.26.0-beta3
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.26.0_2022-11-10.md
Labels: ignore-for-release-notes

#6296 minor: release V3.26.0-beta4
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.26.0_2022-11-10.md
Labels: ignore-for-release-notes

#6286 django-versionlog bumps to 1.5.0
  requirements.txt
Labels: ignore-for-release-notes

#6302 optimization: 自动排版算法，优化网关嵌套时的大多数情况下的排版效果
  pipeline_web/drawing_new/drawing.py
  pipeline_web/drawing_new/dummy.py
  pipeline_web/drawing_new/position.py
Labels: type/optimization, type/feature

#6305 minor: 修改job ip分组的文案
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/base_service.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/v1_1.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/base_service.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_fast_execute_script/v1_1.py
  pipeline_plugins/components/collections/sites/open/job/execute_task/v1_2.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_2.py
Labels: type/optimization

#6310 minor: 优化自动排版换行逻辑
  pipeline_web/drawing_new/position.py
Labels: type/feature

#6311 3.26.0版本日志修改
  version_logs_md/V3.26.0_2022-11-10.md
Labels: ignore-for-release-notes

#6320 minor: 滚动策略文案修改
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_2.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/local_content_upload/v1_1.js
Labels: ignore-for-release-notes

#6318 修复独立子任务节点判断是否为勾选变量报错问题
  pipeline_plugins/components/collections/subprocess_plugin/v1_0_0.py
Labels: type/bug

#6304 任务操作记录增加参数修改明细
  gcloud/contrib/operate_record/apis/drf/serilaziers/operate_record.py
  gcloud/contrib/operate_record/core.py
  gcloud/contrib/operate_record/helpers.py
  gcloud/contrib/operate_record/migrations/0003_taskoperaterecord_extra_info.py
  gcloud/contrib/operate_record/models.py
  gcloud/contrib/operate_record/signal.py
  gcloud/contrib/operate_record/utils.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/taskflow3/apis/drf/viewsets/update_task_constants.py
Labels: type/optimization

#6335 修复子流程节点 template_node_id 字段注入问题
  gcloud/template_base/utils.py
  pipeline_plugins/components/collections/subprocess_plugin/converter.py
Labels: type/bug

#6327 feature: 新增获取某个节点配置快照的接口
  gcloud/core/apis/drf/serilaziers/taskflow_instance.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/taskflow3/models.py
  gcloud/template_base/utils.py
Labels: type/optimization

#6344 minor: release V3.26.0
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6348 minor: 容器化进程ipv6支持
  app_desc.yaml
  bin/start_web.sh
Labels: ignore-for-release-notes

#6351 任务参数设置支持已使用参数校验
  gcloud/taskflow3/apis/drf/viewsets/update_task_constants.py
  gcloud/taskflow3/domains/dispatchers/task.py
  gcloud/taskflow3/domains/task_constants.py
  gcloud/tests/taskflow3/domains/test_task_constants.py
  requirements.txt
Labels: type/feature

#6359 修复旧模版变量没有need_render字段导致独立子任务节点变量渲染失败问题
  pipeline_plugins/components/collections/subprocess_plugin/v1_0_0.py
Labels: type/bug

#6354 bugfix: 修复监控策略屏蔽插件取值错误的问题
  pipeline_plugins/components/collections/sites/open/monitor/alarm_shield_strategy/v1_1.py
  pipeline_plugins/components/collections/sites/open/monitor/alarm_shield_strategy/v1_2.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield_strategy/test_v1_1.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield_strategy/test_v1_2.py
Labels: type/bug

#6349 optimization: 优化自动排版宽度配置
  pipeline_web/drawing_new/position.py
Labels: type/optimization

#6360 release V3.26.1
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.26.1_2022-11-28.md
Labels: ignore-for-release-notes

#6330 get_task_node_data接口支持展示节点历史执行时间数据
  docs/apidoc/en/get_task_node_data.md
  docs/apidoc/zh_hans/get_task_node_data.md
  gcloud/apigw/views/get_task_node_data.py
Labels: type/feature

#6218 周期任务规则过长时显示报错问题修复
  gcloud/core/apis/drf/serilaziers/periodic_task.py
Labels: type/bug

#6369 minor: release V3.26.2
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.26.2_2022-11-29.md
Labels: ignore-for-release-notes

#6264 插件服务支持根据tag_id获取插件列表
  plugin_service/api.py
  plugin_service/plugin_client.py
  plugin_service/serializers.py
Labels: type/optimization
