Repository TencentBlueKing/bk-sops, pull requests merged in 2022-08, with the labels that each got.

#5901 minor: api文档更新
  docs/apidoc/en/create_task.md
  docs/apidoc/en/preview_task_tree.md
  docs/apidoc/zh_hans/create_task.md
  docs/apidoc/zh_hans/preview_task_tree.md
Labels: ignore-for-release-notes

#5900 django sessions清理任务支持配置cron计划时间
  config/default.py
  env.py
  gcloud/core/tasks.py
Labels: type/optimization

#5906 拉取创建方式列表时，不需要更新任务列表
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: type/bug

#5910 minor: release v3.25.1
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.25.1_2022-08-03.md
Labels: ignore-for-release-notes

#5912 minor: release V3.25.2
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.25.2_2022-08-03.md
Labels: ignore-for-release-notes

#5918 跨流程变量克隆合并冲突错误修复
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
Labels: type/bug

#5919 combine类型的表单显示隐藏方法和普通表单保持统一
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
Labels: type/bug

#5933 bugfix: 修复job脚本online_script_version_id字段缺失时取值报错问题
  pipeline_plugins/components/query/sites/open/job.py
Labels: type/bug

#5930 增加点击连线可以插入节点的交互提示
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
Labels: type/optimization

#5886 画布编辑不合法提示优化
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/utils/validatePipeline.js
Labels: type/optimization

#5931 节点端点连线优化
  frontend/desktop/src/assets/images/endpoint-dragging.png
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/options.js
Labels: type/optimization

#5940 develop解决冲突
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
Labels: ignore-for-release-notes

#5937 新增支持独立子任务功能
  gcloud/core/apis/drf/serilaziers/task_template.py
  gcloud/core/apis/drf/serilaziers/taskflow_instance.py
  gcloud/core/apis/drf/viewsets/task_template.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/taskflow3/admin.py
  gcloud/taskflow3/celery/tasks.py
  gcloud/taskflow3/domains/callback.py
  gcloud/taskflow3/migrations/0023_auto_20220809_2112.py
  gcloud/taskflow3/migrations/0024_taskconfig.py
  gcloud/taskflow3/models.py
  pipeline_plugins/components/collections/subprocess_plugin/__init__.py
  pipeline_plugins/components/collections/subprocess_plugin/converter.py
  pipeline_plugins/components/collections/subprocess_plugin/v1_0_0.py
  pipeline_plugins/tests/components/collections/subprocess_plugin/__init__.py
  pipeline_plugins/tests/components/collections/subprocess_plugin/test_converter.py
Labels: type/feature

#5923 修复运营数据统计时更新逻辑的错误
  gcloud/analysis_statistics/tasks.py
Labels: type/bug

#5942 新增标准运维插件开发最佳实践文档
  docs/develop/dev_plugin_best_practices.md
  readme.md
Labels: type/optimization

#5946 minor: release V3.25.3
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.25.3_2022-08-15.md
Labels: ignore-for-release-notes

#5950 添加pydantic依赖
  gcloud/core/apis/drf/viewsets/component_model.py
  requirements.txt
Labels: ignore-for-release-notes

#5949 我的动态接口查询速度优化
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: type/optimization

#5953 添加根任务信息查询&子任务模版id
  gcloud/core/apis/drf/permission.py
  gcloud/core/apis/drf/serilaziers/taskflow_instance.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/taskflow3/models.py
  pipeline_plugins/components/collections/subprocess_plugin/converter.py
  pipeline_plugins/tests/components/collections/subprocess_plugin/test_converter.py
Labels: type/optimization

#5890 批量更新主机所属业务模块
  pipeline_plugins/components/collections/sites/open/cc/batch_transfer_host_module/v1_1.py
  pipeline_plugins/components/static/components/atoms/cc/batch_transfer_host_module/v1_1.js
  pipeline_plugins/tests/components/collections/sites/open/cc_test/batch_transfer_host_module/test_v1_1.py
Labels: type/feature

#5936 优化节点管理插件操作版本选中与回显逻辑
  pipeline_plugins/components/static/components/atoms/nodeman/plugin_operate/v1_0.js
Labels: type/optimization

#5963 minor: release v3_24_4
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.25.4_2022-08-19.md
Labels: ignore-for-release-notes

#5954 修复子流程后台itsm审批出现系统异常的bug
  pipeline_plugins/components/query/sites/open/itsm.py
Labels: type/bug

#5967 minor: release V3.25.5
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.25.5_2022-08-22.md
Labels: ignore-for-release-notes

#5968 minor: service apm fit & dependency update
  app_desc.yaml
  env.py
  requirements.txt
Labels: type/optimization

#5969 任务节点参数面板调整
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteLog.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/InputParams.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/NodeLog.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/OutputParams.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/scss/iconfont.scss
Labels: type/optimization

#5928 优化job插件报错体验
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_0.js
Labels: type/optimization

#5972 独立子流程失败重试后支持回填outputs到父流程中
  gcloud/taskflow3/domains/callback.py
Labels: type/feature

#5908 新增v2引擎任务数据清理功能
  app_desc.yaml
  config/default.py
  env.py
  gcloud/contrib/cleaner/__init__.py
  gcloud/contrib/cleaner/apps.py
  gcloud/contrib/cleaner/handlers.py
  gcloud/contrib/cleaner/pipeline/__init__.py
  gcloud/contrib/cleaner/pipeline/bamboo_engine_tasks.py
  gcloud/contrib/cleaner/settings.py
  gcloud/contrib/cleaner/signals.py
  gcloud/contrib/cleaner/tasks.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/utils/decorators.py
  support-files/supervisord.conf
Labels: type/feature

#5976 修复子流程节点输出勾选问题
  gcloud/taskflow3/domains/callback.py
  pipeline_plugins/components/collections/subprocess_plugin/v1_0_0.py
Labels: type/bug

#5974 修复我的动态接口添加创建方法过滤条件时报错问题
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: type/bug

#5979 feature: 子流程支持独立子任务
  frontend/desktop/package.json
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/NodeRightIconStatus.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteLog.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/InputParams.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/NodeLog.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/OutputParams.vue
  frontend/desktop/src/pages/task/TaskExecute/FullCodeEditor.vue
  frontend/desktop/src/pages/task/TaskExecute/OperationFlow.vue
  frontend/desktop/src/pages/task/TaskExecute/RetryNode.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/scss/iconfont.scss
  frontend/desktop/src/store/modules/template.js
  gcloud/core/apis/drf/permission.py
  gcloud/core/apis/drf/serilaziers/task_template.py
  gcloud/core/apis/drf/serilaziers/taskflow_instance.py
  gcloud/core/apis/drf/viewsets/component_model.py
  gcloud/core/apis/drf/viewsets/task_template.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/taskflow3/admin.py
  gcloud/taskflow3/celery/tasks.py
  gcloud/taskflow3/domains/callback.py
  gcloud/taskflow3/migrations/0023_auto_20220809_2112.py
  gcloud/taskflow3/migrations/0024_taskconfig.py
  gcloud/taskflow3/models.py
  pipeline_plugins/components/collections/subprocess_plugin/__init__.py
  pipeline_plugins/components/collections/subprocess_plugin/converter.py
  pipeline_plugins/components/collections/subprocess_plugin/v1_0_0.py
  pipeline_plugins/tests/components/collections/subprocess_plugin/__init__.py
  pipeline_plugins/tests/components/collections/subprocess_plugin/test_converter.py
  requirements.txt
Labels: type/feature

#5978 job成功历史只在重试时展示
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_2.js
Labels: type/optimization

#5986 minor: 任务列表默认不过滤独立子任务
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: ignore-for-release-notes

#5987 minor: 任务列表默认不过滤独立子任务
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: ignore-for-release-notes

#5997 修复子任务失败时多次回调父任务问题
  gcloud/taskflow3/domains/callback.py
  gcloud/taskflow3/signals/handlers.py
  pipeline_plugins/components/collections/subprocess_plugin/v1_0_0.py
Labels: type/bug

#6002 修复子任务失败回调时多次重入问题
  gcloud/taskflow3/domains/callback.py
Labels: type/bug
