Repository TencentBlueKing/bk-sops, pull requests merged in 2023-12, with the labels that each got.

#7174 optimization: 优化cc插件转移主机模块不支持云区域的问题
  pipeline_plugins/components/collections/sites/open/cc/transfer_host_module/legacy.py
  pipeline_plugins/components/collections/sites/open/cc/transfer_host_module/v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/cc_test/transfer_host_module/test_v1_0.py
Labels: type/optimization

#7205 任务状态体验问题修复
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: type/optimization

#7204 第三方插件节点详情输入参数解析异常问题修复
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: type/bug

#7208 支持业务插件自由选择业务
  frontend/desktop/src/config/setting.js
Labels: type/optimization

#7197 拖动汇聚网关到连线重叠处，完成汇聚插入
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
Labels: type/optimization

#7210 报错信息支持配置消息助手
  config/default.py
  env.py
  gcloud/core/context_processors.py
Labels: type/feature

#7211 支持用户收藏项目
  gcloud/contrib/collection/models.py
  gcloud/core/apis/drf/serilaziers/project.py
  gcloud/core/apis/drf/viewsets/user_project.py
  gcloud/taskflow3/apis/django/api.py
  gcloud/tests/contrib/collection/test_user_favorite_project.py
Labels: type/feature

#7215 更新 commit lint
  commitlint.config.js
Labels: ignore-for-release-notes

#7216 chore: 更新 commit lint
  commitlint.config.js
Labels: ignore-for-release-notes

#7218 独立子流程暂停/终止报错msg节点名查询异常问题修复
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/optimization

#7217 添加公共流程是否可以选择bizid方法
  frontend/desktop/src/config/setting.js
Labels: type/optimization

#7222 支持内置插件默认版本
  pipeline_plugins/components/collections/sites/open/wechat_work/wechat_work_send_message/v1_0.py
  requirements.txt
Labels: type/feature

#7227 IP选择器体验问题修复
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
Labels: type/optimization

#7225 默认选中插件默认版本
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/optimization

#7223 bugfix: ip选择器全选勾选异常问题修复
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
Labels: type/bug

#7224 节点树计算爆栈问题修复
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7229 内置插件数据加载支持识别公共流程
  pipeline_plugins/components/static/components/atoms/bk/notify/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/batch_delete_set/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/batch_update_host/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/batch_update_set/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/cc_batch_delete_set.js
  pipeline_plugins/components/static/components/atoms/cc/cc_empty_set_hosts.js
  pipeline_plugins/components/static/components/atoms/cc/cc_transfer_host_module.js
  pipeline_plugins/components/static/components/atoms/cc/cc_update_host.js
  pipeline_plugins/components/static/components/atoms/cc/cc_update_module.js
  pipeline_plugins/components/static/components/atoms/cc/cc_update_set.js
  pipeline_plugins/components/static/components/atoms/cc/cc_update_set_service_status.js
  pipeline_plugins/components/static/components/atoms/cc/create_module/legacy.js
  pipeline_plugins/components/static/components/atoms/cc/create_set/legacy.js
  pipeline_plugins/components/static/components/atoms/cc/create_set/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/create_set/v2_0.js
  pipeline_plugins/components/static/components/atoms/cc/create_set_by_template/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/empty_set_hosts/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/transfer_host_module/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/update_module/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/update_set/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/update_set_service_status/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_2.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_2.js
  pipeline_plugins/components/static/components/atoms/job/job_cron_task.js
  pipeline_plugins/components/static/components/atoms/job/job_execute_task.js
  pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
  pipeline_plugins/components/static/components/atoms/monitor/alarm_shield/v1_0.js
  pipeline_plugins/components/static/components/atoms/monitor/alarm_shield/v1_1.js
  pipeline_plugins/components/static/components/atoms/monitor/alarm_shield/v1_2.js
  pipeline_plugins/variables/static/variables/cmdb/var_cmdb_ip_selector.js
  pipeline_plugins/variables/static/variables/cmdb/var_cmdb_resource_allocation.js
  pipeline_plugins/variables/static/variables/cmdb/var_ip_picker.js
  pipeline_plugins/variables/static/variables/staff_group_multi_selector.js
Labels: type/feature

#7230 任务状态联调问题修复
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
Labels: type/optimization

#7231 批量删除流程报错信息-删除失败数点击后搜索异常问题修复
  frontend/desktop/src/pages/commonManage/CommonTplList.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
Labels: type/bug

#7119 任务数据清理添加特定类型数据清理逻辑
  config/default.py
  env.py
  gcloud/contrib/cleaner/tasks.py
Labels: type/optimization

#7236 任务列表等待处理状态icon调整
  frontend/desktop/src/mixins/task.js
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/scss/task.scss
Labels: type/optimization

#7235 任务执行结束时间过滤传参错误问题修复
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: type/bug

#7246 运营数据-业务框小屏展示异常修复&&统计列表添加取消上次请求逻辑
  frontend/desktop/src/components/layout/ProjectSelector.vue
  frontend/desktop/src/pages/admin/statistics/Appmaker.vue
  frontend/desktop/src/pages/admin/statistics/Atom.vue
  frontend/desktop/src/pages/admin/statistics/Instance.vue
  frontend/desktop/src/pages/admin/statistics/Percentage.vue
  frontend/desktop/src/pages/admin/statistics/Template.vue
  frontend/desktop/src/pages/home/CommonlyUsed.vue
  frontend/desktop/src/pages/home/index.vue
  frontend/desktop/src/store/modules/admin.js
Labels: type/bug, type/optimization

#7245 任务状态体验问题修复
  frontend/desktop/src/components/common/TableRenderHeader.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteRecord.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: type/bug

#7247 任务状态体验问题修复
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/NodeRightIconStatus.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteRecord.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/scss/iconfont.scss
Labels: type/optimization

#7248 更换icon&&任务详情中画布连线取消hover效果
  frontend/desktop/src/components/common/TemplateCanvas/ToolPanel/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/mixins/task.js
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/scss/task.scss
Labels: type/optimization

#7251 修改节点操作【确认】按钮文案
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: type/optimization

#7252 任务暂停时进行节点操作后取消线上暂停样式&&再次执行添加hover
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: type/bug, type/optimization

#7249 节点审批逻辑调整优化
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7259 fix: 任务状态分支合入hb分支后功能冲突问题修复
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/mixins/lineSuspendState.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7241 优化部分任务报错信息
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/taskflow3/domains/node_timeout_strategy.py
  gcloud/taskflow3/signals/handlers.py
  gcloud/tests/taskflow3/domains/test_node_timeout_strategy.py
  pipeline_plugins/components/collections/subprocess_plugin/v1_0_0.py
Labels: type/optimization

#7262 hb测试验收问题修复
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/components/layout/ProjectSelector.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/mixins/task.js
  frontend/desktop/src/pages/home/MyCollection.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/scss/iconfont.scss
  frontend/desktop/src/scss/task.scss
  frontend/desktop/src/store/index.js
Labels: type/bug

#7263 节点树爆栈修复
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7266 fix: 子流程节点审批传参错误修复
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7265 子流程节点更新时，表单项采用【手动创建】方式创建的变量配置更新异常问题修复
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug

#7264 fix: 节点详情交互优化&&强制失败确认框文案修改
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug, type/optimization
