Repository TencentBlueKing/bk-sops, pull requests merged in 2023-05, with the labels that each got.

#6723 修复任务完成时重复发送通知问题
  gcloud/taskflow3/signals/handlers.py
Labels: type/bug

#6725 修复任务完成时重复发送通知问题
  gcloud/taskflow3/signals/handlers.py
Labels: type/bug

#6728 minor: release V3.28.7
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6727 修复 Yaml 导出带默认分支网关报错问题
  gcloud/template_base/domains/schema_converter.py
Labels: type/bug

#6734 任务id长度调整为10位数字
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: type/optimization

#6741 minor: release V3.28.8
  .pre-commit-config.yaml
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6737 重试问题优化
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/index.vue
Labels: type/optimization

#6742 任务重试体验问题修复
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectPanel/plugin.vue
  frontend/desktop/src/store/modules/atomForm.js
Labels: type/bug, type/optimization

#6743 button按钮添加tips不生效问题修复
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
Labels: type/optimization

#6744 修改任务参数时-暂停后需要更新rootState状态
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
Labels: type/bug

#6746 节点详情侧栏无法展示审批按钮问题修复
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: type/bug

#6747 集群资源筛选变量$emit和$refs多了个字符问题修复
  frontend/desktop/src/components/common/RenderForm/SetAllocation/index.vue
Labels: type/bug

#6755 新版非独立子流程任务节点配置快照优化
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/optimization

#6754 职能化任务创建测试问题修复
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskCreate/index.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: type/optimization

#6757 职能化任务支持转化成普通任务并直接执行
  gcloud/core/apis/drf/serilaziers/taskflow.py
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: type/optimization

#6759 流程tab下创建职能化任务是步骤条优化
  frontend/desktop/src/pages/task/TaskCreate/index.vue
Labels: type/optimization

#6760 节点失败处理测试问题修复
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
Labels: type/bug, type/optimization

#6761 新建任务时-查看是否开启失败处理id传参应为-1
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
Labels: type/bug

#6762 修复创建独立子流程节点时部分失败配置未同步问题
  pipeline_plugins/components/collections/subprocess_plugin/converter.py
Labels: type/bug

#6764 项目规范体验问题修复&&节点失败后跳过状态异常问题修改
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
Labels: type/optimization

#6767 任务列表搜索条件和表格列名称对应
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
Labels: type/optimization

#6769 国际化英文翻译调整
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
Labels: type/optimization

#6770 国际化英文翻译调整
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
Labels: type/optimization
