Repository TencentBlueKing/bk-sops, pull requests merged in 2023-10, with the labels that each got.

#7106 任务列表过滤 sql 语句优化
  gcloud/apigw/views/get_task_list.py
  gcloud/core/apis/drf/viewsets/function_task.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/iam_auth/resource_api/task.py
Labels: type/optimization

#7108 变量禁止删除提示文案统一
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
Labels: type/optimization

#7116 minor: version bumps to 3.30.2
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7121 minor: release V3.28.15
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7124 验收会问题修复
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagCodeEditor.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteRecord.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableCitedList.vue
  frontend/desktop/src/scss/iconfont.scss
Labels: type/bug, type/optimization

#7125 添加自定义属性&&优化任务节点详情拖拽宽度
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/optimization

#7127 输出参数hover触发热区优化
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
Labels: type/optimization

#7128 Release v3.31.0 beta
  app.yml
  app_desc.yaml
  config/default.py
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
  gcloud/apigw/views/get_task_list.py
  gcloud/apigw/views/node_callback.py
  gcloud/core/apis/drf/viewsets/function_task.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/iam_auth/resource_api/task.py
  pipeline_plugins/components/collections/sites/open/job/all_biz_execute_job_plan/base_service.py
  pipeline_plugins/components/collections/sites/open/job/execute_task/execute_task_base.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_2.py
  pipeline_plugins/components/collections/sites/open/job/local_content_upload/base_service.py
  pipeline_plugins/components/collections/sites/open/job/push_local_files/v2_1.py
  pipeline_plugins/components/utils/common.py
  pipeline_plugins/tests/components/collections/sites/open/job_test/all_biz_execute_job_plan/test_v1_0.py
Labels: ignore-for-release-notes

#7132 禁用画布工具栏点击展开节点菜单侧栏&&画布选中态样式调整
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/BranchGateway.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ConditionalParallelGateway.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ConvergeGateway.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ParallelGateway.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
Labels: type/optimization

#7129 新增job本地文件上传文件名空格校验
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v1_0_0.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_1.js
Labels: type/optimization

#7139 minor: release V3.31.0
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.31.0_2023-09-21.md
  version_logs_md_en/V3.31.0_2023-09-21.md
Labels: ignore-for-release-notes

#7141 optimization: 优化cc插件转移主机模块不支持云区域的问题
  pipeline_plugins/components/collections/sites/open/cc/transfer_host_module/legacy.py
  pipeline_plugins/components/collections/sites/open/cc/transfer_host_module/v1_0.py
  pipeline_plugins/tests/components/collections/sites/open/cc_test/transfer_host_module/test_v1_0.py
Labels: type/optimization

#7138 独立子流程支持暂停和终止
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/optimization, stage/for_developing

#7137 列表页只在表格内滚动
  frontend/desktop/src/pages/admin/statistics/Appmaker.vue
  frontend/desktop/src/pages/admin/statistics/Atom.vue
  frontend/desktop/src/pages/admin/statistics/Instance.vue
  frontend/desktop/src/pages/admin/statistics/Template.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/commonManage/CommonTplList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/home/MyDynamic.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/ClockedList/index.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateList/CommonTplList.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
Labels: type/optimization

#7148 审批接口传参错误修复
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7150 minor: release 3.31.1
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes
