Repository TencentBlueKing/bk-sops, pull requests merged in 2023-04, with the labels that each got.

#6680 支持动态计算参数显示隐藏
  gcloud/tasktmpl3/apis/django/api.py
  gcloud/tasktmpl3/domains/constants.py
  gcloud/tasktmpl3/urls.py
  gcloud/tests/tasktmpl3/domains/constants/test_preview_task_referenced_constants.py
  pipeline_web/graph.py
  pipeline_web/preview_base.py
  pipeline_web/tests/graph.py
  requirements.txt
Labels: type/feature

#6681 apigw权限中心无权限报错保持原有返回
  app.yml
  app_desc.yaml
  config/default.py
  gcloud/apigw/decorators.py
Labels: type/bug

#6679 画布缩放后拖入节点位置位置修正
  frontend/desktop/src/assets/js/flow.js
Labels: type/optimization

#6493 optimization: 下拉框组件右侧icon调整
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
Labels: type/optimization

#6683 bugfix: 修复job快速分发文件插件目标主机在跨业务场景下失败的问题
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/v1_0.py
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
Labels: type/bug

#6685 修复集群模块ip选择器老数据不兼容问题
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
Labels: type/bug

#6687 新增条件网关下全部活动节点取消时自动关联删除网关
  gcloud/tasktmpl3/apis/django/api.py
  gcloud/tasktmpl3/domains/constants.py
  pipeline_web/graph.py
  pipeline_web/preview_base.py
  pipeline_web/tests/graph.py
Labels: type/feature

#6696 minor: 后端国际化补充
  gcloud/mako_template_helper/base.py
  gcloud/mako_template_helper/hub.py
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/djangojs.mo
  locale/en/LC_MESSAGES/djangojs.po
  locale/zh_hans/LC_MESSAGES/django.mo
  locale/zh_hans/LC_MESSAGES/django.po
  locale/zh_hans/LC_MESSAGES/djangojs.mo
  locale/zh_hans/LC_MESSAGES/djangojs.po
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_2.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/local_content_upload/v1_1.js
  pipeline_plugins/variables/static/variables/cmdb/var_cmdb_ip_filter.js
Labels: type/optimization

#6697 网关级联勾选联调问题修复
  gcloud/tasktmpl3/apis/django/api.py
  gcloud/tasktmpl3/urls.py
Labels: type/bug

#6700 minor: release V3.28.5
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6710 国际化问题修复
  gcloud/mako_template_helper/base.py
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/djangojs.mo
  locale/en/LC_MESSAGES/djangojs.po
  locale/zh_hans/LC_MESSAGES/django.mo
  locale/zh_hans/LC_MESSAGES/django.po
  locale/zh_hans/LC_MESSAGES/djangojs.mo
  locale/zh_hans/LC_MESSAGES/djangojs.po
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_push_file/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_2.js
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_1.js
  pipeline_plugins/components/static/components/atoms/job/local_content_upload/v1_1.js
Labels: type/bug

#6571 下拉框远程数据源url支持参数填写
  pipeline_plugins/variables/static/variables/select.js
Labels: type/bug

#6546 节点输出支持复用输出变量
  pipeline_web/parser/format.py
Labels: type/feature

#6526 get_task_status 接口支持返回失败节点信息
  gcloud/apigw/docs/apigw-docs.tgz
  gcloud/apigw/views/get_task_status.py
  gcloud/taskflow3/utils.py
  gcloud/tests/taskflow3/test_utils.py
Labels: type/feature

#6491 执行作业插件v1.2参数加载不添加双引号
  pipeline_plugins/components/collections/sites/open/job/execute_task/v1_2.py
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_2.js
Labels: type/optimization

#6489 feature: 新增新版定时插件
  pipeline_plugins/components/collections/controller.py
  pipeline_plugins/components/collections/sites/open/bk/timer/__init__.py
  pipeline_plugins/components/collections/sites/open/bk/timer/base.py
  pipeline_plugins/components/collections/sites/open/bk/timer/v1_0.py
  pipeline_plugins/components/static/components/atoms/bk/timer/v1_0.js
Labels: type/feature

#6716 修复 gsekit 插件 query 未同步问题
  pipeline_plugins/components/query/sites/open/gsekit.py
  pipeline_plugins/components/query/sites/open/query.py
Labels: type/bug

#6717 release V3.28.6
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6719 国际化英文翻译优化
  frontend/desktop/src/components/common/TableSettingContent.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
Labels: type/optimization
