Repository TencentBlueKing/bk-sops, pull requests merged in 2023-07, with the labels that each got.

#6849 任务列表-在已有数据基础做筛选、搜索时，loading优化
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: type/optimization

#6852 变量描述填写展示优化
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/optimization

#6855 创建任务选择节，节点预览时执行方案侧栏收起优化
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: type/optimization

#6854 更新子流程节点后，旧表单勾选变量无法取消勾选问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug

#6861 heron版本验收优化项处理
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug, type/optimization

#6862 回退subprocess_info的修改
  gcloud/core/apis/drf/serilaziers/task_template.py
Labels: type/optimization

#6864 作业平台相关插件代码编辑框添加 variable_render 选项
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/all_biz_fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/fast_execute_script/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
Labels: type/optimization

#6866 develop分支变量设置、交互优化自测问题修复
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#6867 周期/计划任务执行方案展示问题处理
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/InputParams.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
Labels: type/bug

#6874 修复任务列表日期显示异常的问题
  gcloud/core/apis/drf/serilaziers/taskflow_instance.py
Labels: type/bug

#6878 任务列表获取状态逻辑优化&&导入临时方案-描述优化
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/TemplateCanvas/ToolPanel/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/mixins/task.js
  frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
  frontend/desktop/src/pages/audit/AuditList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/home/MyDynamic.vue
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteRecord.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/optimization

#6882 minor: 优化监控插件报错信息&补充插件描述国际化
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
  pipeline_plugins/components/collections/sites/open/monitor/alarm_shield/v1_2.py
  pipeline_plugins/components/collections/sites/open/monitor/base.py
  pipeline_plugins/components/collections/sites/open/nodeman/plugin_operate/v2_0.py
Labels: type/optimization

#6881 fix: 修复画布用鼠标滚轮放大后拖入节点位置不正确的问题
  frontend/desktop/src/assets/js/flow.js
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
Labels: type/bug

#6883 更换导出当前节点选择方案图标
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/TemplateCanvas/ToolPanel/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/scss/iconfont.scss
Labels: type/optimization

#6885 Ctrl加鼠标滚轮画布放大，逻辑计算优化
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: type/optimization

#6853 任务列表支持暂停&失败状态过滤
  config/default.py
  env.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/tests/core/apis/drf/views_set/test_task_instance_view.py
Labels: type/optimization

#6887 minor: release V3.29.0-alpha1
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6891 支持任务running状态过滤&补充单元测试
  env.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/core/context_processors.py
  gcloud/tests/core/apis/drf/views_set/test_task_instance_view.py
Labels: type/optimization

#6895 创建周期任务不选择执行方案未渲染任务参数问题修复
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: type/bug, type/optimization

#6898 集群资源筛选函数名错误修复
  frontend/desktop/src/components/common/RenderForm/SetAllocation/index.vue
Labels: type/bug

#6896 含有默认分支的网关节点，copy后缺少默认分支问题修复
  frontend/desktop/src/store/modules/template.js
Labels: type/bug

#6917 支持用户应用屏蔽功能
  gcloud/core/views.py
  packages/blueking/component/apis/bk_login.py
  requirements.txt
Labels: type/feature

#6918 增加用户登录时 csrftoken 更新逻辑
  gcloud/core/views.py
Labels: type/optimization

#6886 重新执行时默认选中上次任务选择的节点
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: type/optimization

#6897 子流程搜索不支持特殊字符问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectPanel/subflow.vue
Labels: type/bug

#6909 ajax请求失败报错国际化问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTree.vue
Labels: type/bug

#6797 修复第三方插件日志获取异常的问题依赖Paas版本v1.1.0-beta.38
  plugin_service/api.py
  plugin_service/plugin_client.py
Labels: type/bug

#6919 流程执行方案支持更新操作
  gcloud/template_base/apis/drf/serilaziers/template_scheme.py
Labels: type/optimization

#6921 创建任务时执行方案样式优化
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: type/optimization

#6926 minor: release V3.29.0_beta2
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.29.0-alpha_2023-07-04.md
  version_logs_md/V3.29.0_2023-07-04.md
Labels: ignore-for-release-notes

#6906 覆盖IamPermission实现，修复远程插件包更新无权限的问题
  gcloud/core/apis/drf/viewsets/package_source.py
Labels: type/bug

#6905 覆盖IamPermission实现，修复远程插件包更新无权限的问题
  gcloud/core/apis/drf/viewsets/package_source.py
Labels: type/bug

#6931 执行方案操作添加权限校验
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#6932 release V3.26.14
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.26.14_2023-07-20.md
Labels: ignore-for-release-notes

#6934 执行方案操作添加权限校验
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
Labels: type/optimization

#6937 minor: release V3.28.14
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6936 修复执行方案鉴权问题
  gcloud/contrib/admin/views/command.py
  gcloud/template_base/apis/drf/permission.py
  gcloud/template_base/apis/drf/viewsets/template_scheme.py
Labels: type/bug

#6938 release hearon beta2
  app.yml
  app_desc.yaml
  config/default.py
  gcloud/core/views.py
  packages/blueking/component/apis/bk_login.py
  requirements.txt
Labels: ignore-for-release-notes

#6939 样式调整
  frontend/desktop/src/components/common/searchSelect/index.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableClone.vue
Labels: type/optimization

#6941 minor: release V3.29.0
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6922 变量联想细节优化&& 免渲染优化
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagCodeEditor.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
Labels: type/optimization

#6942 节点失败处理-自动跳过/手动跳过冲突问题修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
Labels: type/bug

#6943 周期任务-任务名hover热区问题优化
  frontend/desktop/src/pages/task/PeriodicList/index.vue
Labels: type/optimization

#6944 重新执行时默认选中上次任务选择的节点
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: type/optimization

#6945 节点配置combine表单类型支持显示参数名
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
Labels: type/optimization

#6946 系统变量&项目变量禁用变量输出勾选
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
Labels: type/optimization

#6947 模板编辑时切换业务/导航触发二次确认弹框，选择【留在此页】需切换回原选项
  frontend/desktop/src/components/layout/Navigation.vue
  frontend/desktop/src/components/layout/ProjectSelector.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/optimization

#6948 input类型配置时支持变量联想
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
Labels: type/feature

#6949 变量免渲染优化
  docs/develop/tag_usage_dev.md
  en_docs/develop/tag_usage_dev.md
  frontend/desktop/src/components/common/FullCodeEditor.vue
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/formMixins.js
  frontend/desktop/src/components/common/RenderForm/tags/TagCodeEditor.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
Labels: type/optimization

#6952 minor: 3.29.0 版本日志更新
  version_logs_md/V3.29.0_2023-07-04.md
  version_logs_md_en/V3.29.0_2023-07-04.md
Labels: ignore-for-release-notes

#6953 bugfix: 修复快速执行脚本插件国际化问题
  pipeline_plugins/components/static/components/atoms/job/job_fast_execute_script.js
Labels: type/bug
