Repository TencentBlueKing/bk-sops, pull requests merged in 2023-06, with the labels that each got.

#6775 页面中英文切换按钮失效问题
  frontend/desktop/src/assets/html/index.html
  frontend/desktop/src/components/layout/NavigatorHeadRight.vue
Labels: type/bug

#6774 新增通过 BKPAAS_BK_MODAIN 环境变量获取环境域名
  env.py
  gcloud/core/context_processors.py
Labels: type/optimization

#6772 网关默认分支条件拖动后，保存报错问题修复
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/bug

#6778 支持动态计算参数显示隐藏
  gcloud/tasktmpl3/apis/django/api.py
  gcloud/tasktmpl3/domains/constants.py
  gcloud/tasktmpl3/urls.py
  gcloud/tests/tasktmpl3/domains/constants/test_preview_task_referenced_constants.py
  pipeline_web/graph.py
  pipeline_web/preview_base.py
  pipeline_web/tests/graph.py
  requirements.txt
Labels: type/feature

#6783 计划任务添加日志和启动失败判断
  gcloud/clocked_task/tasks.py
Labels: type/optimization

#6782 bugfix: 修复paasv2 ipv6 开启时环境变量BK_API_URL_TMPL的问题
  config/default.py
  env.py
Labels: type/bug

#6780 第三方插件任务节点配置快照未加载问题修复
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
Labels: type/bug

#6785 minor: release V3.28.11
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6789 流程列表标签列支持过滤
  frontend/desktop/src/components/common/TableRenderHeader.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
Labels: type/optimization

#6779 填参页面展示优化
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/pages/task/ParameterInfo.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
  frontend/desktop/src/scss/iconfont.scss
Labels: type/optimization

#6784 动态变量合入问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagInt.vue
  frontend/desktop/src/pages/task/ParameterInfo.vue
Labels: type/bug

#6799 内置插件隔离
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/store/modules/atomForm.js
Labels: type/feature

#6796 插件搜索框粘贴后自动搜索问题修复&&创建任务执行方案优化
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectPanel/plugin.vue
Labels: type/bug, type/optimization

#6801 插件详情接口404处理逻辑调整
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/optimization

#6800 ip选择器agent状态错误修复
  frontend/desktop/src/components/common/RenderForm/IpSelector/IpSelectorTable.vue
Labels: type/bug

#6807 填参页面展示优化
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/pages/task/ParameterInfo.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
Labels: type/optimization

#6809 修复若干 Yaml 导入导出问题
  gcloud/template_base/domains/schema_converter.py
  gcloud/tests/template_base/schema_converter/test_complicated_yaml_data.yaml
Labels: type/bug

#6815 跨系统国际化处理&&ip选择器agent异常态数量批量操作问题修复
  frontend/desktop/src/api/index.js
  frontend/desktop/src/assets/html/index.html
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
  frontend/desktop/src/components/layout/NavigatorHeadRight.vue
Labels: type/optimization

#6817 minor: release V3.28.12
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6813 minor: 新增注入esb的变量
  gcloud/core/context_processors.py
Labels: type/optimization

#6818 首页注入ESB变量
  gcloud/core/context_processors.py
Labels: type/optimization

#6822 merge_master_to_heron
  frontend/desktop/src/assets/html/index.html
Labels: ignore-for-release-notes

#6824 minor: release V3.26.13
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.26.13_2023-06-26.md
Labels: ignore-for-release-notes

#6825 流程克隆需要判断是否同时有查看和编辑的权限
  frontend/desktop/src/pages/commonManage/CommonTplList.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
Labels: type/optimization, stage/for_test

#6826 前端国际化优化
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/RenderForm/HostAllocation/HostFilter.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/IpSelectorTable.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/SingleIpSelector.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/index.vue
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceFilter.vue
  frontend/desktop/src/components/common/TableRenderHeader.vue
  frontend/desktop/src/components/common/TableSettingContent.vue
  frontend/desktop/src/components/layout/NavigatorHeadRight.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/admin/manage/AdminSearch/SearchResult.vue
  frontend/desktop/src/pages/admin/statistics/Template.vue
  frontend/desktop/src/pages/appmaker/index.vue
  frontend/desktop/src/pages/atomdev/TagPanel.vue
  frontend/desktop/src/pages/atomdev/configPanel/ConfigPanel.vue
  frontend/desktop/src/pages/atomdev/index.vue
  frontend/desktop/src/pages/commonManage/CommonTplList.vue
  frontend/desktop/src/pages/functor/FunctionList.vue
  frontend/desktop/src/pages/home/MyCollection.vue
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/ClockedList/index.vue
  frontend/desktop/src/pages/task/PeriodicList/index.vue
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/task/TaskExecute/GatewaySelectDialog.vue
  frontend/desktop/src/pages/task/TaskExecute/InjectVariableDialog.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/ReuseVarDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/SystemVariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableClone.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
  frontend/desktop/src/scss/common.scss
Labels: type/optimization

#6821 后台国际化优化
  en_docs/features/remote_plugins.md
  gcloud/core/footer/sites/open/footer.py
  gcloud/tasktmpl3/models.py
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
  locale/zh_hans/LC_MESSAGES/django.po
  pipeline_plugins/components/collections/gse_kit/flush_process/v1_0.py
  pipeline_plugins/components/collections/gse_kit/job_exec/v1_0.py
Labels: type/optimization

#6827 minor: release V3.28.13
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6829 后端国际化补充
  gcloud/taskflow3/models.py
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
  pyproject.toml
Labels: type/optimization

#6828 前端国际化优化
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/admin/statistics/Template.vue
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/atomdev/TagPanel.vue
  frontend/desktop/src/pages/atomdev/formPanel/FormPanel.vue
  frontend/desktop/src/pages/atomdev/index.vue
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateList/ExportTemplateDialog.vue
Labels: type/optimization

#6830 前端国际化优化
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/project/config.vue
Labels: type/optimization

#6832 项目管理tab栏国际化添加复数s
  frontend/desktop/src/config/i18n/en.js
Labels: type/optimization

#6833 画布缩放时左侧功能栏新建节点自动连线触发区间、两侧端点计算异常问题修复
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
Labels: type/bug

#6834 变量描述设置上限10行
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
Labels: type/optimization

#6839 跨流程语言切换中文字段英文错误修改
  frontend/desktop/src/components/layout/NavigatorHeadRight.vue
Labels: type/bug

#6840 创建任务填参时，是否未能重用表单项判断错误修复/下拉框选项粘贴问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
  frontend/desktop/src/pages/task/TaskParamEdit.vue
Labels: type/bug

#6844 变量描述优化
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/optimization

#6845 template不支持问号写法问题修复
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#6846 template不支持问号写法问题修复
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#6848 画布缩放时左侧功能栏新建节点自动连线触发区间、两侧端点计算异常问题修复
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
Labels: type/bug
