Repository TencentBlueKing/bk-sops, pull requests merged in 2023-03, with the labels that each got.

#6585 bugfix: 修复画布排版时并行网关之后的节点高度异常的问题
  pipeline_web/drawing_new/dummy.py
Labels: type/bug

#6586 流程标签筛选支持多id查询，多流程标签切换为或查询逻辑
  gcloud/core/apis/drf/viewsets/common_template.py
  gcloud/core/apis/drf/viewsets/task_template.py
Labels: type/optimization

#6596 子流程节点编辑时隐藏未引用自定义变量
  pipeline_web/preview.py
  pipeline_web/tests/prview/test_preview.py
Labels: type/bug

#6599 minor: release V3.26.7
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.26.7_2023-03-07.md
Labels: ignore-for-release-notes

#6602 apigw注册的版本号添加时间戳
  config/default.py
  gcloud/apigw/management/commands/data/api-definition.yml
Labels: type/optimization

#6606 修复创建集群插件校验失败问题
  pipeline_plugins/components/collections/sites/open/cc/create_set/legacy.py
  pipeline_plugins/components/collections/sites/open/cc/create_set/v1_0.py
  pipeline_plugins/components/collections/sites/open/cc/create_set/v2_0.py
  pipeline_plugins/tests/components/collections/sites/open/cc_test/create_set/test_v2_0.py
Labels: type/bug

#6610 release V3.26.8
  app.yml
  app_desc.yaml
  config/default.py
  version_logs_md/V3.26.8_2023-03-08.md
Labels: ignore-for-release-notes

#6631 修复公共空间用户查询接口无配置时报错问题
  gcloud/core/apis/drf/viewsets/common_space.py
  gcloud/core/apis/drf/viewsets/utils.py
Labels: type/bug

#6634 前后端上下文添加PaaS平台版本信息
  config/default.py
  env.py
  gcloud/core/context_processors.py
Labels: type/optimization

#6635 apigw-manager version bumps to 1.1.6
  requirements.txt
Labels: type/optimization

#6642 职能化任务添加id过滤方式
  gcloud/core/apis/drf/viewsets/function_task.py
Labels: type/bug

#6646 修复cmdb业务数据life_cycle字段为null时业务同步失败问题
  gcloud/core/project.py
Labels: type/bug

#6651 集群模块ip选择器去除module_name填参项
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
  pipeline_plugins/variables/static/variables/cmdb/var_set_module_ip_selector.js
Labels: type/optimization

#6671 minor: version bumps to V3.28.2
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6673 修复get_task_status接口子流程状态查询报错问题
  gcloud/taskflow3/utils.py
Labels: type/bug

#6666 optimization: 职能化任务支持转化成普通任务并直接执行
  gcloud/core/apis/drf/serilaziers/taskflow.py
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: type/optimization
