Repository TencentBlueKing/bk-sops, pull requests merged in 2023-08, with the labels that each got.

#6957 修复修改周期任务更新时间不会变化问题
  gcloud/core/apis/drf/viewsets/periodic_task.py
Labels: type/bug

#6959 修复独立子流程终止时父流程对应节点没有失败问题
  gcloud/taskflow3/signals/handlers.py
Labels: type/bug

#6965 feature: 标准插件前端国密改造
  docs/develop/tag_usage_dev.md
  en_docs/develop/tag_usage_dev.md
  frontend/desktop/package.json
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/RenderForm.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagPassword.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/store/index.js
Labels: type/feature

#6962 集群资源筛选非数字输入框输入问题修复
  frontend/desktop/package.json
Labels: type/optimization

#6961 输入框增加长度限制交互
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/project/index.vue
  frontend/desktop/src/pages/task/ClockedList/EditClockedTask.vue
  frontend/desktop/src/pages/task/PeriodicList/ModifyPeriodicDialog.vue
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskExecute/InjectVariableDialog.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskFunctionalization.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  frontend/desktop/src/pages/task/TaskList/TaskCloneDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/ReuseVarDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateSnapshoot.vue
Labels: type/optimization

#6968 独立子流程消息通知、执行代理人继承父流程配置
  gcloud/taskflow3/signals/handlers.py
Labels: type/optimization

#6974 节点树重构&子流程详情查看与操作优化
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/assets/js/flow.js
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteRecord.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/InputParams.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTreeItem.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/scss/iconfont.scss
Labels: type/optimization, type/feature

#6973 轻应用找不到执行方案入口问题优化
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
Labels: type/optimization

#6975 修复 ip 选择器 topo 过滤所有节点都失效时选中所有 ip 问题
  pipeline_plugins/cmdb_ip_picker/utils.py
Labels: type/bug

#6970 修复job失败时提取变量取不到step_ip_result_list的bug
  pipeline_plugins/components/collections/sites/open/job/base.py
Labels: type/bug

#6976 minor: release V3.29.2
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#6979 轻应用初始化支持使用默认执行方案
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: type/optimization

#6980 轻应用初始化支持使用默认执行方案
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: type/optimization

#6903 执行中状态添加时间范围限制
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: type/bug

#6966 修复job作业跳转id的问题
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_1.js
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_2.js
Labels: type/bug

#6930 优化get_node_data_v2加载速度
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/tasktmpl3/domains/constants.py
  gcloud/tests/mock_settings.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py
Labels: type/optimization

#6910 修复监控插件失败无异常输出的问题
  pipeline_plugins/components/collections/sites/open/monitor/base.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield/test_v1_1.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield_strategy/test_v1_1.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield_strategy/test_v1_2.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/test_alarm_shield.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/test_alarm_shield_strategy.py
Labels: type/bug

#6971 优化网关接口无权限时的展示
  gcloud/apigw/decorators.py
Labels: type/optimization

#6984 优化get_node_data_v2 的运行速度
  gcloud/taskflow3/domains/dispatchers/node.py
  gcloud/tasktmpl3/domains/constants.py
  gcloud/tests/mock_settings.py
  gcloud/tests/taskflow3/dispatchers/node/node_command_dispatcher/test_get_node_data_v2.py
Labels: type/optimization

#6985 修复监控插件失败无异常输出的问题
  pipeline_plugins/components/collections/sites/open/monitor/base.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield/test_v1_1.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield/test_v1_2.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield_strategy/test_v1_1.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/alarm_shield_strategy/test_v1_2.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/test_alarm_shield.py
  pipeline_plugins/tests/components/collections/sites/open/monitor_test/test_alarm_shield_strategy.py
Labels: type/bug

#6963 修复更新集群属性插件集群多选时更新失败的问题
  pipeline_plugins/components/collections/sites/open/cc/base.py
  pipeline_plugins/components/collections/sites/open/cc/update_set/legacy.py
  pipeline_plugins/components/collections/sites/open/cc/update_set/v1_0.py
Labels: type/bug

#6987 节点输入参数布局调整
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
Labels: type/optimization

#6990 自测问题修复
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#6993 支持批量任务状态查询接口
  gcloud/iam_auth/view_interceptors/taskflow.py
  gcloud/taskflow3/apis/django/api.py
  gcloud/taskflow3/apis/django/validators.py
  gcloud/taskflow3/urls.py
Labels: type/feature

#6994 ip 选择器动态分组先过滤失效分组再进行查询
  gcloud/utils/cmdb.py
  pipeline_plugins/cmdb_ip_picker/utils.py
Labels: type/optimization

#6996 修复job 执行方案 默认版本跳转连接的问题
  pipeline_plugins/components/static/components/atoms/job/job_execute_task.js
Labels: type/bug

#6997 修复job 执行方案 默认版本跳转连接的问题，处理job host 下划线
  pipeline_plugins/components/static/components/atoms/job/execute_task/v1_0.js
  pipeline_plugins/components/static/components/atoms/job/job_execute_task.js
Labels: type/bug

#7001 horse测试问题修复
  frontend/desktop/src/assets/js/flow.js
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/EndPoint.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/StartPoint.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTreeItem.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/store/modules/task.js
Labels: type/bug, type/optimization

#7000 解决子流程预览异常的问题
  gcloud/tasktmpl3/domains/constants.py
Labels: type/optimization

#7002 删除执行方案新增相关的校验
  gcloud/template_base/apis/drf/viewsets/template_scheme.py
Labels: type/optimization

#7005 节点树独立子流程交互优化&&免渲染提示调整&&节点配置侧拉支持拖拽宽度
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicGroup.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicIp.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/IpSelectorTable.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/SingleIpSelector.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagCodeEditor.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteRecord.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/InputParams.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/NodeOperationFlow.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTreeItem.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/optimization

#7006 ip选择器失效tag添加disabled样式&&节点配置侧栏拖拽添加判断
  frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicGroup.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/DynamicIp.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/IpSelectorTable.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/optimization

#7011 bugfix: 修复轻应用template_scheme_id为空时导致异常的问题
  gcloud/template_base/apis/drf/viewsets/template_scheme.py
Labels: type/bug

#7012 独立子任务节点重试或跳过时更新父流程对应节点状态
  gcloud/taskflow3/admin.py
  gcloud/taskflow3/celery/tasks.py
  gcloud/taskflow3/domains/callback.py
  gcloud/taskflow3/models.py
Labels: type/optimization

#7013 apigw文档description描述补充
  gcloud/apigw/management/commands/data/api-definition.yml
Labels: type/optimization

#7015 文本框支持联想
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
Labels: type/feature

#7017 bugfix: 修复首页我的动态异常&任务列表缺少执行代理人的问题
  gcloud/core/apis/drf/serilaziers/taskflow_instance.py
  gcloud/core/apis/drf/viewsets/taskflow.py
Labels: type/bug

#7020 节点详情页测试体验问题优化
  frontend/desktop/src/components/common/RenderForm/IpSelector/IpSelectorTable.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteLog.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteRecord.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/InputParams.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/NodeLog.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/NodeOperationFlow.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/OutputParams.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTreeItem.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
  frontend/desktop/src/store/modules/task.js
Labels: type/bug, type/optimization

#7022 子流程操作二次确认弹框描述优化
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTreeItem.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
  frontend/desktop/src/scss/iconfont.scss
Labels: type/optimization

#7018 独立子任务交互优化
  gcloud/taskflow3/models.py
  pipeline_plugins/components/collections/subprocess_plugin/v1_0_0.py
Labels: type/optimization

#7024 子流程节点重试操作优化&&子流程画布优化&&子流程配置快照传参逻辑优化
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/InputParams.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/optimization

#7026 修复任务创建后查看节点详情，任务执行代理人提前确定问题
  gcloud/contrib/function/handlers.py
  gcloud/periodictask/signals/handlers.py
  gcloud/taskflow3/domains/context.py
  gcloud/taskflow3/domains/dispatchers/task.py
  gcloud/taskflow3/models.py
  gcloud/taskflow3/signals/__init__.py
  gcloud/tests/taskflow3/context/task_context/test_task_executor.py
  gcloud/tests/taskflow3/models/taskflow/test_executor_proxy.py
Labels: type/bug

#7029 horse版本优化
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTreeItem.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
Labels: type/bug, type/optimization

#7030 节点详情节点树算法问题修复
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7031 minor: release V3.29.4
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7032 文本框自测问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: type/bug

#7027 bugfix: 修复节点预览报错&&更新执行方案未正确刷新unique_id的值
  gcloud/tasktmpl3/domains/constants.py
  gcloud/template_base/apis/drf/viewsets/template_scheme.py
Labels: type/bug

#7034 执行方案删除失败后逻辑调整&&节点详情tab切换不支持滚动
  frontend/desktop/src/pages/task/TaskCreate/EditTaskScheme.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/optimization
