Repository TencentBlueKing/bk-sops, pull requests merged in 2023-09, with the labels that each got.

#7038 独立子任务创建是添加由父任务触发的操作记录
  gcloud/contrib/operate_record/constants.py
  pipeline_plugins/components/collections/subprocess_plugin/v1_0_0.py
Labels: type/optimization

#6967 minor: 更新bkui-form版本支持密码框只读态展示
  frontend/desktop/package.json
Labels: type/bug

#7041 bugfix: 修复ipv6环境下ip过滤器失效的问题
  pipeline_plugins/variables/collections/sites/open/ip_filter_base.py
Labels: type/bug

#7043 bugfix: 修复文本值下拉框变量传递时值异常的问题
  pipeline_plugins/variables/collections/common.py
Labels: type/bug

#7046 子流程节点执行详情输入参数展示异常问题优化
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/formMixins.js
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagHostAllocation.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagMemberSelector.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagSetAllocation.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/InputParams.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
  frontend/desktop/src/utils/checkDataType.js
Labels: type/optimization

#7062 minor: release V3.31.0-alpha
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7082 Horse版本提测问题修复
  frontend/desktop/package.json
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIp.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagSelect.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
  frontend/desktop/src/store/modules/taskList.js
Labels: type/bug, type/optimization

#7074 bugfix: 集群模块ip选择器空格的问题
  pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
Labels: type/bug

#7084 节点勾选/取消勾选逻辑错误问题修复&&文案修改
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
Labels: type/bug, type/optimization

#7086 变量勾选描述文案调整
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/OutputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/ReuseVarDialog.vue
Labels: type/optimization

#7090 变量取消勾选后是否自动删除变量只根据变量来源数判断
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/optimization

#7092 minor: 修复第三方插件日志get_paas_logs的401的问题
  plugin_service/plugin_client.py
Labels: type/bug

#7093 第三方插件日志接口请求方式改为post
  frontend/desktop/src/store/modules/atomForm.js
Labels: type/optimization

#7095 文案调整
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
Labels: type/optimization

#7097 release V3.31.0-alpha2
  app.yml
  app_desc.yaml
  config/default.py
  frontend/desktop/src/components/common/RenderForm/FormGroup.vue
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagInt.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTree.vue
  frontend/desktop/src/store/modules/atomForm.js
  locale/en/LC_MESSAGES/djangojs.mo
  locale/en/LC_MESSAGES/djangojs.po
  plugin_service/plugin_client.py
  version_logs_md/V3.31.0_2023-09-21.md
  version_logs_md_en/V3.31.0_2023-09-21.md
Labels: ignore-for-release-notes

#7098 批量更新页变量取消勾选逻辑优化
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
Labels: type/optimization

#7101 添加国际化
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
Labels: type/optimization

#7102 minor: pre-commit 适配 Python3.7
  .pre-commit-config.yaml
Labels: type/optimization
