Repository TencentBlueKing/bk-sops, pull requests merged in 2023-11, with the labels that each got.

#7156 可编辑div补充粘贴逻辑&&计划任务没有【执行历史】时展示调整
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/ClockedList/index.vue
Labels: type/bug, type/optimization

#7154 任务状态联调
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/NodeRightIconStatus.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTreeItem.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/index.vue
Labels: type/optimization

#7158 textareaTag换行判断逻辑错误修复
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
Labels: type/bug

#7159 minor: release_V3.31.3
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7162 minor: release_V3.31.4
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7163 对变量标签的内容进行unicode编码替换
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
Labels: type/bug

#7164 可编辑div空格编码特殊处理&&变量编辑页联想不到自定义节点问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/bug

#7165 minor: release_V3.31.5
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7136 ip选择器交互优化
  frontend/desktop/src/components/common/RenderForm/IpSelector/IpSelectorTable.vue
  frontend/desktop/src/components/common/RenderForm/IpSelector/StaticIpAddingPanel.vue
Labels: type/optimization

#7166 bugfix: 避免xss
  frontend/desktop/src/components/common/RenderForm/tags/TagCodeEditor.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
Labels: type/bug

#7167 inputTag粘贴时换行符替换为空格
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
Labels: type/optimization

#7168 分支节点对应的汇聚节点算法递归问题修复
  frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7171 divInput输入逻辑优化&&全局变量配置未更新问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/NodeTreeItem.vue
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
Labels: type/bug, type/optimization

#7172 minor: release V3.31.6
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7177 子流程交互优化
  frontend/desktop/src/components/common/TemplateCanvas/ToolPanel/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/optimization

#7182 子流程交互优化
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteRecord.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTreeItem.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug, type/optimization

#7184 V3.31线上测试问题修复
  frontend/desktop/src/pages/commonManage/CommonTplList.vue
  frontend/desktop/src/pages/home/SelectCreateTaskDialog.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateHeader.vue
Labels: type/bug, type/optimization

#7186 任务详情小画布网关选中和节点树联动
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTree.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTreeItem.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/optimization

#7196 minor: release V3.31.8
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7198 任务状态联调
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/NodeRightIconStatus.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/constants/index.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/NodeTreeItem.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
Labels: type/optimization

#7200 任务状态测试问题修复
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
Labels: type/optimization

#7201 支持第三方插件回调
  pipeline_plugins/components/collections/remote_plugin/v1_0_0.py
Labels: type/feature
