Repository TencentBlueKing/bk-sops, pull requests merged in 2024-06, with the labels that each got.

#7487 feat: 第三方插件节点支持配置最长执行时间
  config/default.py
  env.py
  pipeline_plugins/components/collections/controller.py
  pipeline_plugins/components/collections/remote_plugin/v1_0_0.py
Labels: type/feature

#7486 feat: 快速分发文件插件支持文件源类型 #7474
  pipeline_plugins/components/collections/sites/open/job/fast_push_file/v3_0.py
  pipeline_plugins/components/static/components/atoms/job/fast_push_file/v3_0.js
Labels: type/feature

#7494 bugfix: 第三方插件输入框失焦后未去拉取列表问题修复 #ignore
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
Labels: type/bug

#7499 fix: 项目全局配置可修改 && 退出登录添加参数
  frontend/desktop/package.json
  frontend/desktop/src/App.vue
  frontend/desktop/src/api/index.js
  frontend/desktop/src/assets/html/index.html
  frontend/desktop/src/components/layout/CopyrightFooter.vue
  frontend/desktop/src/components/layout/Navigation.vue
  frontend/desktop/src/components/layout/NavigatorHeadRight.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/store/index.js
Labels: type/optimization

#7502 fix: 轻应用页面查看任务url路径错误问题修复 #ignore
  frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
Labels: type/bug

#7510 feat: 第三方插件支持上传文件的同时传递参数 #7509
  plugin_service/plugin_client.py
Labels: type/feature

#7512 fix: 项目title、footer未国际化问题修复 #ignore
  frontend/desktop/src/components/layout/Navigation.vue
  frontend/desktop/src/store/index.js
Labels: type/bug

#7511 fix: 输入框文本框粘贴后保存数据为空问题修复 --ignore
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
Labels: type/bug

#7508 fix: 元变量隐藏时父流程引用问题处理
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug

#7507 feat: 支持蓝鲸审计中心 #7506
  config/default.py
  env.py
  gcloud/contrib/analysis/decorators.py
  gcloud/contrib/analysis/views.py
  gcloud/contrib/appmaker/api.py
  gcloud/contrib/audit/instances.py
  gcloud/contrib/audit/serializers.py
  gcloud/contrib/audit/utils.py
  gcloud/core/apis/drf/viewsets/appmaker.py
  gcloud/core/apis/drf/viewsets/common_template.py
  gcloud/core/apis/drf/viewsets/function_task.py
  gcloud/core/apis/drf/viewsets/periodic_task.py
  gcloud/core/apis/drf/viewsets/project.py
  gcloud/core/apis/drf/viewsets/task_template.py
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/taskflow3/apis/django/api.py
  gcloud/tasktmpl3/models.py
  requirements.txt
Labels: type/feature

#7515 fix: 插件开发页面打不开问题修复 && 任务撤销后节点详情还显示操作按钮问题修复
  frontend/desktop/package.json
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeAction/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/index.vue
  frontend/desktop/src/utils/serializeObj.js
Labels: type/bug
