Repository TencentBlueKing/bk-sops, pull requests merged in 2024-08, with the labels that each got.

#7520 fix: 子流程批量更新问题 #7519
  gcloud/tasktmpl3/apis/drf/viewsets/batch_form_with_schemes.py
Labels: type/bug

#7532 fix: 节点clone时勾选的输出变量clone逻辑异常问题修复 && 项目名统一规范调整 #ignore
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeExecuteInfo/components/ExecuteInfoForm.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/store/index.js
  frontend/desktop/src/store/modules/template.js
Labels: type/bug, type/optimization

#7535 feat: 流程列表支持过滤和展示执行代理人 #7533
  gcloud/core/apis/drf/viewsets/task_template.py
Labels: type/feature

#7537 fix: 流程列表支持过滤和展示执行代理人 #7533
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
Labels: type/optimization

#7539 fix: 文本框组件\n为渲染问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
Labels: type/bug

#7454 feat: 配置平台(CMDB) 相关插件支持 云区域:IP #7432
  gcloud/utils/cmdb.py
  pipeline_plugins/components/collections/sites/open/cc/base.py
  pipeline_plugins/components/collections/sites/open/cc/batch_update_host/v1_0.py
  pipeline_plugins/components/collections/sites/open/cc/update_host/legacy.py
  pipeline_plugins/tests/components/collections/sites/open/cc/base/test_cc_get_host_id_by_cloudid_innerip.py
  pipeline_plugins/tests/components/collections/sites/open/cc/base/test_cc_get_host_id_by_innerip.py
  pipeline_plugins/tests/components/collections/sites/open/cc_test/batch_update_host/test_v1_0.py
Labels: type/feature

#7541 create_and_start_task新增回调功能 #7540
  gcloud/apigw/views/create_and_start_task.py
Labels: type/feature

#7542 master_2_hb_20240823
  frontend/desktop/package.json
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/template/TemplateList/projectTplList.vue
  gcloud/apigw/views/create_and_start_task.py
  gcloud/core/apis/drf/viewsets/task_template.py
  gcloud/utils/cmdb.py
  pipeline_plugins/components/collections/sites/open/cc/base.py
  pipeline_plugins/components/collections/sites/open/cc/batch_update_host/v1_0.py
  pipeline_plugins/components/collections/sites/open/cc/update_host/legacy.py
  pipeline_plugins/tests/components/collections/sites/open/cc/base/test_cc_get_host_id_by_cloudid_innerip.py
  pipeline_plugins/tests/components/collections/sites/open/cc/base/test_cc_get_host_id_by_innerip.py
  pipeline_plugins/tests/components/collections/sites/open/cc_test/batch_update_host/test_v1_0.py
Labels: ignore-for-release-notes

#7547 fix: ip选择器接口调用逻辑优化 #7543
  frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
Labels: type/bug

#7548 fix: ip选择器接口调用自测问题修复 #7543
  frontend/desktop/src/components/common/RenderForm/tags/TagIpSelector.vue
Labels: type/bug
