Repository TencentBlueKing/bk-sops, pull requests merged in 2024-02, with the labels that each got.

#7344 fix: 任务在执行前校验任务是否被删除 #7307
  .pre-commit-config.yaml
  gcloud/taskflow3/models.py
Labels: type/feature

#7336 fix: Hb版本测试问题修复
  frontend/desktop/src/App.vue
  frontend/desktop/src/components/layout/ProjectSelector.vue
  frontend/desktop/src/pages/admin/statistics/Template.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/utils/errorNotify.js
Labels: type/bug

#7350 feat: sync code from master branch V3.31.20 #ignore
  .gitignore
  bkcodeai.json
  config/default.py
  frontend/desktop/package.json
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskCreate/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/test/unit/components/RenderForm/combinePlugin.js
  frontend/desktop/test/unit/components/RenderForm/renderform.spec.js
  frontend/desktop/test/unit/components/RenderForm/singlePlugin.js
  frontend/desktop/test/unit/jest.conf.js
  frontend/desktop/test/unit/setup.js
  gcloud/core/apis/drf/serilaziers/common_template.py
  gcloud/core/apis/drf/serilaziers/project_config.py
  gcloud/core/apis/drf/serilaziers/task_template.py
  gcloud/tasktmpl3/domains/constants.py
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
  locale/zh_hans/LC_MESSAGES/django.mo
  locale/zh_hans/LC_MESSAGES/django.po
Labels: ignore-for-release-notes

#7353 feat: release_V3.31.21 #ignore
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7355 refactor: paas V3 private_token 调用方式调整 #7354
  gcloud/taskflow3/domains/node_log.py
  plugin_service/plugin_client.py
Labels: type/optimization

#7357 perf: get_task_status 添加报错日志 #ignore
  gcloud/apigw/views/get_task_status.py
Labels: type/optimization

#7346 feat: 通知中心代码迁移 #7309
  frontend/desktop/package.json
  frontend/desktop/src/App.vue
  frontend/desktop/src/assets/html/index-dev.html
  frontend/desktop/src/assets/html/index.html
  frontend/desktop/src/pages/admin/manage/index.vue
  frontend/desktop/src/pages/admin/statistics/index.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskCreate/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
Labels: type/feature

#7335 fix: meta变量复用不去更新变量配置和值
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug

#7360 feat: release_V3.31.22 #ignore
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7361 fix: 修复失败节点下跳过icon点击报错的问题 --bug=120214755
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7369 chore: 更新vue版本 --ignore
  frontend/desktop/package.json
Labels: type/optimization
