Repository TencentBlueKing/bk-sops, pull requests merged in 2024-04, with the labels that each got.

#7406 feat: release V3.31.25 #ignore
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7408 fix: 修复节点管理插件调用安装通道失败问题 #7397
  pipeline_plugins/components/static/components/atoms/nodeman/create_task/v6_0.js
Labels: type/bug

#7404 chore: webpack升级
  frontend/desktop/builds/webpack.base.js
  frontend/desktop/builds/webpack.dev.config.js
  frontend/desktop/builds/webpack.prod.config.js
  frontend/desktop/package-lock.json
  frontend/desktop/package.json
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu/NodeMenu.vue
  frontend/desktop/src/components/layout/Navigation.vue
  frontend/desktop/src/components/layout/NavigatorHeadRight.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/JsonschemaForm.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/JsonschemaInputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectPanel/plugin.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
Labels: type/optimization

#7410 fix: 节点管理插件调用安装通道时提供默认通道 #7379
  pipeline_plugins/components/collections/sites/open/nodeman/create_task/v4_0.py
  pipeline_plugins/components/static/components/atoms/nodeman/create_task/v6_0.js
Labels: type/bug

#7400 perf: 周期任务的执行人改为周期更新人 #7368
  .pre-commit-config.yaml
  gcloud/core/apis/drf/viewsets/periodic_task.py
Labels: type/optimization

#7415 fix: 周期任务编辑下拉框 value保存问题 --bug=116848222
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
Labels: type/bug

#7422 Feature periodic task optimization master
  app.yml
  app_desc.yaml
  config/default.py
  env.py
  gcloud/contrib/admin/urls.py
  gcloud/contrib/admin/views/command.py
  gcloud/core/apis/drf/viewsets/periodic_task.py
  gcloud/core/tasks.py
  gcloud/core/templates/core/period_task_notice_mail.html
  version_logs_md/V3.32.0_2024-04-16.md
  version_logs_md_en/V3.32.0_2024-04-16.md
Labels: ignore-for-release-notes

#7409 chore: 更新部分前端依赖 --ignore
  frontend/desktop/package-lock.json
  frontend/desktop/package.json
  frontend/desktop/src/api/index.js
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceList.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/mobile/package.json
Labels: type/optimization

#7429 fix: 修复节点管理插件操作的bk-collector插件获取插件版本失败问题 #7423
  pipeline_plugins/components/query/sites/open/nodeman.py
Labels: type/bug

#7431 Dependencies udpate merge master
  app.yml
  app_desc.yaml
  config/default.py
  env.py
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  gcloud/contrib/admin/urls.py
  gcloud/contrib/admin/views/command.py
  gcloud/core/apis/drf/viewsets/periodic_task.py
  gcloud/core/tasks.py
  gcloud/core/templates/core/period_task_notice_mail.html
  pipeline_plugins/components/query/sites/open/nodeman.py
  version_logs_md/V3.32.0_2024-04-16.md
  version_logs_md_en/V3.32.0_2024-04-16.md
Labels: ignore-for-release-notes

#7414 fix: 验收会问题修复
  frontend/desktop/src/assets/fonts/bksops-icon.eot
  frontend/desktop/src/assets/fonts/bksops-icon.svg
  frontend/desktop/src/assets/fonts/bksops-icon.ttf
  frontend/desktop/src/assets/fonts/bksops-icon.woff
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/components/common/TemplateCanvas/options.js
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/mixins/task.js
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeCanvas/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/index.vue
  frontend/desktop/src/pages/task/TaskExecute/InjectVariableDialog.vue
  frontend/desktop/src/pages/task/TaskExecute/ModifyParams.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/scss/iconfont.scss
  frontend/desktop/src/scss/task.scss
Labels: type/bug, type/optimization

#7417 feat: release V3.33.0
  api/collections/nodeman.py
  app.yml
  app_desc.yaml
  config/default.py
  gcloud/iam_auth/signals/handlers.py
  pipeline_plugins/components/collections/sites/open/nodeman/create_task/v4_0.py
  pipeline_plugins/components/collections/sites/open/nodeman/create_task/v6_0.py
  pipeline_plugins/components/query/sites/open/nodeman.py
  pipeline_plugins/components/static/components/atoms/nodeman/create_task/v6_0.js
  version_logs_md/V3.33.0_2024-04-15.md
  version_logs_md_en/V3.33.0_2024-04-15.md
Labels: ignore-for-release-notes

#7436 release V3.33.0-bata1
  app.yml
  app_desc.yaml
  config/default.py
  env.py
  frontend/desktop/builds/webpack.base.js
  frontend/desktop/builds/webpack.dev.config.js
  frontend/desktop/builds/webpack.prod.config.js
  frontend/desktop/package-lock.json
  frontend/desktop/package.json
  frontend/desktop/src/api/index.js
  frontend/desktop/src/components/common/RenderForm/FormItem.vue
  frontend/desktop/src/components/common/RenderForm/SetAllocation/ResourceList.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagDatatable.vue
  frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/NodeMenu/NodeMenu.vue
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/components/layout/Navigation.vue
  frontend/desktop/src/components/layout/NavigatorHeadRight.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeExecuteInfo/components/common/JsonschemaForm.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/JsonschemaInputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/SelectPanel/plugin.vue
  frontend/desktop/src/pages/template/TemplateList/index.vue
  frontend/mobile/package.json
  gcloud/analysis_statistics/data_migrate/tasks.py
  gcloud/analysis_statistics/tasks.py
  gcloud/clocked_task/tasks.py
  gcloud/contrib/admin/urls.py
  gcloud/contrib/admin/views/command.py
  gcloud/contrib/cleaner/tasks.py
  gcloud/core/apis/drf/viewsets/periodic_task.py
  gcloud/core/tasks.py
  gcloud/core/templates/core/period_task_notice_mail.html
  gcloud/external_plugins/tasks.py
  gcloud/iam_auth/tasks.py
  gcloud/taskflow3/celery/tasks.py
  pipeline_plugins/components/query/sites/open/nodeman.py
  requirements.txt
  support-files/supervisord.conf
  version_logs_md/V3.32.0_2024-04-16.md
  version_logs_md_en/V3.32.0_2024-04-16.md
Labels: ignore-for-release-notes
