Repository TencentBlueKing/bk-sops, pull requests merged in 2024-01, with the labels that each got.

#7268 fix: 变量免渲染兼容第三方插件
  frontend/desktop/src/components/common/RenderForm/tags/TagCodeEditor.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug

#7271 feat: release V3.31.12
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7273 插件配置项免渲染默认值逻辑判断异常修复
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
Labels: type/bug

#7275 创建任务选择节点时，画布默认选中不符合默认执行方案问题修复
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: type/bug

#7274 添加项目不存在或已归档异常提示
  frontend/desktop/src/App.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
Labels: type/optimization

#7279 commitlint 添加issue id 检查
  .pre-commit-config.yaml
  commitlint.config.js
Labels: ignore-for-release-notes

#7278 修复独立子流程节点循环历史输入显示问题
  gcloud/taskflow3/domains/dispatchers/node.py
Labels: type/bug

#7281 Release humming bird merge master
  .pre-commit-config.yaml
  commitlint.config.js
  frontend/desktop/src/components/common/RenderForm/tags/TagCodeEditor.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskList/index.vue
  frontend/desktop/src/pages/template/TemplateEdit/BatchUpdateDialog.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  gcloud/taskflow3/utils.py
  gcloud/tests/utils/test_crypto.py
  gcloud/utils/crypto.py
Labels: ignore-for-release-notes

#7282 fix: 非独立子流程节点操作完以后重新加载节点详情
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7280 第三方插件任务节点配置快照版本与选择的版本不同问题修复&&轻应用创建任务默认使用自身选中的执行方案
  frontend/desktop/src/components/layout/ProjectSelector.vue
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/appmaker/index.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
Labels: type/bug

#7286 创建执行方案/创建任务时，添加未勾选节点样式 &&节点自动重试时需刷新节点详情
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/index.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7285 修复插件跨业务修改后部分组件数据未清空问题
  pipeline_plugins/components/static/components/atoms/cc/batch_delete_set/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/cc_batch_delete_set.js
  pipeline_plugins/components/static/components/atoms/cc/cc_empty_set_hosts.js
  pipeline_plugins/components/static/components/atoms/cc/cc_transfer_host_module.js
  pipeline_plugins/components/static/components/atoms/cc/cc_update_host.js
  pipeline_plugins/components/static/components/atoms/cc/cc_update_module.js
  pipeline_plugins/components/static/components/atoms/cc/cc_update_set.js
  pipeline_plugins/components/static/components/atoms/cc/cc_update_set_service_status.js
  pipeline_plugins/components/static/components/atoms/cc/create_module/legacy.js
  pipeline_plugins/components/static/components/atoms/cc/create_set/legacy.js
  pipeline_plugins/components/static/components/atoms/cc/create_set/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/create_set/v2_0.js
  pipeline_plugins/components/static/components/atoms/cc/create_set_by_template/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/empty_set_hosts/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/transfer_host_module/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/update_module/v1_0.js
  pipeline_plugins/components/static/components/atoms/cc/update_set/v1_0.js
  pipeline_plugins/components/static/components/atoms/monitor/alarm_shield/v1_2.js
Labels: type/bug

#7287 未选择任何节点时，添加一个错误message && 选择节点时隐藏节点重试/跳过标识
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: type/optimization

#7291 Master merge 2 release humming bird
  frontend/desktop/src/components/layout/ProjectSelector.vue
  frontend/desktop/src/pages/appmaker/AppEditDialog.vue
  frontend/desktop/src/pages/appmaker/index.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  gcloud/apigw/forms/get_task_list.py
  gcloud/apigw/views/get_task_list.py
  gcloud/contrib/admin/urls.py
  gcloud/contrib/admin/utils.py
  gcloud/contrib/admin/views/command.py
  pipeline_plugins/components/collections/remote_plugin/v1_0_0.py
  pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_2.py
Labels: ignore-for-release-notes

#7290 feat: 未选择任何节点时，添加一个错误message #6750
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
Labels: type/optimization

#7294 fix: 任务记录过滤180天判断逻辑异常修复 #7293
  frontend/desktop/src/pages/task/TaskList/index.vue
Labels: type/bug

#7297 feat: release V3.31.15 #ignore
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7298 fix: 执行代理人限制仅能设置为本人 #7289
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/store/modules/template.js
Labels: type/bug

#7296 feat: 添加 执行代理人 配置校验 #7289
  gcloud/core/apis/drf/serilaziers/common_template.py
  gcloud/core/apis/drf/serilaziers/project_config.py
  gcloud/core/apis/drf/serilaziers/task_template.py
  gcloud/core/apis/drf/viewsets/common_template.py
  gcloud/core/apis/drf/viewsets/task_template.py
Labels: type/feature

#7299 fix: 执行代理人限制仅能设置为本人 #7289
  frontend/desktop/src/store/modules/template.js
Labels: type/bug

#7300 fix: 执行代理人限制仅能设置为本人 #7289
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
Labels: type/bug

#7301 fix: 执行代理人限制仅能设置为本人
  frontend/desktop/src/config/i18n/cn.js
  frontend/desktop/src/config/i18n/en.js
  frontend/desktop/src/pages/project/config.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/BasicInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
  frontend/desktop/src/store/modules/template.js
Labels: type/bug

#7303 feat: release V3.31.16 #ignore
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7306 fix: 修复变量存在嵌套时预览变量输入失败的问题 #7305
  gcloud/tasktmpl3/domains/constants.py
Labels: type/bug

#7308 feat: release 3.31.17 #ignore
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7312 fix: 修复任务未启动时变量存在引用时异常的问题 #ignore
  app.yml
  app_desc.yaml
  config/default.py
  gcloud/tasktmpl3/domains/constants.py
Labels: type/bug

#7313 fix: 子任务网关失败支持跳过
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7324 fix: 接口400状态码报错信息不展现问题修复 --bug=119762901
  frontend/desktop/src/utils/errorNotify.js
Labels: type/bug

#7325 feat: release V3.31.19 #ignore
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7326 chore: 执行代理人英文翻译调整 --ignore
  frontend/desktop/src/config/i18n/en.js
Labels: type/optimization

#7347 refactor: 用户业务列表仅返回用户有权限的业务 #7317
  gcloud/core/apis/drf/viewsets/user_project.py
Labels: type/optimization

#7338 fix: 创建任务-默认节点勾选逻辑同步 --bug=119078037
  frontend/desktop/src/pages/task/TaskCreate/TaskScheme.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskCreate/index.vue
Labels: type/bug

#7348 feat: release_V3.31.20 #ignore
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes
