Repository TencentBlueKing/bk-sops, pull requests merged in 2024-03, with the labels that each got.

#7370 perf: 任务列表过滤实现注释 #6653
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/taskflow3/domains/dispatchers/task.py
Labels: type/optimization

#7373 feat: release V3.32.0-alpha3 #ignore
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7372 fix: 导入流程-分页后导致之前选择的数据被清空问题修复 --bug=116340266
  frontend/desktop/src/pages/template/TemplateList/ImportYamlTplDialog.vue
Labels: type/bug

#7363 fix: 修复模版删除时关联资源判断错误问题 #7362
  gcloud/template_base/models.py
Labels: type/bug

#7378 fix: 节点详情重构测试问题修复优化 --ignore
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeAction/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeExecuteInfo/components/ExecuteRecord/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeExecuteInfo/components/TaskCondition.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeExecuteInfo/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeTree/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/index.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7376 fix: 第三方插件执行详情输出展示问题修复 --bug=116432067
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
Labels: type/bug

#7379 feat: 任务状态展示支持降级 #6653
  config/default.py
  env.py
  gcloud/core/context_processors.py
  gcloud/taskflow3/domains/dispatchers/task.py
Labels: type/optimization

#7380 minor: hb merge master
  app.yml
  app_desc.yaml
  config/default.py
  frontend/desktop/package.json
  frontend/desktop/src/App.vue
  frontend/desktop/src/assets/html/index-dev.html
  frontend/desktop/src/assets/html/index.html
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/pages/admin/manage/index.vue
  frontend/desktop/src/pages/admin/statistics/index.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
  frontend/desktop/src/pages/task/TaskCreate/TaskSelectNode.vue
  frontend/desktop/src/pages/task/TaskCreate/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/InputParams.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/index.vue
  gcloud/apigw/views/get_task_status.py
  gcloud/taskflow3/domains/node_log.py
  pipeline_plugins/components/collections/controller.py
  plugin_service/plugin_client.py
Labels: ignore-for-release-notes

#7381 fix: 独立子流程任务状态降级 && master功能迁移 --ignore
  frontend/desktop/src/assets/html/index-dev.html
  frontend/desktop/src/assets/html/index.html
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/Subflow.vue
  frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeAction/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeExecuteInfo/index.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7382 fix: 代码合并功能不生效问题修复&&详情页加载loading优化 --ignore
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeExecuteInfo/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/index.vue
Labels: type/bug

#7389 fix: 锁死vue版本 && 节点详情loading加载逻辑调整 && 默认分支条件选中异常修复 --ignore
  frontend/desktop/package.json
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeCanvas/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeExecuteInfo/components/TaskCondition.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeExecuteInfo/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeTree/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/index.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7388 feat: get_functionalization_task_list获取职能化相关任务数据 #7374
  .pre-commit-config.yaml
  docs/apidoc/en/get_functionalization_task_list.md
  docs/apidoc/zh_hans/get_functionalization_task_list.md
  gcloud/apigw/forms/get_functionalization_task_list.py
  gcloud/apigw/views/get_functionalization_task_list.py
  gcloud/apigw/views/utils.py
Labels: stage/for_test

#7391 fix: 修复子任务超时后跳过时父任务状态未切换成执行中的问题
  gcloud/taskflow3/domains/node_timeout_strategy.py
Labels: type/bug

#7392 feat: release_V3.32.0-alpha5 #ignore
  app.yml
  app_desc.yaml
  config/default.py
Labels: ignore-for-release-notes

#7395 fix: 节点切换时记录小画布高度 && 子画布-节点树联动问题修复
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeCanvas/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeExecuteInfo/components/TaskCondition.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeExecuteInfo/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeTree/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/index.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7396 fix: 节点强制失败后状态流程未更新问题修复 --ignore
  frontend/desktop/src/components/common/TemplateCanvas/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeTree/index.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/index.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug
