Repository TencentBlueKing/bk-sops, pull requests merged in 2024-05, with the labels that each got.

#7447 fix: 轻应用体验问题修复
  frontend/desktop/builds/webpack.base.js
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
  frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
  frontend/desktop/src/pages/task/TaskExecute/index.vue
  frontend/desktop/src/scss/task.scss
Labels: type/bug

#7448 fix: 轻应用再次执行路由跳转错误问题修复 --ignore
  frontend/desktop/src/pages/appmaker/AppTaskHome/index.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
Labels: type/bug

#7452 feat: release v3.33.0 beta2
  app.yml
  app_desc.yaml
  config/default.py
  frontend/desktop/package.json
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeExecuteInfo/components/common/JsonschemaForm.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/JsonschemaInputParams.vue
  frontend/desktop/src/store/modules/task.js
  gcloud/core/tasks.py
Labels: ignore-for-release-notes

#7453 fix: 节点审批审批失败但出现审批成功message修复 && 任务名过长样式异常问题修复
  frontend/desktop/src/pages/task/TaskExecute/TaskOperation.vue
  frontend/desktop/src/pages/task/TaskExecute/TaskOperationHeader.vue
Labels: type/bug

#7455 release V3.32.4
  app.yml
  app_desc.yaml
  config/default.py
  frontend/desktop/package.json
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/JsonschemaForm.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/JsonschemaInputParams.vue
  gcloud/core/tasks.py
  requirements.txt
Labels: ignore-for-release-notes

#7438 chore: 中心统一登录窗口替换 --bug=116978891
  frontend/desktop/builds/webpack.prod.config.js
  frontend/desktop/package.json
  frontend/desktop/src/api/index.js
  frontend/desktop/src/assets/html/login_success.html
Labels: type/optimization

#7458 feat: release V3.32.5 #ignore
  api/collections/nodeman.py
  app.yml
  app_desc.yaml
  config/default.py
  frontend/desktop/builds/webpack.prod.config.js
  frontend/desktop/package.json
  frontend/desktop/src/api/index.js
  frontend/desktop/src/assets/html/login_success.html
  pipeline_plugins/cmdb_ip_picker/query.py
  pipeline_plugins/cmdb_ip_picker/utils.py
  pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_ip_filter.py
  pipeline_plugins/variables/collections/sites/open/ip_filter_base.py
Labels: ignore-for-release-notes

#7460 fix: 修复第三方插件$.context.bk_plugin_api_host未注入的问题 && 节点输出支持jsonschema格式渲染
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo.vue
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
  frontend/desktop/src/pages/template/TemplateEdit/NodeConfig/NodeConfig.vue
  frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
Labels: type/bug, type/optimization

#7461 perf: gse 1.0接口下线切换 #7440
  api/collections/nodeman.py
  pipeline_plugins/cmdb_ip_picker/query.py
  pipeline_plugins/cmdb_ip_picker/utils.py
  pipeline_plugins/tests/variables/collections/sites/open/cc/test_var_cmdb_ip_filter.py
  pipeline_plugins/variables/collections/sites/open/ip_filter_base.py
Labels: type/optimization

#7463 perf: 获取agent状态做分页获取优化 #7440
  api/collections/nodeman.py
  pipeline_plugins/cmdb_ip_picker/query.py
  pipeline_plugins/cmdb_ip_picker/utils.py
  pipeline_plugins/variables/collections/sites/open/ip_filter_base.py
Labels: type/optimization

#7439 fix: 修复公共流程无法重新执行，提示无权限问题 #7434
  gcloud/core/apis/drf/viewsets/taskflow.py
  gcloud/iam_auth/res_factory.py
  gcloud/iam_auth/utils.py
Labels: type/bug

#7437 fix: 修复脚本报错后重试后，脚本内容错误渲染问题 #7433
  gcloud/taskflow3/domains/dispatchers/node.py
Labels: type/bug

#7473 fix: 代码编辑框检测变量方法优化 && 文本框输入大量内容时卡死问题修复
  frontend/desktop/src/components/common/RenderForm/tags/TagCodeEditor.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagInput.vue
  frontend/desktop/src/components/common/RenderForm/tags/TagTextarea.vue
Labels: type/bug

#7476 fix: master合入hb遗留commit同步
  frontend/desktop/src/pages/task/TaskExecute/ExecuteInfo/components/NodeExecuteInfo/index.vue
Labels: type/bug
